### ISSUE TITLE
Create half-page ad placement

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#100]
> Half page ad will need to appear on desktop views in the upper right position

This is a problem because in the current design and css a half-page ad will not fit next to the featured image/media. (—the featured image and neighbouring ad are not within the flow of the article content, so expanding this section vertically will create a gap in the layout.) So this will require some reworking and might not be possible for monday. 

> There should always be two big box zones in the story, not just when the half-page ad is showing

I'm not understanding this. (There currently _are_ 2 bigbox images in the prototype.)
To clarify:
- There should always be 2 bigbox ads, one after paragraph 5, another crics 6 paragraphs before the end.
- In addition there will (often) be a half-page ad that appears only on "desktop" views. This ad must appear to the right of the article's featured image.

Is that correct?

I have an idea for how this can work but it will likely only be possible for viewports that are at least 1275px wide. Is that ok?

**Comment by alexgreen** [comment]
NEW AD SPECS

There are **3 ad spots**:
**3 ads visible at larger screen sizes**, and **2 (in the story flow) at smaller sizes**.

**Small screens**: 2 bigbox ads, one after paragraph 5, another circa 6 paragraphs before the end.

**Desktop views**: same as small screen but with the addition of  third ad appearing to the right of the article's featured image. This ad may be a bigbox or a half-page.

**Comment by phillipadsmith** [comment]
> NEW AD SPECS

Correct.

**Comment by alexgreen** [comment]
0dfd5b5b33e014d91ec436b79fa6e26fce8c34c3 implements the new halfpage ad format.
@phillipadsmith some of the ad-block parameters have changed (and also the name of the ad-box include itself) so you might need to update a couple things on the index page, but I'll try to do most of that now.

**Comment by alexgreen** [comment]
Currently the halfpage ad only shows up on viewports > 1400px. I believe that's still a bit smaller than the average laptop screen so I hope it's ok.

**Comment by alexgreen** [comment]
Ok, I think I've updated everything on the index page. Wasn't much to do there actually.

**Comment by phillipadsmith** [comment]
> Ok, I think I've updated everything on the index page. Wasn't much to do there actually.

Hmmm... I'm not crazy about this side-to-side layout that seems to break the grid, or is too far to the left or something. Feel very awkward to me.

Others? cc @kidcompassion @MrBryan 

<img width="1385" alt="_pennies_for_billions___aboriginals_fight_near_giveaway_of_pipeline_rights_in_1952___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/14835043/a293d936-0bbc-11e6-9f54-e3429195ab39.png">

**Comment by alexgreen** [comment]
It does align, just not with what you’re looking at. (See fig1) With an ad this size it isn’t possible to make it align with everything, so we have to choose which alignment we want. Because the original spec didn’t include ads of this size the layout wasn’t designed with these ads in mind. 

I think the current layout has a stronger visual unity than a strictly centred layout which can’t align with anything (see fig2).

The best solution would probably be to align the photo with the left edge of the article header and the text column and then put the ad in the left margin (se fig3). This would create a strong axis of alignment. But it would require a slightly wider breakpoint to display the ad (although I now see that it wouldn’t actually need to be much wider than the current breakpoint, maybe only about 20px). So this is the option I’d recommend. What do you think?

![fig1](https://cloud.githubusercontent.com/assets/151099/14856089/ab56c306-0cd1-11e6-83f4-738310222696.jpg)

![fig2](https://cloud.githubusercontent.com/assets/151099/14856090/ab59d320-0cd1-11e6-899c-9ab6fa4a8e87.jpg)

![fig3](https://cloud.githubusercontent.com/assets/151099/14856091/ab62338a-0cd1-11e6-9663-6e62373d866d.jpg)

**Comment by phillipadsmith** [comment]
> It does align, just not with what you’re looking at. (See fig1) 

Yes, but what it aligns with is not in the viewport at the time the user first sees the photo and advertisement.

This issue was always the case, as there was always an advertisement there of some kind, e.g., in the early layouts there was a big box, however the featured media was not expanding beyond the story margins.

> I think the current layout has a stronger visual unity than a strictly centred layout which can’t align with anything (see fig2).

I don't entirely agree because that the items in question are leaving the viewport at the time they align with items on the page. I'll get some input from others, as perhaps it's just me.

> The best solution would probably be to align the photo with the left edge of the article header and the text column and then put the ad in the left margin (se fig3).

I'll ask Michelle and Robyn. I don't personally like this option as it prioritizes an advertisement over content in the left-to-right scan.

cc'ing @kidcompassion @MrBryan for quick input.

**Comment by phillipadsmith** [comment]
Quick update: Robyn and Michelle didn't have any preference for version 1 vs. version 2 above. Version 3 was immediately vetoed with loud groaning sounds. ;-)

So, assuming that @kidcompassion @MrBryan have no conflicting input, I would say to go with your gut on this @alexgreen between 1 and 2. I can live with version 1.

**Comment by phillipadsmith** [comment]
Just to note, however, on my 13" retina screen the navigation bar doesn't appear to extend as far left as it does in your screenshots above, and that is what is throwing me off, i.e., that the left alignment of the navigation is not matching the left alignment of the photo.

**Comment by alexgreen** [comment]
> there was always an advertisement there of some kind, e.g., in the early layouts there was a big box, however the featured media was not expanding beyond the story margins.

Yes, because the ad is now more than double the height it used to be that means that the photo also has to be taller and therefore much wider (as you can see in fig4 below). I'm open to other suggestions, but if we want to keep the ad within the featured media section, then that section has to get wider, as it now is. Otherwise a huge gap will result.

> on my 13" retina screen the navigation bar doesn't appear to extend as far left as it does in your screenshots above, and that is what is throwing me off, i.e., that the left alignment of the navigation is not matching the left alignment of the photo.

That's not supposed to happen. It's the result of bug in the nav bar layout that was introduced as a measure to fix a prior nav bar bug (that one was causing the logo to enlarged enormously). Basically, this problem: #128.

> Version 3 was immediately vetoed with loud groaning sounds.

I actually think version 3 is the best layout and the most reader-friendly. I would argue strongly for this one. I'd say it's absolutely the least intrusive placement as it does affect the content flow all and it keeps the ad clearly segregated from the article. But it fig3 is off the table, then probably fig1 is the next best, but I'll try to find a better solution.

![fig4](https://cloud.githubusercontent.com/assets/151099/14891052/fe7a18a2-0d9f-11e6-8e51-8a2822fdedc6.jpg)

**Comment by alexgreen** [comment]
Here's another option. Maybe this a happy medium.
Fig 5. The photo is right-aligned with the article header and centred over the text column. The gets pushed a bit further right, so this means the breakpoint would have to increase yet another 30px or so.

![fig5](https://cloud.githubusercontent.com/assets/151099/14892307/3757246c-0da5-11e6-9dd8-f4bce6c8d75a.jpg)

**Comment by phillipadsmith** [comment]
Actually, I take my earlier comments back -- I like figure 5.

**Comment by phillipadsmith** [comment]
I take that back, I like figure 2.

**Comment by phillipadsmith** [comment]
Or 1

**Comment by MrBryan** [comment]
Fig 3 looks the cleanest to me, being used to seeing things align on the leading edge. But it gives a lot of prominence to the ad, which Michelle may like :)

Seems like the need to have the ad & image the same height is dictating what options can be used, perhaps css hacks could shrink the "gap" as needed since the ad size would be predictable right?

**Comment by MrBryan** [comment]
- returns to gallery

**Comment by alexgreen** [comment]
> Seems like the need to have the ad & image the same height is dictating what options can be used, perhaps css hacks could shrink the "gap" as needed since the ad size would be predictable right?

The ads are unpredictable (could be bigbox or half-page) and Phillip says these ads are contained within an iframe, so it wouldn't be possible with css alone but maybe someone's javascript wizardry could solve it.

**Comment by phillipadsmith** [comment]
Last comment to update this thread: Alex and I spoke this morning. Figure 3 was vetoed by Robyn and Michelle. So we're going to roll with figure 1 for now, and try to adjust the navigation to extend to the edges of the screen so the alignment issue I was seeing is not so prominent.

**Comment by MrBryan** [comment]
Re ad size predictability -- ah right -- working with iframe properties is always nightmare/fun depending on your outlook ;)  Perhaps a battle for another day.

Re #3 Glad to know we're all in sync with my choice vetoed already :P 
in fairness I liked it because of the aligned image to left edge — I agree that the ad does look awkward there which is probably what they reacted to...
