### ISSUE TITLE
Style footer 

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#101]
Using bootstrap column for this is really not ideal because BS doesn’t have any breakpoints below 750px (which is too wide in this case). This will probably need to get rebuilt.

**Comment by alexgreen** [comment]
This breakpoint should be at around 600px.

**Comment by phillipadsmith** [comment]
Well, it looks great! :-)

**Comment by phillipadsmith** [comment]
@alexgreen @kidcompassion This is resolved for now, yes?

**Comment by alexgreen** [comment]
Yes I think it's done.

**Comment by kidcompassion** [comment]
@phillipadsmith yup!
