### ISSUE TITLE
Overflow property on lead-in-text ?

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#103]
What's going on here @alexgreen ?

<img width="702" alt="localhost_4000" src="https://cloud.githubusercontent.com/assets/34128/14271569/31e0733e-faaf-11e5-8f5a-1386b46f9053.png">

**Comment by alexgreen** [comment]
I set the overflow to hidden, which sounds like a bad idea intuitively, but it eliminates the scrolling. 

However it creates an unsightly gap in the text flow.
Setting the overflow to visible closes this gap.
But it causes the dropcap to fall way down the page, which is much worse. (I have a feeling that this drop may only occur when an article has both a fact-box and a series-box, so maybe this is just an edge case.)
Obviously there's some kind of float scope problem. Any ideas, @phillipadsmith ?

...

![gap](https://cloud.githubusercontent.com/assets/151099/14293916/9a179afe-fba9-11e5-95cf-fa4aa5d73faf.png)

...

![no-gap](https://cloud.githubusercontent.com/assets/151099/14293935/b84a8306-fba9-11e5-9930-cd33f6b15d7c.png)

...

![big-drop](https://cloud.githubusercontent.com/assets/151099/14294016/0ccc6ce6-fbaa-11e5-936e-3d32b3a6a228.png)

**Comment by kidcompassion** [comment]
@alexgreen @phillipadsmith I'm closing this, since it appears to be resolved from these commits. Replace if there's more to be done.
