### ISSUE TITLE
Fix disappearing category and author info

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#104]
When I click on the inline anchor link to the fact-box it makes the category header disappear. It also causes the text in the .author-info block to change.

Category header: 
`<h6 class="category-label"><a href="#" data-bind="category">NEWS</a></h6>`

Inline anchor link:
`<a href="#fact-box-1" class="fact-box__anchor-link">Inline link to fact box.</a>`

**Comment by phillipadsmith** [comment]
Oh, yes, ha-ha! I know why... It's from the demo of loading content from the API. I'll remove that.

**Comment by phillipadsmith** [comment]
Fixed in develop with this commit: https://github.com/TheTyee/design-article.thetyee.ca/commit/d79b40f76bc0c2a73a3283c235005827bfbb0d84
