### ISSUE TITLE
Run /library.html and /index.html through Browserstack

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#105]
Run /library.html and /index.html through Browserstack to get a quick take on how we're doing across platforms, browser, devices, etc.

**Comment by kidcompassion** [comment]
@alexgreen Wait, I've only been testing /index. What is library? Like, I know what the page, is but is the difference that it's pure HTML, as opposed to the backbone one?

**Comment by kidcompassion** [comment]
@alexgreen NM, i just clued in. will check it as well.

**Comment by alexgreen** [comment]
Yeah, Library is actually the more important page to test because it includes all the components. Personally I would have kept the library page at the root and then put various specific page view examples in subdirectories.
