### ISSUE TITLE
Join icon in footer is misaligned everywhere

### ISSUE THREAD

**Issue by kidcompassion** [TheTyee/design-article.thetyee.ca#106]
It also doesn't show up in older versions of Android, but it falls back nicely.

Example of misalignment:
![uploads/5022cb8e-3ef2-4a61-bc13-db96dbb26db8/Screen Shot 2016-04-08 at 1.51.41 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F5022cb8e-3ef2-4a61-bc13-db96dbb26db8%2FScreen+Shot+2016-04-08+at+1.51.41+PM.png)

![uploads/defe53e6-a11d-414d-8ab1-0e52db86b57d/Screen Shot 2016-04-08 at 1.56.41 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fdefe53e6-a11d-414d-8ab1-0e52db86b57d%2FScreen+Shot+2016-04-08+at+1.56.41+PM.png)

![uploads/91e627a3-c144-484f-9b45-fc1042c6d16e/Screen Shot 2016-04-08 at 2.03.58 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F91e627a3-c144-484f-9b45-fc1042c6d16e%2FScreen+Shot+2016-04-08+at+2.03.58+PM.png)

**Comment by alexgreen** [comment]
Yeah, I figured that would be trouble. Aligning that icon relative to the text baseline is a hassle. Hopefully there will be a universal solution that works in every location on the page.

**Comment by alexgreen** [comment]
d2ea8bec54043d68eaea27990aa090cd3d0490f6 fixes join icon alignment in footer on chrome OS X, iOS, and android
