### ISSUE TITLE
Read more authour bio button doesn't do anything

### ISSUE THREAD

**Issue by kidcompassion** [TheTyee/design-article.thetyee.ca#107]
In the following environments:
Chrome on MacOs

![uploads/dcd964ce-96e6-43d6-9541-eb0fa3c6dd00/Screen Shot 2016-04-08 at 2.08.32 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fdcd964ce-96e6-43d6-9541-eb0fa3c6dd00%2FScreen+Shot+2016-04-08+at+2.08.32+PM.png)

**Comment by alexgreen** [comment]
What's the problem?

**Comment by alexgreen** [comment]
...oh yes, the idea is that it will just link to the author page. I though I had set the link url as "link-to-authors-page" but maybe not, or maybe it got changed in the drying out.

**Comment by alexgreen** [comment]
...so, no more expanding or collapsing. Just a bio teaser that gets truncated via CSS and a link to the author's page where the entire bio can be read in its full glory.
