### ISSUE TITLE
The search button says Submit, which seems weird.

### ISSUE THREAD

**Issue by kidcompassion** [TheTyee/design-article.thetyee.ca#108]
![uploads/7aff7fa2-5256-46c3-b530-dbec325fe146/Screen Shot 2016-04-08 at 2.10.43 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7aff7fa2-5256-46c3-b530-dbec325fe146%2FScreen+Shot+2016-04-08+at+2.10.43+PM.png)

**Comment by alexgreen** [comment]
I agree. Isn't that your purview?
