### ISSUE TITLE
Windows 8/IE10 Issues

### ISSUE THREAD

**Issue by kidcompassion** [TheTyee/design-article.thetyee.ca#109]
- [ ] Pretty much anything with the heart/$ icon breaks

![uploads/c5b5b1c7-beae-422a-8469-5fee3790525a/Screen Shot 2016-04-08 at 2.57.53 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fc5b5b1c7-beae-422a-8469-5fee3790525a%2FScreen+Shot+2016-04-08+at+2.57.53+PM.png)

![uploads/6664f231-3ebd-425a-bff5-3b2cfa262926/Screen Shot 2016-04-08 at 2.57.03 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6664f231-3ebd-425a-bff5-3b2cfa262926%2FScreen+Shot+2016-04-08+at+2.57.03+PM.png)

![uploads/b88b7b03-3f76-4ddb-a41f-2ad47b0830a8/Screen Shot 2016-04-08 at 2.54.01 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb88b7b03-3f76-4ddb-a41f-2ad47b0830a8%2FScreen+Shot+2016-04-08+at+2.54.01+PM.png)

![uploads/fcdba8b4-e48c-49bb-ae43-220b7d6a4584/Screen Shot 2016-04-08 at 2.54.27 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffcdba8b4-e48c-49bb-ae43-220b7d6a4584%2FScreen+Shot+2016-04-08+at+2.54.27+PM.png)

![uploads/6ba6653e-5bbd-456b-8f14-15cbbd250156/Screen Shot 2016-04-08 at 2.53.37 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6ba6653e-5bbd-456b-8f14-15cbbd250156%2FScreen+Shot+2016-04-08+at+2.53.37+PM.png)

**Comment by alexgreen** [comment]
well it wouldn't be real web project without at least one IE bug!

**Comment by alexgreen** [comment]
really thrilled to hear that the Join icon is is the only IE bug!!! this is the best news I've had in weeks!

**Comment by alexgreen** [comment]
Waiting on merge of Sally's recent commits.

**Comment by kidcompassion** [comment]
Resolved in bugs/testing-fixes branch, commit f6330cdbde1759db051077515e2166ea47c23a6a
