### ISSUE TITLE
Latest stories text is green on screens narrower than 992px

### ISSUE THREAD

**Issue by kidcompassion** [TheTyee/design-article.thetyee.ca#112]
- [ ] Latest slider text is green

![uploads/101f28e5-aa95-406b-a6da-a82ed704d0f7/Screen Shot 2016-04-10 at 1.58.03 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F101f28e5-aa95-406b-a6da-a82ed704d0f7%2FScreen+Shot+2016-04-10+at+1.58.03+PM.png)

**Comment by alexgreen** [comment]
As far as I can tell the latest story text is green everywhere on screens narrower than 992px.

**Comment by alexgreen** [comment]
This issue identifies 2 separate problems so I'm breaking it into 2 issues.
