### ISSUE TITLE
Windows 10 / Chrome

### ISSUE THREAD

**Issue by kidcompassion** [TheTyee/design-article.thetyee.ca#124]
- [x] Join icon in footer (man, one fix is going to solve like 20 cards!

![uploads/2f417749-d148-43c9-ba70-22cb9ca352c0/Screen Shot 2016-04-15 at 2.11.52 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F2f417749-d148-43c9-ba70-22cb9ca352c0%2FScreen+Shot+2016-04-15+at+2.11.52+PM.png)

**Comment by kidcompassion** [comment]
wound up being the width: auto on the icon on line 152 of article.css. i just took it out, and nothing else seemed to kerplode.

**Comment by alexgreen** [comment]
That css rule is required for proper sizing and spacing of the icon in chrome. Can you push all your commits to develop to I can see them?

**Comment by alexgreen** [comment]
... then I can have a look and see about using other rules for the sizing and spacing.

**Comment by alexgreen** [comment]
> Can you push all your commits to develop to I can see them?

Ah, ok I see you've pushed to a different branch. Thanks!

**Comment by alexgreen** [comment]
> one fix is going to solve like 20 cards!

Thanks for testing all these browser cases! Did removing this one rule really fix them all? That would be amazing!

**Comment by kidcompassion** [comment]
@alexgreen It really did! You should have seen my glee! :D

**Comment by alexgreen** [comment]
◦°˚( ͝° ͜ʖ͡°)/˚°◦
