### ISSUE TITLE
Set borders on header to span full viewport width

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#128]
Header doesn’t span width in wide viewports leaving the borders oddly truncated, because:

```
@media (min-width: 1200px)
.primary-nav {
    max-width: 1200px;
```

The top border on .site-nav .navbar-collapse and the bottom border on .menu_left-nav-wrap, .menu_right-nav-wrap should extend to the screen edge. (However, keeping the nav links closer to the center of the page in wide views, as they are now, is probably a good hting.)
So if the max-width rule is necessary then those borders may need to get applied to different elements.

**Comment by alexgreen** [comment]
> So if the max-width rule is necessary then those borders may need to get applied to different elements.

Another option might be to use left and right padding that is calculated via to fill the required space  a css calc function. I do a similar thing to dynamically set the margins of asides:

`margin-right: calc( -1 * (((100vw - 34em) / 2) - (1em)));`

...basically a function that sets an appropriate margin relative to the size of the viewport and known dimensions of other relevant elements. You could probably do something similar to set padding that would extend .menu_left-nav-wrap, .menu_right-nav-wrap to the edge of the viewport.

**Comment by kidcompassion** [comment]
Thanks for the feedback @alexgreen. We're doing a lot of back and forth on this issue; why don't you go ahead and build it however you want it- don't worry, you're not stepping on my toes AT ALL. That's probably the best use of time. Unless @phillipadsmith wants to take a crack at it?

**Comment by alexgreen** [comment]
I have plenty of other stuff to do and as you've already been working on the header and nav for quite a while I think trading it off to me at this stage will hold things up. although I could add it to the bottom of my list if necessary.

**Comment by kidcompassion** [comment]
k, i'll ask phillip what he thinks, since I think even if it went to the
bottom of the list it would be faster than the back and forth.

**Comment by phillipadsmith** [comment]
> k, i'll ask phillip what he thinks, since I think even if it went to the
> bottom of the list it would be faster than the back and forth.

Assigning to @MrBryan per conversation last Thursday.

**Comment by phillipadsmith** [comment]
@MrBryan Are you receiving? ;-)

**Comment by MrBryan** [comment]
yep i see this & two other issues assigned to me

**Comment by alexgreen** [comment]
see also #133

**Comment by phillipadsmith** [comment]
Also #138

**Comment by kidcompassion** [comment]
FYI @MrBryan @phillipadsmith @alexgreen I spent a couple of hours fighting with the full width nav bar underlines in the styles/nav-underline branch; I fixed the underlines but discovered something i didn't notice previously, which is that the fixed width at 1200 breaks the full-width dropdowns. Might be necessary to leave the nav totally fluid.

<img width="1280" alt="screen shot 2016-04-29 at 3 01 50 pm" src="https://cloud.githubusercontent.com/assets/1507827/14929576/574d4762-0e1b-11e6-8d83-4b2a1e7ac4ba.png">

**Comment by phillipadsmith** [comment]
> FYI @MrBryan @phillipadsmith @alexgreen I spent a couple of hours fighting with the full width nav bar underlines in the styles/nav-underline branch

The example image is looking pretty good to me. @alexgreen ?

**Comment by alexgreen** [comment]
Yeah, I think having a nav dropdown that doesn't run full width is ok.
I mentioned some other nav issues in #145

**Comment by phillipadsmith** [comment]
Okay, going to close this for now.
