### ISSUE TITLE
Create Series example story

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#130]
Hi @alexgreen,

Just checking that all the elements for a Series story are in the library.html now? If so, I'll flow in some real series content into an example story.

Phillip.

Article: 
http://thetyee.ca/News/2016/01/28/Nature-Death-Row-BC/

**Comment by alexgreen** [comment]
Yes, I believe the only necessary elements are the series-box and the series-badge. Those are done and I just now extracted the series badge into its own include.

**Comment by phillipadsmith** [comment]
> Yes, I believe the only necessary elements are the series-box and the series-badge. Those are done and I just now extracted the series badge into its own include.

Awesome. :-)

**Comment by phillipadsmith** [comment]
Okay, the series is mocked-up here:
http://thetyee.github.io/design-article.thetyee.ca/series.html

cc @MrBryan

**Comment by alexgreen** [comment]
Looks great! 
Nice use of the aside photo placement for the butterfly image.

**Comment by alexgreen** [comment]
... but I see only 1 ad.

**Comment by alexgreen** [comment]
... also, the final paragraph should be
`{% include 01-molecules/text/paragraph-with-end-mark.html %}`

If that's trouble I could probably use the `p:last-of-type:after` to target that paragraph and add the end-mark. (But I vaguely remember that something led me to avoid doing that.)

**Comment by phillipadsmith** [comment]
> ... but I see only 1 ad.
> ... also, the final paragraph should be

I'll fix these two issues up today. Thanks for spotting them.

**Comment by phillipadsmith** [comment]
> ... but I see only 1 ad.
> ... also, the final paragraph should be

I've fixed up those two issues.

I simply carried over the markup for the last paragraph because the content would not have been right if the include was used. Let me know if there's a more sensible way to be doing that (I kept the include for the end mark itself, so updates to that would be reflected).

**Comment by phillipadsmith** [comment]
One thing I noticed in the photo essay example, which is also a series, here: http://thetyee.github.io/design-article.thetyee.ca/slideshow.html

Is that in the original story there is often a blurb at the bottom, under the old bio, that says something like:

> This series was produced by Tyee Solutions Society. It was made possible through the financial support of Simon Fraser University's VanCity Office of Community Engagement. This support for this project does not necessarily imply endorsement of the findings or content of this report. TSS funders neither influence nor endorse the particular content of TSS reporting. Other publications wishing to publish this story or other TSS produced articles, please see this website for contacts and information.

What element would you propose this kind of "explainer" or "funding" text should go into? I suspect staff here will say that this kind of text should not be lost on small screens... I can check on that if problematic.

(Reopening for now.)

**Comment by alexgreen** [comment]
using a fact-box is probably the best. I'll set that up.

**Comment by alexgreen** [comment]
I've added a fact-box explainers to the Series story and slideshow story:
be73d766c5064c7643853570994d472a6e37f552
758fe579a54df76331f0caaf8a53e433fc480605
707b9d03460fbe4867823f89675bc7949b9a5b8b
