### ISSUE TITLE
Create article variation for photo essay story

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#134]

**Comment by phillipadsmith** [comment]
FYI, @alexgreen, talked to Robyn about this today and -- even though "photo essays" in the traditional sense will be rare (more so given the new media sizes in stories) -- it still make sense to have a basic carousel available to stories in the scenario like this one where there are 20+ photos: http://preview.thetyee.ca/News/2014/12/05/Affordable-Homeownership-Experiments/index.html

I'll hold off setting up this story pending your thoughts on how to move forward, i.e., do you want to take the lead on setting up the various includes and HTML structure and then I can move over the text and media for this example?

**Comment by phillipadsmith** [comment]
cc @MrBryan

**Comment by alexgreen** [comment]
> do you want to take the lead on setting up the various includes and HTML structure and then I can move over the text and media for this example?

yes, that sounds good.

**Comment by alexgreen** [comment]
@phillipadsmith is this lower priority than the Presents example story?

**Comment by phillipadsmith** [comment]
> @phillipadsmith is this lower priority than the Presents example story?

Yes.

**Comment by phillipadsmith** [comment]
I've set-up a basic photo essay example here:
http://thetyee.github.io/design-article.thetyee.ca/slideshow.html

Based on this story:
http://thetyee.ca/News/2015/02/23/Four-Sisters-Coop-Profile/

I've only used the carousel for now, as it has been done in the past.
