### ISSUE TITLE
Nav dropdown shouldn't cover up content

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#137]
In the original design the nav dropdown pushes the story content down on the page, rather than covering up the story content as it currently does. It would be good to implement this as originally intended.

Our goal has been to encourage readers to navigate the website directly from the article page, so it doesn't make sense for the nav to hide content and put extra clicks in their way. ... Ideally I would like to make the Latest Stories dropdown more compact and possibly have it showing by default (as the NYT does), but that part will have to wait. 

Bryan, I'm tagging you on this since you've taken on the related nav bar issue #128

**Comment by MrBryan** [comment]
ah sorry i didn't read this before i committed the other change

**Comment by MrBryan** [comment]
needs either a fair bit of restructuring where nav elements  like this are nested or 'faking' its spot in the element order with javascript pushing down by its height the article elements. 

Probably the latter is the better route but I personally wouldn't expect this behaviour when clicking on drop downs from my experience (why would i open the menu then scroll past it?)  and I think the other stories widget as it is is too large height wise to pull off what the NY times is doing by having it open by default - theirs is very short.  Should we maybe push this to until we look at how that would work?

**Comment by MrBryan** [comment]
with that said I'm not picky just playing devil's advocate I can do it if given the above you want to go through with it now

**Comment by alexgreen** [comment]
> I think the other stories widget as it is is too large height wise to pull off what the NY times

...ergo, "I would like to make the Latest Stories dropdown more compact and possibly have it showing by default (as the NYT does), but that part will have to wait."

> I personally wouldn't expect this behaviour when clicking on drop downs from my experience

I find this is very common in mobile views these days. In fact even our website already does this in views narrower than 991px. (Try it and see.) I'm just saying we should make the behaviour consistent in wider views as well.

> needs either a fair bit of restructuring

I don't think so: we're already doing in narrow views. Should be easily doable with CSS. Or are you saying that the trouble is due to the side-scrolling of recent story items? Seems like that shouldn't have any bearing on the vertical height of the element.

> why would i open the menu then scroll past it?

Why would you hide something that doesn't need to be hidden? Why not give people the option of scrolling rather than forcing them to close the menu? Is there a reason that the nav should cover up the content? If so, then why isn't it covering up the content in narrow views?

**Comment by MrBryan** [comment]
fair enough - just did the JS route which was simple enough.  It seems less unusual to me to push things down in mobile / narrow views than on a desktop but as I said I'm not picky

f94facf

**Comment by alexgreen** [comment]
Thanks!

Currently only the Latest Stories dropdown is exhibiting this behaviour, while the other dropdowns are still covering up content. I think the behaviour should be consistent for all dropdown menus.

**Comment by alexgreen** [comment]
I noticed that in Chrome OSX at medium and small views the content sometimes gets pushed down twice as far as it should. Maybe a conflict between css styling and js? This doesn't happen always and it doesn't seem to occur on my IOS and android devices. (I suspect it may only be an issue when the browser window gets resized, but not sure.) Can you have a quick look and try to replicate?

![at four sisters co op an affordable housing dream realized the tyee](https://cloud.githubusercontent.com/assets/151099/15285651/89fbbeca-1b93-11e6-97ed-f31de65d6e9b.png)

![at four sisters co op an affordable housing dream realized the tyee 2](https://cloud.githubusercontent.com/assets/151099/15285654/8d1b426a-1b93-11e6-81c8-8f9fc7249b37.png)

**Comment by phillipadsmith** [comment]
> I noticed that in Chrome OSX at medium and small views the content sometimes gets pushed down twice as far as it should. Maybe a conflict between css styling and js? This doesn't happen always and it doesn't seem to occur on my IOS and android devices. (I suspect it may only be an issue when the browser window gets resized, but not sure.) Can you have a quick look and try to replicate?

I've not seen this when re-sizing? How are you currently producing that problem?

**Comment by MrBryan** [comment]
I can't seem to reproduce that issue either. But I did broaden the js targetting on the push-down effect to all drop-downs 7438d0a

**Comment by MrBryan** [comment]
a-ha yes I can - if i expand the latest stories in full size, then resize to small and expand latest stories there.

Fixed that by testing what width we are in at click time .. a98f744

**Comment by alexgreen** [comment]
The nav dropdown is covering up the content again. In chrome on desktop and also on ipad.

**Comment by MrBryan** [comment]
not for me are you sure you have all pulls?

**Comment by alexgreen** [comment]
Yeah I pulled develop just a few minutes ago

**Comment by alexgreen** [comment]
I had to make a bunch of changes to Sally's nav dropdown code to fix issues of Latest Stories text sizing and colour, so I hope I didn't remove something your javascript was hooked to!

**Comment by MrBryan** [comment]
did you commit them? i have latest pulled to and i'm still getting the correct push-down behaviour and can browse the menus & scroll on ipad too

**Comment by alexgreen** [comment]
yeah. committed and pushed to develop.
I'd investigate further, but I really have to call it a night now. The sun's coming up.

**Comment by MrBryan** [comment]
hmm i just pulled again you're right i was missing your changes and it's broken now

**Comment by MrBryan** [comment]
wait.. it's working actually. Possibly just needed a hard refresh command+shift+r

**Comment by alexgreen** [comment]
Yeah, today it's working for me too. Not sure what the issue was, but there's definitely something buggy going on because the menus still disappear when I scroll on mobile which is a big problem.
