### ISSUE TITLE
Extend top navigation borders to viewport edges

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#138]
Howdy @kidcompassion,

Per our conversation today, I'm assigning you this issue to explore expanding the navigation borders to the viewport edges. 

The content can stay width-limited as it is now.

Please update this issue once you've had time to take a look.

**Comment by alexgreen** [comment]
How are we doing on this?

**Comment by phillipadsmith** [comment]
Re-assigning to @MrBryan

**Comment by MrBryan** [comment]
0b90ac9  All done

**Comment by alexgreen** [comment]
Some new problems have appeared:
- Too much vertical space between nav and bottom border
- border and logo baseline should be aligned (no longer are)
- Space above top border is too great
- Ghosted secondary border appears

![wrong-nac-spacing](https://cloud.githubusercontent.com/assets/151099/15984318/5a94fc96-3001-11e6-8f6a-6db8053c38e0.png)

![correct-nav-spacing-alignment](https://cloud.githubusercontent.com/assets/151099/15984320/60cf1b3c-3001-11e6-980e-55de9963ce27.png)

**Comment by MrBryan** [comment]
We will have to settle for less than perfect to achieve this border that is actually outside of it's container but this is pretty close 

8e0c91f664c27e0c24a80d1f1a880382a709498c
71f9799

**Comment by MrBryan** [comment]
Unless I did all kinds of javascript or restructure the whole nav which I don't think is worthwhile for this minor difference

**Comment by alexgreen** [comment]
This nav layout should be pretty simple and shouldn't require any javascript, but I haven't gone into Sally's code so I don't know what's happening in there.

I see that you've got it working very well now (without all kinds of javascript?)! Thanks! The only issue is gaps between the border and the edge of the window (tiny 5px gap on left side, larger expanding gap on right side). I'll take a quick look and see if it's easily fixable.

![screen shot 2016-06-15 at 8 02 37 pm](https://cloud.githubusercontent.com/assets/151099/16077672/3e4d4a20-3335-11e6-8654-140419659b2e.png)

**Comment by alexgreen** [comment]
Oh, I see the problem. 
`@media (min-width: 992px)
.menu_center-nav-wrap {
    ...
    max-width: 300px;
}`
Is causing the the nav to become uncentered, creating a progressively increasing gap on the right side

**Comment by alexgreen** [comment]
I fixed this issue by adding 
`.menu_left-nav-wrap, .menu_right-nav-wrap {
      width: 37.5%; /* Fallback for older browsers */
      width: calc(50% - 150px);
    }`
to the 1200px breakpoint. 37ab94a17cda86f897701d0aae33d009b98118f2
Calc is pretty widely supported (http://caniuse.com/#feat=calc) but it would be nice to have a better fallback.

This nav css looks like its much more complicated than it needs to be so I'm worried that there may be browser/device testing issues, but I guess we'll see.
