### ISSUE TITLE
Style for "Editors note"

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#139]
This commonly happens (much to my cries for it to end):
<img width="581" alt="on_nature_s_death_row__it_used_to_be_bc_s__eden____the_tyee" src="https://cloud.githubusercontent.com/assets/34128/14904446/0c65ea6a-0d5d-11e6-9986-4197f80ed6e2.png">

There is an element in Bricolage they can use to add this. I'll hammer that home again. It needs to be styled in some sensible way.

**Comment by alexgreen** [comment]
Duly noted:
https://www.google.com/search?num=40&safe=off&espv=2&q=%22editor%27s+note%22+site%3Athetyee.ca&oq=%22editor%27s+note%22+site%3Athetyee.ca&gs_l=serp.3...11701.11869.0.12378.3.3.0.0.0.0.168.168.0j1.1.0....0...1c.1.64.serp..2.0.0.WgfCnXv563k

**Comment by alexgreen** [comment]
0e013959b8df25108f8ddbe738d9ebfd232437bc creates and styles the editor's note. You can see it on the library page.

I left out the phrase "Editor's note:" because the page looks nicer without it and I think it's pretty self-evident. But lmk if it needs to be included.

![screen shot 2016-05-19 at 2 43 08 am](https://cloud.githubusercontent.com/assets/151099/15368989/84cd130c-1d6b-11e6-9cfa-bb78f48384d6.png)

**Comment by alexgreen** [comment]
@phillipadsmith do you want to be the main point of contact with editorial, or should ask them about this directly?

**Comment by phillipadsmith** [comment]
> @phillipadsmith do you want to be the main point of contact with editorial, or should ask them about this directly?

Feel free to ask them directly this week because I'm mostly offline for another project.

> I left out the phrase "Editor's note:" because the page looks nicer without it and I think it's pretty self-evident. But lmk if it needs to be included.

The challenge will be that it's literally included in the text that they type into the top of a story, unfortunately, so even if you leave it out it will likely appear again. 

I'd say ask Robyn about this, yes, but let's also move forward and consider this "done" for now because it meets the requirement as its met on the existing site.

cc @MrBryan

**Comment by MrBryan** [comment]
Hmm yes that is a challenge. There is an actual "editor's note" element that is designed to separate the content and it adds the "editor's note" text but as you point out they haven't been using it but manually inserting into the body complete with `<em>` tags

If we tell them to start using the element I can apply the style to the element template.

It also creates a problem for the 'lead-in' style that gets applied to first paragraphs with the giant first letter -- the editors note gets a giant left bracket [ so i'm having to detect that and not apply the lead-in in those stories

Maybe would make sense for content entering posse to go back and move them all to that element.  

Could also create a script but that could be ugly.

**Comment by alexgreen** [comment]
> It also creates a problem for the 'lead-in' style that gets applied to first paragraphs with the giant first letter -- the editors note gets a giant left bracket [ so i'm having to detect that and not apply the lead-in in those stories

Yeah, @MrBryan the drop cap should get applied to the first paragraph after the editor's note. Here's a way we could solve it using just html and css:

Put the editor's note in a [div] rather than a [p]. Then I can use css to target the first [p] instance within the article__body and give it the drop cap. That will work regardless of whether there's an Ed note or not. —and we won't even need to use the .lead-in class anymore! (assuming that every story will always start with a drop cap.)

Should I implement this in Jekyll?

**Comment by MrBryan** [comment]
Well that solves it for the ideal situation when they use the editor's note element itself which i can markup, but that has been rare -- usually when it is in the body it will be a `<p><em></em></p>` so it will still get stuck in that css rule.  I can't think of any smart way to catch that in only css. It would be easy enough to remove the lead-in treatment if it is in an`<em>`but not to apply it to the next paragraph when that happens

**Comment by MrBryan** [comment]
Maybe that's good enough though, to just not have the giant leading letter when there is an editor's note for now

**Comment by MrBryan** [comment]
And then apply the editor's note css to p:first em

**Comment by MrBryan** [comment]
although.. then if they just used italics in the paragraph anywhere it would do that.  Pardon my using the comment box to think.  I think I will just have to parse the paragraphs and watch for `<em>[` in which case it will restart the paragraph count and apply the editor's note css to that part

**Comment by MrBryan** [comment]
annnd. it's working now for the record with that kind of parsing.

**Comment by alexgreen** [comment]
I could write css rule to target the first `<em>` of the first `<p>` in the article body. But really the dropcap is an important visual marker which marks the start of the article content and separates it from the preceding editor's note, so omitting it isn't good. 

Can this omission of dropcap after editor's note be limited to "legacy" articles? E.g. if you can add a body class of .article--legacy to all ye olden articles then we can write css to treat them differently without compromising the new articles.

**Comment by MrBryan** [comment]
whatever this is 
![image](https://cloud.githubusercontent.com/assets/1721891/15973060/5b676f02-2ef6-11e6-968e-c3cc7721eaee.png)

**Comment by alexgreen** [comment]
I think we're in the wrong thread, but that's a cute kitty. :)  
It's also and `<img>` inside a figure.figure. When a `<figure class="figure "><img></figure>` is put inside `<section class="featured-media"></>` then it should expand to fill the container  (i.e. this is the behaviour I styled in the css), resulting in the enormous headshot you mentioned. And that in turn should be tall enough to support a half-page ad next to it. So all good, if I'm understanding you correctly.

**Comment by MrBryan** [comment]
haha yes i pasted on the wrong one i'll answer in the right one

**Comment by MrBryan** [comment]
I'm never omitting the dropcap altogether just delaying it after the editor's note. But I did add a rule to remove it when the paragraph is too short like on here

http://preview.thetyee.ca/Testing/2016/01/22/East-Van-Wants-More-testing/index-closeup.html

**Comment by alexgreen** [comment]
> I'm never omitting the dropcap altogether just delaying it after the editor's note. But I did add a rule to remove it when the paragraph is too short

Sounds good. How did you define "too short"?

Can I see some more examples of articles with an Ed Note where the dropcap shows up and doesn't?
