### ISSUE TITLE
GIT-tard help ->

### ISSUE THREAD

**Issue by MrBryan** [TheTyee/design-article.thetyee.ca#146]
Hey guys -- need some help getting started with this:

Why are article_custom.js and other js files in the ui/js directory when i look at my branch (BC) on here but when i have my branch checked out only article.js and jquery.slides.js are there? I'm trying to edit article_custom.js

![image](https://cloud.githubusercontent.com/assets/1721891/15003314/a10b2ca6-1178-11e6-8c63-857a4b77a21d.png)

js mrbryan$ ls
article.js      jquery.slides.min.js

**Comment by MrBryan** [comment]
nevermind, sorry had to clone / fetch with the branch specified /duh

**Comment by phillipadsmith** [comment]
💯
