### ISSUE TITLE
Add explainer text object to Series stories and slideshow stories

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#152]
See #130 

**Use fact-box for this?**

there is often a blurb at the bottom, under the old bio, that says something like:

> This series was produced by Tyee Solutions Society. It was made possible through the financial support of Simon Fraser University's VanCity Office of Community Engagement. This support for this project does not necessarily imply endorsement of the findings or content of this report. TSS funders neither influence nor endorse the particular content of TSS reporting. Other publications wishing to publish this story or other TSS produced articles, please see this website for contacts and information.

What element would you propose this kind of "explainer" or "funding" text should go into? I suspect staff here will say that this kind of text should not be lost on small screens.

**Comment by alexgreen** [comment]
I've added a fact-box explainers to the Series story and slideshow story:
be73d766c5064c7643853570994d472a6e37f552
758fe579a54df76331f0caaf8a53e433fc480605
707b9d03460fbe4867823f89675bc7949b9a5b8b

**Comment by phillipadsmith** [comment]
> What element would you propose this kind of "explainer" or "funding" text should go into? I suspect staff here will say that this kind of text should not be lost on small screens.

Correct.
