### ISSUE TITLE
Create numbering system for slides

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#157]
I removed the typical slideshow dot-nav-thing because it seems messy (especially considering that some Tyee slideshows have a couple dozen images), but it would be good to give readers some indication of how many slides there are and their position in the sequence.

This could be done manually by adding slide numbering at the beginning of every slide caption (e.g. "1/12. ") as I've done in dev ( 005695efcb3129679bada1a924230236f20fceed ). Intuitively I'd say this isn't a great idea because it relies on staff to remember to do this consistently and in a consistent format.

The other option would be to number the slides with js or server-side. I think that's probably the way to go, and it will allow more design control over the styling of the numbers too.

@phillipadsmith, what say you?

**Comment by phillipadsmith** [comment]
> This could be done manually by adding slide numbering at the beginning of every slide caption (e.g. "1/12. ") as I've done in dev ( 005695e ). Intuitively I'd say this isn't a great idea because it relies on staff to remember to do this consistently and in a consistent format.

Agreed, this is not a good approach because it would require re-numbering if there was a last-minute addition of another image.

> The other option would be to number the slides with js or server-side. I think that's probably the way to go, and it will allow more design control over the styling of the numbers too.

Yes, easy enough to do, but also not blocking anything, so let's mark this as an issue to return to after the other work is done.

**Comment by MrBryan** [comment]
I did this server side didn't notice this thread but I took from the example that it goes in the caption so worked something out.

For the bric-curious and future reference it looks like this in gallery_output.mc

```
% my $relcount = 1;
% for my $rel (@relateds) {
%     $m->comp('.slide', rel => $rel, num => $relcount, total => (scalar @relateds) );
% $relcount++;
% }

<%def .slide>\
<%args>
$rel
$num => 1
$total
</%args>
% my $image = $rel->get_related_media;
% my $height = $image->get_value('height');
<div class="item <% $num == 1 ? "active" : "" %>">
      <img src="<% $image->get_uri %>" alt="<% encode_entities $rel->get_value('image_title') || $image->get_title %>">
      <div class="carousel-caption caption"><strong><% $rel->get_value('image_title') %></strong>
% if ( my $caption = $rel->get_value('caption') || $image->get_description ) {
                                <p><% $num %>/<% $total %> <% $caption %></p>
% }
      </div>
    </div>
</%def>\


```

**Comment by alexgreen** [comment]
Can you provide a link so we can see this? thx
