### ISSUE TITLE
Need treatment / suggestion for smaller featured images (in legacy stories )

### ISSUE THREAD

**Issue by MrBryan** [TheTyee/design-article.thetyee.ca#159]
I have been testing the templates in various old stories and for the featured image, as far as I can tell the existing options for medium sized images (especially headshots) are to make it a giant EXTREME CLOSEUP as below or an aside.  I think something in between is needed - I can detect image size and apply something. Any ideas? Apologies if I missed something in the conversation about this before

![image](https://cloud.githubusercontent.com/assets/1721891/15908099/c960c586-2d74-11e6-8fb2-ed19fdce90fc.png)

![image](https://cloud.githubusercontent.com/assets/1721891/15908281/bcd7cff2-2d75-11e6-8fba-3d2006aff50f.png)

**Comment by MrBryan** [comment]
cc @alexgreen not sure if you get notified if I don't do this..

**Comment by MrBryan** [comment]
Using the medium treatment from here for now for medium "featured images" http://thetyee.github.io/design-article.thetyee.ca/library and the aside small for smaller by detecting the featured image width & choosing that way

issue is mostly that this is being mass republished for old stories where we can't manually select better images or choose the treatment

**Comment by alexgreen** [comment]
@MrBryan The featured image should appear as designed, otherwise it will cause big problems with the placement of half-page ads. It will have to be a giant extreme closeup. (Every article needs to have a properly formatted image in section.featured-media otherwise the layout will break.)

**Comment by alexgreen** [comment]
(although I'm not totally sure what you mean by "the medium treatment" because we don't have anything with that name.) by default images fill their container (figure or aside) and there is no medium container size. there is .figure--xl and .figure--xxl but these won't work properly within section.featured-media.

**Comment by MrBryan** [comment]
> It's also and <img> inside a figure.figure. When a <figure class="figure "><img></figure> is put inside <section class="featured-media"></> then it should expand to fill the container (i.e. this is the behaviour I styled in the css), resulting in the enormous headshot you mentioned. And that in turn should be tall enough to support a half-page ad next to it. So all good, if I'm understanding you correctly.

Yes the way I coded it was it will put the medium image in the regular flow below rather than in the featured image area  if it is below a width threshold

That works but creates some other spacing issues at the moment  which I have yet to resolve if it's a result of code recombinating incorrectly

**Comment by alexgreen** [comment]
So where does the halfpage ad go if there's no featured-image section?

I think it's easier and more consistent to just stick with the design intent and have a big featured image. No need to create more work atm.

**Comment by MrBryan** [comment]
It just looks really wonky with a good percentage of the old stories, sometimes the images were around 250 px and are someone's face

**Comment by alexgreen** [comment]
Aha. low-res images. Can we see some examples? It's hard to speculate about invisibles.

**Comment by alexgreen** [comment]
Is there some way we can access the results of the testing you're doing?

**Comment by alexgreen** [comment]
Where does the halfpage ad go if there's no featured-image section? It would need to get move to a new position. It won't fit in an aside, so it would have to go in the main text column, creating a really big vertical break in the story. Seems like there's a bunch of stuff to work out here

**Comment by alexgreen** [comment]
But Michelle needs to have the half-page ad at the top, not within the text column so that's a non-starter anyway ...

**Comment by MrBryan** [comment]
where is the half-page ad example on the github sample pages?

**Comment by MrBryan** [comment]
here's that super close up sample in context - i will probably preview it another way later so will only work for now:  http://preview.thetyee.ca/Testing/2016/01/22/East-Van-Wants-More-testing/index.html

**Comment by MrBryan** [comment]
don't worry about nitpicking other aspects of the page just yet

**Comment by MrBryan** [comment]
I think i'm realizing part of the problem is the absence of the half page ad that used to take of some of the width, thinking back to what I had seen but can't find at the moment on any example pages

**Comment by MrBryan** [comment]
I moved a copy to http://preview.thetyee.ca/Testing/2016/01/22/East-Van-Wants-More-testing/index-closeup.html so that it won't get overriden when I test other things so follow that link instead

**Comment by alexgreen** [comment]
> where is the half-page ad example on the github sample pages?

It's literally on every page. But the breakpoint is currently at 1400px wide, so maybe you don't have your window big enough. See attached.
1400px is quite a wide breakpoint, but there's some specific reasons why we arrived at this. It would be great to set the breakpoint lower. We could make it a bit narrower by centring the block, but that would only gain us about 80px and the consensus agreed that it wasn't worth sacrificing the layout alignments for such a small gain.
The requirement that we position the half-page ad at the top of the article is a big constraint that determines a lot of the design decisions in this project.

It really doesn't make any sense to speculate about potential design changes without taking all the objects and breakpoints into account. If you want to move this project to launch quickly then it's better not to make design changes now.

![screen shot 2016-06-11 at 5 24 11 pm](https://cloud.githubusercontent.com/assets/151099/15984127/950d0870-2ffa-11e6-8953-d87d3dea6f39.png)

**Comment by alexgreen** [comment]
> I moved a copy to http://preview.thetyee.ca/Testing/2016/01/22/East-Van-Wants-More-testing/index-closeup.html so that it won't get overriden when I test other things so follow that link instead

Is there some way you can add this to our github repo or is it that not feasible due to dynamic content?

I don't know what you've done to this page, but you've omitted the half-page ad. Please let's just stick with  the current design that has been approved, otherwise this will never end.

Having a large headshot in some legacy article is ok. 
I'll try setting a max-height so that it doesn't blow up quite so huge, but this may cause other problems so please let me test it first.

**Comment by alexgreen** [comment]
@MrBryan btw thanks for doing this testing with live content! This is very useful for seeing how the design responds to a variety of content. It would be great to see more sample pages.

**Comment by alexgreen** [comment]
As I mentioned in #160, lets leave this for now. I think scaling up low-res images is better than leaving them too small even though the image quality suffers.

**Comment by alexgreen** [comment]
I'm seeing a new media query added:

`/* more attempts at cross browser / os alignment issues w/ small image in play  BC */
 @media screen and (min-width: 700px) and (max-width: 880px) {
  .main-col-container {
     margin-left: auto;
          margin-right: auto;
    left: -7%; 
   left: calc( -1 * ( ((100vw - 33em) / 2) - (3em) ) );
   /* left:-webkit-calc( -1 * ( ((100vw - 33em) / 2) - (2em) ));*/
   */
 }
 }`

This will not be be good for articles that have normal size featured images.
When we talked we agreed that this issue could be dealt with by simply resizing the small legacy image to fill the column within a very narrow range of breakpoints, and thus leave the .main-col-container unaffected. Is that not possible?

**Comment by MrBryan** [comment]
doesn't affect the other images negatively in any of my testing. I tried the full width earlier option and it won't work because the ad is still virtually floating in the same row so pushes everything down funny. Going to go with this for launch unless anything big jumps out in further testing

**Comment by MrBryan** [comment]
This is implemented, currently the code to enable ads to show < 1200px is disabled. For post launch
