### ISSUE TITLE
Change “Join” in top navigation bar to Heart/Dollar sign emoticon and word “Join”

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#16]

**Comment by phillipadsmith** [comment]
Per this comment in Basecamp:

> ​On the story page, below the author bio where all the share icons are, please move the dollar-heart sign to the outside right of all the icons and add the word “JOIN" (just as you have it in the top nav). We just want to make it as obvious as possible how to give us money...
> 
> There's no dollar-heart icon on the small mobile (or narrow) view. Could we add it along with the word "JOIN"

So:
- [ ] Needs to be moved to the right of the social icons
- [ ] <3 needs to be added to the header navigation, I believe?

**Comment by alexgreen** [comment]
>  <3 needs to be added to the header navigation, I believe?
> Moving this to a Sally task
