### ISSUE TITLE
Set max-height for featured-image to prevent huge blowup of legacy article images

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#160]
See problem:
http://preview.thetyee.ca/Testing/2016/01/22/East-Van-Wants-More-testing/index-closeup.html

see also: Need treatment / suggestion for smaller featured images (in legacy stories ) #159

**Comment by MrBryan** [comment]
it's not just the max-height so much as the scale factor. We would have to set the max-height to something small enough that it would break the pictures that actually work i.e. higher res + better aspect ratio.  So when you consider this take into account that I can detect the image dimensions in conditional logic before applying some class or choosing between treatments / whatever

**Comment by alexgreen** [comment]
Lets leave this for now. I think scaling up low-res images is better than leaving them too small even though the image quality suffers.

**Comment by MrBryan** [comment]
Hmm, I don't that's flying well here with the previews I've shown them.  What about an option where it will float next to the headline & deck like this:

![image](https://cloud.githubusercontent.com/assets/1721891/16093017/0156b926-32ef-11e6-899f-f0ca87dcf0b6.png)

**Comment by MrBryan** [comment]
notwithstanding margins etc just plopped elements into a mockup

**Comment by MrBryan** [comment]
That example of the giant head zoomed in is a little to silly and unfortunately not uncommon for stories to have a little headshot as the featured image in the past

**Comment by alexgreen** [comment]
No. The halfpage ad is too wide to fit in the side-column. Lets stick with the design that's been approved.

**Comment by alexgreen** [comment]
I think people are used to seeing giant heads these days. It's not ideal, but this issue only affects old stories, correct? —so it's a low-priority design enhancement that should be addressed later.

**Comment by MrBryan** [comment]
I'll take it up with them today. There is a significant amount of traffic to those stories from search / related etc so may not work. just hopping on call hopefully we can chat more in an hour or so

**Comment by alexgreen** [comment]
It's 4am here. So if you want to get into design changes that will have to wait for another day. I'm happy to book chat time during the windows I mentioned to you.

**Comment by MrBryan** [comment]
ok i'll just note here what the decision is today when we look at it as to whether something has to happen before launch
