### ISSUE TITLE
Dropdown nav sometime breaks upon device rotation

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#161]
Rotating the device (ipad mini in this case) creates gap when dropdown is/was active.

![a9b3ef84-6962-472f-bd1e-f72049e557c2](https://cloud.githubusercontent.com/assets/151099/15984355/e2054540-3002-11e6-8971-c0badbc0cb7c.PNG)

**Comment by MrBryan** [comment]
Tried to fix with b3a7835. Works for resize events, might work for orientation change.  I tried to test but the site doesn't work at all on IOS simulator of iPad 2 and iPad retina.. hopefully it's better on real devices

**Comment by alexgreen** [comment]
I've been testing on my iPad3 mini every time I make a change and it's always worked perfectly (other this dropdown issue).

**Comment by MrBryan** [comment]
fixed as above
