### ISSUE TITLE
half-page has to show on ~ipad and larger screens

### ISSUE THREAD

**Issue by MrBryan** [TheTyee/design-article.thetyee.ca#163]
Right now the half-page ad disappears under 1400px -- this is too small as loads of laptops, older ios(ipad) and other screens around 1200px-1300 will miss it

![image](https://cloud.githubusercontent.com/assets/1721891/16023597/517d896c-3172-11e6-9cdc-4463aeb0dd7a.png)

**Comment by MrBryan** [comment]
a fair bit of rejigging various widths etc has to happen, just setting the threshold from 1400 to 1200 doesn't work

**Comment by MrBryan** [comment]
this seems to work well actually.

2ba1ed7

**Comment by MrBryan** [comment]
236d89a added back 1400px treatment as it was (originally i just changed 1400 to 1200 now both breakpoints are there for more optimized image size)

**Comment by alexgreen** [comment]
This looks like a reasonable solution. It works surprisingly well because the bottom of the 2-line caption happens to roughly line up with the bottom of the ad and thus no weird gap is created above the story text. There's a couple wonky spacing things that I'll try to fix up.

**Comment by alexgreen** [comment]
Alignment corrected
d9d7f5c995819238322647f2dc9db17b7db879ae

**Comment by alexgreen** [comment]
I've adjusted the height of the image to match the height of the ad and used `object-fit: cover` to clip excess image width. There's a fallback for IE10+
b0a32e8dd911c0790e2910d5205048d0cafb8484
