### ISSUE TITLE
Nav dropdowns disappear upon scrolling on mobile

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#167]
Tested on nexus android and ipad3 chrome

**Comment by alexgreen** [comment]
This makes it impossible to browse the latest stories menu on narrow mobiles

**Comment by alexgreen** [comment]
They also disappear on desktop upon window resizing. Not so critical, but probably a related symptom of the same cause.

**Comment by MrBryan** [comment]
that one i did on purpose(resize) so that if you moved between breakpoints with menus open you wouldn't be left with a funny margin on the content (which is pushed down when menus open)

I could make the script more clever to detect if you pass between breakpoints but maybe overkill

**Comment by MrBryan** [comment]
i'll check the scroll thing i'm not sure what the cause is but shoulkdnt' be the same because the trigger is a resize event

**Comment by MrBryan** [comment]
fixed 
        24d00bc and 
        346eca1
