### ISSUE TITLE
Search panel position is not right

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#170]
Might be a duplicate, but wanted to flag:
<img width="1433" alt="dix_asks_auditor_general_to_examine__misleading__hydro_accounting___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/16162086/6daecaee-34d1-11e6-9430-f679a4d22a5d.png">

cc @alexgreen @MrBryan

**Comment by MrBryan** [comment]
fixed 43ecf15
