### ISSUE TITLE
"Latest stories" links are not active at bottom of article

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#175]
E.g., if you try to click a link to a "Latest story" under the article, the link is not active.

**Comment by phillipadsmith** [comment]
This is fixed, yes?

**Comment by phillipadsmith** [comment]
This is not fixed for me!

**Comment by phillipadsmith** [comment]
All linking to the same story.

**Comment by MrBryan** [comment]
woops, nice catch.

For realsies this time : 8713690
