### ISSUE TITLE
Footer on preview doesn't match footer on GitHub

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#176]
<img width="773" alt="health_firing_inquiry__adversarial__intimidating____the_tyee_and__pennies_for_billions___aboriginals_fight_near_giveaway_of_pipeline_rights_in_1952___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/16273623/49d6087e-3870-11e6-9f26-6aa5a75a3943.png">

**Comment by MrBryan** [comment]
Fixed on bric, not in git because it's a template just missing a closing div
