### ISSUE TITLE
List JS files to be removed from production site

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#179]
> Remove unused .js files, like article.js, article_subscription_popup.js, backbone.js, etc. [Phillip will review and make a list to remove]

**Comment by phillipadsmith** [comment]
I've removed them in this fork (now merged with `develop` and `gh-pages`:
https://github.com/TheTyee/design-article.thetyee.ca/tree/feature/performance-one

**Comment by MrBryan** [comment]
i'm running the branch bc-bricmod on the server where I have moved as many of the files as I can to load from the repo  just fyi haven't landed on the best approach to the workflow yet

**Comment by phillipadsmith** [comment]
> i'm running the branch bc-bricmod on the server where I have moved as many of the files as I can to load from the repo just fyi haven't landed on the best approach to the workflow yet

Cool. Just flagging which .js files can be removed / have their references removed. No point loading them if the page doesn't require them.

**Comment by MrBryan** [comment]
is it just the ones you listed or is there a commit where i can see what has to be changed? I think i'll try to find a way to move the css/javascript calls in head back into github & include from there

**Comment by MrBryan** [comment]
oh sorry re-read i see that you are going to list

**Comment by phillipadsmith** [comment]
> oh sorry re-read i see that you are going to list

The changes are in the fork linked above:
https://github.com/TheTyee/design-article.thetyee.ca/tree/feature/performance-one

If you want, I can also list them here.

**Comment by phillipadsmith** [comment]
Basically:

Remove:
- backbone.js
- backbone.stickit.js
- underscore.js
- less.js

And switch to use bootstrap.min.css vs. the .less file (which also requires an update to the attribute of that tag).
