### ISSUE TITLE
Specify image dimensions in the Latest Stories blocks

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#185]
Not sure if this is possible @alexgreen @MrBryan because it looks like the image size varies depending on the viewport size?

**Comment by MrBryan** [comment]
da2f181  done

**Comment by MrBryan** [comment]
and yes the image stretches to viewport scale but it does have an initial size that will be known before loading now so I think that still has a tiny performance advantage

**Comment by phillipadsmith** [comment]
👍
