### ISSUE TITLE
Poll block is wonky in smaller viewport sizes

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#186]
<img width="380" alt="citizens_tell_the_premier__ban_big_bucks__pooh-pooh_party_pay___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/16280090/f44eeba2-388b-11e6-83e0-ef131ed136a2.png">

**Comment by MrBryan** [comment]
what version combo were you able to reproduce this under? I tried my VM windows 8 latest firefox and browserstack latest firefox also

**Comment by MrBryan** [comment]
This should fix it in any case 34198ad

**Comment by MrBryan** [comment]
er this i mean  b0f68b9  af0a269c86fb201362b644afa77d910abb6ed820
