### ISSUE TITLE
Inconsistencies with the periods in the post-article stuff

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#190]

**Comment by MrBryan** [comment]
not sure i get this one

**Comment by phillipadsmith** [comment]
<img width="676" alt="citizens_tell_the_premier__ban_big_bucks__end_party_pay___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/16404124/decaada6-3cb0-11e6-9c13-764f31a79eac.png">

**Comment by alexgreen** [comment]
Those lines have different functions. 2 headings, 1 declarative sentence, 1 CTA. The 2 headings do also function as CTAs but in general I omit periods in headings and include periods in declaratives. That's why the difference.

But when in doubt removing periods is better than adding new ones.

**Comment by alexgreen** [comment]
So @phillipadsmith , if I make a change to messaging-block--ask.html on github, would that now be reflected in preview or in development? What I mean is, should I bother making any changes?

**Comment by phillipadsmith** [comment]
During one of the feedback sessions with Robyn, she asked for them to be consistent. I can't recall which direction she wanted to go -- more or less periods -- but we need to follow the direction of editorial here. Do you have the notes on that round of feedback by any chance, @alexgreen? If not, I'll ask Robyn.

**Comment by phillipadsmith** [comment]
> So @phillipadsmith , if I make a change to messaging-block--ask.html on github, would that now be reflected in preview or in development? What I mean is, should I bother making any changes?

Yes, if you can create a feature branch with the name of the bug/fix/feature/issue number, make changes there, publish it, and then merge into develop -- that is the best approach, because it provides the changes specific to the fix in a branch were it's easy to see what changed.

Let me know if you have any questions on that.

Phillip.

**Comment by MrBryan** [comment]
If you want to try making the change in develop i'll see if it merges correctly with my bc-bricmod branch --  i've had problems with conflicts. or if you make the change directly on bc-bricmod it will show up.  A lot of the includes are being included right into bricolage with some changes

**Comment by MrBryan** [comment]
didn't see Phillip's response above when i answered

**Comment by alexgreen** [comment]
> Do you have the notes on that round of feedback by any chance, @alexgreen? If not, I'll ask Robyn.

I don't, but I'm happy with whatever editorial prefers.

**Comment by robynleighsmith** [comment]
Sorry, had to create a github account. I say drop all the periods for consistency sake, please.

**Comment by MrBryan** [comment]
`Sorry, had to create a github account.`

see, you're a geek, too, now, soon you'll be complaining about sore eyes

**Comment by MrBryan** [comment]
335b9c8 fixed in bricmod -- avoiding merging issues for now

**Comment by alexgreen** [comment]
fixed in repo via 7fdd6fc
