### ISSUE TITLE
Spacing between share and first paragraph when feature image is small

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#193]
<img width="711" alt="citizens_tell_the_premier__ban_big_bucks__end_party_pay___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/16399349/70743a04-3c86-11e6-871e-e78d08cc6d1a.png">

**Comment by MrBryan** [comment]
Added 20px margin top when medium treatment is present (adds class "margintop")
d55e361

**Comment by MrBryan** [comment]
http://preview.thetyee.ca/News/2016/06/22/BC-Ban-Big-Bucks/
