### ISSUE TITLE
Presents story needs header treatment

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#194]

**Comment by MrBryan** [comment]
fixed here

**Comment by MrBryan** [comment]
http://preview.thetyee.ca/Presents/2016/06/28/Mass-Sea-Star-Deaths/index.html

**Comment by alexgreen** [comment]
That link shows the old design.
But you can see the treatment here: http://thetyee.github.io/design-article.thetyee.ca/presents

**Comment by phillipadsmith** [comment]
Re-previewed: http://preview.thetyee.ca/Presents/2016/06/28/Mass-Sea-Star-Deaths/index.html

**Comment by MrBryan** [comment]
assuming we can close..
