### ISSUE TITLE
Presents series box

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#199]
On a presents story, if it's related to a 'Tyee Presents' series page (a `presents` element type in Bricolage), it gets a sidebar that shows the other stories in the series (I think?). This should carry over.

**Comment by MrBryan** [comment]
http://preview.thetyee.ca/Presents/2016/06/28/Mass-Sea-Star-Deaths/index.html

**Comment by MrBryan** [comment]
fixed

**Comment by MrBryan** [comment]
woops hang on this was just the header part i fixed

**Comment by MrBryan** [comment]
So this one we had said we would do post launch but I had been thinking it was a different story type. now i see that it just needs /Presents category . We don't actually have a treatment for this but I can adapt alex's series one quickly tomorrow:

![image](https://cloud.githubusercontent.com/assets/1721891/16404095/c97c1f20-3cc9-11e6-9882-39ff617b71f1.png)

**Comment by phillipadsmith** [comment]
Per Skype, we have a treatment here:
http://thetyee.github.io/design-article.thetyee.ca/presents-series

**Comment by MrBryan** [comment]
got er thanks,  http://preview.thetyee.ca/Presents/2016/06/09/Start-Farmers-Market/index.html

**Comment by alexgreen** [comment]
This issue could be merged with Presents Series doesn't use a proper series box #205

**Comment by phillipadsmith** [comment]
Closing this in favour of #205 for now.
