### ISSUE TITLE
Create Related Event box

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#20]
Create Related Event box (similar to Related Story option). Here’s an example of a story that had a related event (it’s a fact box at the top of the story titled “Standing Up to Fracking: A Tyee Event”): http://thetyee.ca/News/2016/01/13/Supreme-Court-Fracking-Battle/

<img width="963" alt="screen shot 2016-03-25 at 3 28 17 pm" src="https://cloud.githubusercontent.com/assets/1507827/14054362/49d076c4-f29e-11e5-9a23-9fc4422c3daf.png">

**Comment by kidcompassion** [comment]
For your review, @alexgreen! Feel free to change anything you like. You can find it in its own branch, based of the current state of ag-atomic (figured this would make for a nice easy merge) by going:

`git fetch`
`git checkout addition/related-event-box`

![uploads/18fb8023-4912-4159-ae1b-1bb92e41156b/Screen Shot 2016-03-25 at 3.48.14 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F18fb8023-4912-4159-ae1b-1bb92e41156b%2FScreen+Shot+2016-03-25+at+3.48.14+PM.png)

**Comment by alexgreen** [comment]
Thanks!
Is it nested inside an aside.html object with its address passed through the parameter (similar to how related-story.html objects get included)? 
(Sorry haven't pulled yet so I can't see.)

**Comment by phillipadsmith** [comment]
@alexgreen I think this is done, yes?

**Comment by alexgreen** [comment]
In a basic sense yes, but I'd like to add a "related event" badge (similar to the badge in the series block).
In the future it would probably make sense to add fields for standard details like event time and date so that the block is more scannable.
