### ISSUE TITLE
Nav Menu won't close at viewport width 778px – 991px

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#201]
The nav menu stays open at all times and can't be closed.
I see this in chrome on osx and ipad.

**Comment by phillipadsmith** [comment]
> The nav menu stays open at all times and can't be closed. I see this in chrome on osx and ipad.

Where are you seeing this, @alexgreen? On GitHub, or on a previewed page?

**Comment by phillipadsmith** [comment]
I see it on GitHub as well as on previewed pages, FYI, @MrBryan.

**Comment by alexgreen** [comment]
yes, on GitHub as well as on previewed pages.

**Comment by MrBryan** [comment]
It happened with switching away from less . I just previewed with less back in and the menu behaves correctly so going to have to find what differs

**Comment by phillipadsmith** [comment]
> It happened with switching away from less . I just previewed with less back in and the menu behaves correctly so going to have to find what differs

Shit. That's what I was wondering / worried about.

Let me have a look and see what I can find.

**Comment by MrBryan** [comment]
ok the preview site right now has non-less back on so you can use that to compare if you want

**Comment by MrBryan** [comment]
i mean has less back on

**Comment by phillipadsmith** [comment]
So, yah, this is what I vaguely remembered:
https://github.com/TheTyee/design-article.thetyee.ca/commit/960b7005de08e04630a86f04a7420155ad4bddbb

"Adds less.js, so I can recompile bootstrap after changing the default…"

So it sounds like Boostrap got recompiled with some different defaults. I'll need to get that into the bootstrap.min.css.

Working on it...

**Comment by phillipadsmith** [comment]
Fixed in #203
