### ISSUE TITLE
Nav Menu has buggy drop down behaviour at viewport width 778px – 991px

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#203]
The sub-menus appear as popups and the become layered in a weird way. (Observed on ipad and OSX, although the layering of multiple sub-menus doesn't seem to occur on OSX.)

![fe69f7db-d860-4621-9ffd-77a80d9e6ae1](https://cloud.githubusercontent.com/assets/151099/16416288/7e2d2b50-3d7c-11e6-893c-3f7cbf68fa45.PNG)

**Comment by phillipadsmith** [comment]
To clarify, this is _only_ when the menu is in the weird state described in #201

**Comment by alexgreen** [comment]
It seems to happen at the same viewport widths. I don't know about states.

**Comment by phillipadsmith** [comment]
> It seems to happen at the same viewport widths. I don't know about states.

Yes, just clarifying that these "popups" are only visible at the widths described in the other ticket (and are related to that issue).

**Comment by MrBryan** [comment]
this is also from less being removed although there are other issues still with it in - seems breakpoints for the different submenu styling is not set at the right threshold

**Comment by MrBryan** [comment]
or maybe that is intentional that the wider topic menu still shows here > 768
![image](https://cloud.githubusercontent.com/assets/1721891/16427863/6a1ce9b4-3d3d-11e6-826a-ed968b94927f.png)

**Comment by MrBryan** [comment]
More shows as a (vertical one column) list at same spot 
![image](https://cloud.githubusercontent.com/assets/1721891/16427937/b1faa3b6-3d3d-11e6-90ef-a7d9e60777f6.png)

**Comment by MrBryan** [comment]
might have been some css tweak i did accidentally just confirming before I change it

**Comment by phillipadsmith** [comment]
> might have been some css tweak i did accidentally just confirming before I change it

I'm 99.9% sure it has to do with a setting that was in bootstrap.less that's not in bootstrap.min.css

**Comment by alexgreen** [comment]
That's an odd looking More menu. In narrow views it should have borders below each item, as attached, but I didn't do any coding on the nav so I can only speculate.

![screenshot_2016-06-29-03-40-18](https://cloud.githubusercontent.com/assets/151099/16428190/bbcd4be6-3dab-11e6-9e91-ef9ec5c4a892.png)

**Comment by MrBryan** [comment]
well my screenshot is with everything reverted to less

**Comment by MrBryan** [comment]
separate issue, sorry.. confusing. i'll take it up after we sort this out if still there

**Comment by phillipadsmith** [comment]
Okay, so I've recompile Bootstrap from the .less files and _most_ of the issue seems to be fixed:
http://thetyee.github.io/design-article.thetyee.ca/

Branch with specific changes is here:
https://github.com/TheTyee/design-article.thetyee.ca/tree/feature/re-recompile-bootstrap-for-dist

**Comment by phillipadsmith** [comment]
Okay, I fixed the font path issue and I think we're good to go.

@MrBryan You can re-remove the .less and less.js and then you'll need to pull the latest changes from `develop` to get the new bootstrap.min.css and so on.

Phillilp.

**Comment by MrBryan** [comment]
ok did that, seems good

**Comment by phillipadsmith** [comment]
That was my bad for pushing out the bootstrap.min.css without checking for the customizations. :-/
