### ISSUE TITLE
Presents Series doesn't use a proper series box

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#205]
A Tyee Presents story that is also part of a Series should get a Tyee Present Series box as it does in the repo:
http://thetyee.github.io/design-article.thetyee.ca/presents-series
... not some other treatment.
No need to reinvent the wheel here, we've had a solution for weeks.

This issue may be related to the present/series issue #204

**Comment by phillipadsmith** [comment]
Hi Alex,

When reporting these issues, can you provide the URL you're looking at?

Phillip.

**Comment by phillipadsmith** [comment]
(And also can we all commit to be extra cordial to each other during this slightly-stressful run up to the launch?)

**Comment by alexgreen** [comment]
(Yes, sorry. It's just frustrating to see extra work happen because of missed communications.)

URL:
http://preview.thetyee.ca/Presents/2016/06/09/Start-Farmers-Market/index.html

**Comment by phillipadsmith** [comment]
> (Yes, sorry. It's just frustrating to see extra work happen because of missed communications.)

It's going to happen, @alexgreen. 

It's a lot of information to keep in one's head at all times, when also juggling other requests for support from Tyee staff, as well as figuring out all of the CMS-specific implementation. 

Let's just remember that we're all on the same team, working toward the same goals. ;-)

**Comment by MrBryan** [comment]
Fixed, same preview url

![image](https://cloud.githubusercontent.com/assets/1721891/16428509/3c1dd462-3d40-11e6-8988-5ed5fef98e8e.png)
![image](https://cloud.githubusercontent.com/assets/1721891/16428523/48000c00-3d40-11e6-8e90-4f79aa841ad4.png)

**Comment by alexgreen** [comment]
On http://preview.thetyee.ca/Presents/2016/06/09/Start-Farmers-Market/index.html
there's a weird empty aside:
`<aside class="aside" id="placehold"></aside>`
This element is causing a gap between the preceding series-box and the subsequent explainer fact-box. Why is this placeholder there? Can it be omitted?

**Comment by MrBryan** [comment]
i was going to make it zero sized by default in CSS -  i'll do that so it doesn't affect anything. I was using it to fix an issue for showing ads down to smaller resolutions.

**Comment by MrBryan** [comment]
9b6b919
