### ISSUE TITLE
Regular badge hiding underneath Presents badge?

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#211]
<img width="337" alt="mass_sea_star_deaths_shake_up_marine_food_chain___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/16430750/1a161e96-3d32-11e6-95b0-cabf5f777c9a.png">

**Comment by phillipadsmith** [comment]
http://preview.thetyee.ca/Presents/2016/06/28/Mass-Sea-Star-Deaths/

**Comment by alexgreen** [comment]
already flagged this twice at #204
