### ISSUE TITLE
Another issue relating to advertising

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#213]
> 1. In the off-grid story, the Tyee series box seems to chomp into the ad. Not sure if this is a finicky issue related to the preview site?
> 
> http://preview.thetyee.ca/Culture/2014/12/29/Off-Grid-In-Canada/

@alexgreen Are the ad zones doing something with a float attribute that is causing these overlaps to happen?

**Comment by phillipadsmith** [comment]
And another:
http://preview.thetyee.ca/Opinion/2011/12/27/BCRail/index.html

<img width="634" alt="how_bc_rail_was_made_to_disappear___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/16433552/af09a484-3d3f-11e6-986d-b39f33e50736.png">

**Comment by alexgreen** [comment]
Yep, looks floaty! I'll have to investigate.

There's a lot of floating nonsense going on to prevent collision between objects. In all other cases it seems to work, but here obviously not.

**Comment by alexgreen** [comment]
But this involves the new small-legacy-photo styling that only exists in bric. (Normally a photo would not drop into the text column with a wrap like that.) @MrBryan can you carry that style into github so I can reproduce this issue?

**Comment by alexgreen** [comment]
But it's not just a problem with small-legacy-photo styling because I'm also seeing this:

![screen shot 2016-06-30 at 4 48 29 am](https://cloud.githubusercontent.com/assets/151099/16466473/448e6640-3e7e-11e6-95a8-e696b178433d.png)

**Comment by alexgreen** [comment]
@phillipadsmith do you have a screenshot from that reviewer report at top of this thread? When I go to that page the ad is nowhere near the series box.

**Comment by MrBryan** [comment]
All the styles should be synced just need to nest the element the same and it should behave the same - no JavaScript was involved in this one

You'll see there's a point where I disabled floating on an element in the CSS where you had commented that it keeps ads from crashing or something, but with that enabled it was cutting off the first paragraph. It had been working when I was testing but maybe Will need some other solution for the top paragraph thing

I think if you search the CSS file for crash you'll find that entry

**Comment by MrBryan** [comment]
Or maybe that float setting got wiped out by a merge all have a look at it too shortly

**Comment by alexgreen** [comment]
I see related useful screenshots here:
https://basecamp.com/1929296/projects/9481270/messages/59419207#comment_432821828

**Comment by alexgreen** [comment]
Is there some way we can get github.io (and ideally also locally-hosted repos) to show ads? That would help a lot in debugging this.

**Comment by MrBryan** [comment]
Both should already be working as far as I know ( and just tried on mobile ) Do you have a blocker on maybe?

**Comment by alexgreen** [comment]
> Do you have a blocker on maybe?

No, I see ads on the preview website.

**Comment by MrBryan** [comment]
Each domain needs it's own exception rules, I did the same thing earlier, in case that is the prob

**Comment by alexgreen** [comment]
I don't use ad blockers and I'm not seeing the ads on my mobile devices either when viewing locally hosted pages.

**Comment by alexgreen** [comment]
I'm noticing that the ad within feature-media section actually does show up, but none of ads in the article__body do.

**Comment by MrBryan** [comment]
Probably geo targeting because you're in Korea then

**Comment by alexgreen** [comment]
...but then why are the ads in the featured-media section showing up? wouldn't those be subject to the same geo-targeting?

**Comment by phillipadsmith** [comment]
> Is there some way we can get github.io (and ideally also locally-hosted repos) to show ads? That would help a lot in debugging this.

Done.

**Comment by alexgreen** [comment]
I had originally floated the ad-box left to avoid these collisions.
@MrBryan you disabled this float, commenting that it was causing "ads to 'clump' sometimes and to break up paragraphs". Can you show some examples of this?
In the meantime I've re-enable the float ( a809069c20cd1edbb71f6829074631ac7c0d7293 ) and it does seem to solve the collision issues.
