### ISSUE TITLE
Video embeds are not resizing on small viewports

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#214]
http://preview.thetyee.ca/News/2016/05/05/Fleeing-For-McMurray/

<img width="326" alt="iphone_5s_-_iphone_5s___ios_9_3__13e230_" src="https://cloud.githubusercontent.com/assets/34128/16433491/5bc039f0-3d3f-11e6-8da3-1b832d582387.png">

**Comment by alexgreen** [comment]
same prob as #215 

All media objects should be marked up inside a figure, and use a figcaption.
When in doubt see http://thetyee.github.io/design-article.thetyee.ca/library

**Comment by MrBryan** [comment]
Yes I know it has to have that wrap I did that to the embedded media element but it seems that the editors don't often use that but just paste the iframe so I'll have to find a way to detect & add the wrapping but it will be tricky to bring in the blockquote too. hmm..

**Comment by phillipadsmith** [comment]
> Yes I know it has to have that wrap I did that to the embedded media element but it seems that the editors don't often use that but just paste the iframe so I'll have to find a way to detect & add the wrapping but it will be tricky to bring in the blockquote too.

Seems like an editorial error to not have used the `embedded media` element? 

If so, another option would be to create a report of stories where there are iframes in `paragraph` elements and send that to Editorial to clean up.

**Comment by MrBryan** [comment]
Well I made a parsing script in page.mc that works anyways while we move that way. it's repreviewed now

**Comment by MrBryan** [comment]
see here again for successfully parsed: http://preview.thetyee.ca/News/2016/05/05/Fleeing-For-McMurray/

**Comment by phillipadsmith** [comment]
> see here again for successfully parsed: http://preview.thetyee.ca/News/2016/05/05/Fleeing-For-McMurray/

Looking good.

**Comment by alexgreen** [comment]
If possible, it might be good to disable the ability of writers to paste html code into the story body. This appears to be the source of a number of issues. Seems like there should never be any reason for writers to paste html, and the ability to do so only invites trouble.

**Comment by phillipadsmith** [comment]
> If possible, it might be good to disable the ability of writers to paste html code into the story body. This appears to be the source of a number of issues. Seems like there should never be any reason for writers to paste html, and the ability to do so only invites trouble.

We've attempted to do so, for sure. Unfortunately, they've learned to work around certain limitations of the CMS by adding small bits of HTML.

It will require some re-training to avoid this entirely.
