### ISSUE TITLE
Long bios are cut off

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#216]
<img width="871" alt="how_bc_rail_was_made_to_disappear___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/16433583/dd5c7c76-3d3f-11e6-964f-3f14d006772a.png">

http://preview.thetyee.ca/Opinion/2011/12/27/BCRail/index.html

**Comment by alexgreen** [comment]
see http://thetyee.github.io/design-article.thetyee.ca/library
see also #212

**Comment by phillipadsmith** [comment]
Doesn't look right to me:

<img width="385" alt="margolese_prize_winner_bing_thom_on_the_art_of_placemaking___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/16504871/fad8ddb8-3ece-11e6-80e0-f34ece930666.png">

**Comment by alexgreen** [comment]
Bio is now hidden in views < 600px. 
Fixed in develop branch by cfce8a09d982e9ffb7c092384f0d6dcc0fc932c6

**Comment by phillipadsmith** [comment]
Hi Alex,

I see this was re-opened? Accident?

**Comment by MrBryan** [comment]
I just added it to the live site -- it required bric template adjustments couldn't just include it so it is good it was re-opened for me to see ...

Repreviewed this story : http://preview.thetyee.ca/Opinion/2011/12/27/BCRail/index.html

(other stories will still lack "read more" link until repreviewed)

 now closing

**Comment by phillipadsmith** [comment]
Bigger issue here, @alexgreen:

From Robyn: 

> The author bio for this story is not the same as the one on the author’s “bio” page, because it includes different credit information for the specific article. This is true of many stories -- the bio on the article page will be different than the bio on the author’s specific page. So the “read more” option doesn’t work. You will click “read more” thinking you’ll get to read the end of the sentence, and then be taken to a bio page that includes none of the pertinent information.

So, in summary, we can't truncate long bios here and have a "read more" that links to the author's bio page. Could the div be expanded to show everything, instead? Otherwise, I think we need to let the bios run full length on large enough screens (where the bio is not hidden).

**Comment by phillipadsmith** [comment]
Related...

letter ‘g’ in two-line bios
URL: http://preview.thetyee.ca/Mediacheck/2016/04/12/Affordable-Internet-Access/
Description: Such a minor thing, not at all critical with regards to launch.  But on my computer (PC / firefox), the very bottom of any ‘g’ gets cut off in the bio.
Reporter: Michelle
Screenshot:

<img width="497" alt="tyee_staff_consolidated_article_page_feedback_-_google_docs" src="https://cloud.githubusercontent.com/assets/34128/16674861/1bb6947e-4471-11e6-8f21-befa02887e22.png">

**Comment by MrBryan** [comment]
Seems pretty trivial for us to just make the read more hide the "read more" link and remove the overflow = hidden

**Comment by MrBryan** [comment]
Hopefully this is the only instance of these two paragraph long author bios?

http://preview.thetyee.ca/News/2016/03/08/UN-Tells-Canada-Clean-Up-Inequality/index.html

![image](https://cloud.githubusercontent.com/assets/1721891/16740510/53378562-476d-11e6-8f7b-3bc1bb96358c.png)

![image](https://cloud.githubusercontent.com/assets/1721891/16740478/3b00ea06-476d-11e6-874f-7773e59e66ee.png)

**Comment by phillipadsmith** [comment]
> Hopefully this is the only instance of these two paragraph long author bios?

I've never seen that before.

@robynleighsmith ?

**Comment by phillipadsmith** [comment]
> Seems pretty trivial for us to just make the read more hide the "read more" link and remove the overflow = hidden

👍

**Comment by MrBryan** [comment]
I can also detect when it's overriding the link /canned bio like that and only do the expand this way in those cases

**Comment by phillipadsmith** [comment]
> I can also detect when it's overriding the link /canned bio like that and only do the expand this way in those cases

According to @robynleighsmith the bio is always updated on a per-story basis, and the other bio -- from the bio story -- is almost never used.

**Comment by robynleighsmith** [comment]
Yes, bios can differ from story to story. 

One reason: they can include different funder information. So for example, some of Katie's education stories include a long two paragraphs of funder attribution that wouldn't appear on others. Now, I'm not sure if that information needs to go in the bio section on the new article page, or just in italics at the bottom of the article. But it's something to note.

Another reason: There can be two or more authors on a story, requiring more space.

Another reason: A reporter may have had help with their story, from a researcher for example. So the bio box is usually where the "helpers" are credited.

Not sure I understand Bryan's idea for a resolution, but hopefully this gives you a sense of why it's important to resolve this issue before launch (particularly for all the old stories that have very long bios -- there will be a huge number of them).

Hope this helps.

**Comment by MrBryan** [comment]
Basically what I'm saying is that if there isn't a bio field overwriting the canned one it will do what it's doing now. But if that's so rare it may not be worth implementing. So I can just do the expand thing for all of them if Alex doesn't have a problem with  that. You can test I will look if you just remove the overflow : hidden property

**Comment by robynleighsmith** [comment]
Okay, I'll wait to see how it looks when updated.

**Comment by alexgreen** [comment]
Sounds good to me.

**Comment by alexgreen** [comment]
None of the stories in preview seem to have headshots anymore. @MrBryan can you put those back in so I can revise the styling?

**Comment by robynleighsmith** [comment]
@alexgreen @MrBryan Not sure how the author headshots are sourced or if they still need to be uploaded into Bricolage. I can organize that for tomorrow if it would be helpful.

**Comment by MrBryan** [comment]
I didn't remove any but each has to be uploaded. That would probably be helpful @robynleighsmith - I think Phillip has that in his list, there is a spreadsheet of all the images. They must be cropped to square before uploading

**Comment by MrBryan** [comment]
and added as the related media to the author bio in bric + republished

**Comment by MrBryan** [comment]
Also - this fix will have to get more sophisticated since the read more will show presently even if the text is only a sentence (and not truncated). I will have to use js to detect if it is overflowing or not

**Comment by alexgreen** [comment]
So what will the "read more" do when the bio is only 1 line long?

![screen shot 2016-07-11 at 5 10 57 pm](https://cloud.githubusercontent.com/assets/151099/16750975/af8ff8b8-478a-11e6-931e-708e027ef575.png)

**Comment by MrBryan** [comment]
it won't be there per above -- will detect if it's overflowing & only show the link then

**Comment by MrBryan** [comment]
OK that is working a3484f5 :

http://preview.thetyee.ca/News/2016/01/11/California-Gas-Leak/

**Comment by robynleighsmith** [comment]
Great!

**Comment by alexgreen** [comment]
The html structure isn't matching github and it's causing the "Read more" to be the wrong size.

`<a href="/Bios/Andrew_Nikiforuk" class="author-more" style="display: block;">... read more</a>`

should be inside

`<span class="author-info__bio" data-bind="author-bio">`

**Comment by MrBryan** [comment]
Fixed ... repreviewed same story (wont' be on others until repreview)
