### ISSUE TITLE
Adjust negative margin below videos

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#219]
I've added a margin below featured-media section ads to ensure adequate spacing from asides:
1cb77fbb34cba805c5175ec10c3f2e8c3778341d
This is required for when js applies a negative margin below a featured-media video placement and it should affect the layout otherwise.
@MrBryan please adjust the js to compensate by decreasing the margin-bottom another 43px (e.g. from -83 to -126).

**Comment by MrBryan** [comment]
fixed with bc4dd54 -- 43px more gap  (its initial value is the difference in height between the two objects:  var mediaHeight=  $('.featured-media .figure').outerHeight();
        var sectionHeight=  $(".featured-media .ad-box").outerHeight(); )

**Comment by MrBryan** [comment]
*less gap not more

**Comment by alexgreen** [comment]
Since the .ad-box--halfpage is set to height: 600px a gap is created when this spot is occupied by a bigbox which is only 250px high. The 600px css height overrides the negative margin set by the js and prevents the following aside from moving up to be flush with the top of article__body. (Unfortunately I can no longer get any bigbox ads to come up in the position right so I have no screenshot.)

In an attempt to prevent this gap I've removed all the css declarations that specify the height of the halfpage ad position, thus allowing the featured-media section to collapse to the height of its media contents so that the top of the first aside can be flush with the top of article__body. The branch is here: https://github.com/TheTyee/design-article.thetyee.ca/tree/ag--featured-video

@MrBryan This seems compatible with the js function you wrote and it did seem to work 30 min ago when the bigbox ad was coming up in that position. But for some reason the js would only activate if I resized the page after loading. Do you have any idea why that would be and how to correct it?

(It's a hassle to test this because the bigbox only shows up sometimes.)

**Comment by MrBryan** [comment]
hmm well the function that loads is called  fixFeaturedMediaOffset() which is set to fire at document.ready as well as resize but it's possible it has to be set to window.load which happens after all images are present.. I don't think so though because the sizes are specified so should be reserved.

You could test it by adding another call to it in the js like this:

$(window).load(function() {
        fixFeaturedMediaOffset();
});

**Comment by MrBryan** [comment]
I don't think it looks too bad to have the asides starting down a little further personally, maybe not a launch blocker

**Comment by alexgreen** [comment]
> maybe not a launch blocker

Yeah not top priority but it would be great to do if there's time.

**Comment by alexgreen** [comment]
I came across an old screenshot that illustrates the issue.
And here's the weblink: http://preview.thetyee.ca/Presents/2016/05/06/Save-Haida-Language/

![screen shot 2016-07-12 at 10 56 34 pm](https://cloud.githubusercontent.com/assets/151099/16821974/634c0552-490e-11e6-8868-cc47e575c5e1.png)

**Comment by alexgreen** [comment]
> You could test it by adding another call to it in the js like this:
> 
> $(window).load(function() {
> fixFeaturedMediaOffset();
> });

Are you proposing to just ad it to the beginning of fixFeaturedMediaOffset() like this?:

```
function fixFeaturedMediaOffset(){
    $(window).load(function() {
        fixFeaturedMediaOffset();
    });
    if ($(window).width() >= 1200 && ($('.featured-media .figure').height() >= 5 )  ) {
        var mediaHeight=  $('.featured-media .figure').outerHeight();
        var sectionHeight=  $(".featured-media .ad-box").outerHeight();
        if (  (sectionHeight - mediaHeight) >= 0) {

            var mediamargin =  mediaHeight - sectionHeight + -13;
            $("section.featured-media").css("margin-bottom", mediamargin);

            if (navigator.userAgent.indexOf('Safari') != -1 && navigator.userAgent.indexOf('Chrome') == -1)  { 
                            var negmargin = -1 * mediamargin;
                            $($("article .container-fluid aside")[0]).css("margin-top", negmargin);
        }
        }
    } else {
        $("section.featured-media").css("margin-bottom", "inherit");
        $($("article .container-fluid aside")[0]).removeAttr("style");
    }
}
```

**Comment by MrBryan** [comment]
no that would cause an infinite loop  put it just after the closing brackets

function readMore(){
var author = $(".author-info div")[0];

if (author) {
    if (author.offsetHeight < author.scrollHeight && !$(".author-info__text").hasClass("overflow") ) {
            $(".author-more").css("display","block");
    } else {
        $(".author-more").css("display","none");
    }

}
}

   $(window).load(function() {
        fixFeaturedMediaOffset();
    });

**Comment by MrBryan** [comment]
This was resolved some time ago I believe
