### ISSUE TITLE
IMGs in Related-story blocks are cropped and not tall enough

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#223]
Problem occurs here, but also on all other preview pages I've seen: http://preview.thetyee.ca/News/2016/06/22/BC-Ban-Big-Bucks/

It should be like as here: http://thetyee.github.io/design-article.thetyee.ca/library

**Comment by phillipadsmith** [comment]
I think this is because @MrBryan is re-using an existing thumbnail size there.

@MrBryan worth seeing if Thumbor could help here, and re-crop the largest image down to square? 

Phillip.

**Comment by alexgreen** [comment]
Square would be pretty tall. 
The best is if they can just have a normal 3x2 photo aspect ratio. The CSS scales the image depending on the browser view, but the largest pixel size they appear is about 243 x 162 (although I guess double that for retina).

**Comment by MrBryan** [comment]
we already have squares for lots of these too so I used that for now, can look at thumbor as part of the whole package when we look at that soon

fixed & previewed here (not all stories) 

http://preview.thetyee.ca/News/2016/06/22/BC-Ban-Big-Bucks/

**Comment by alexgreen** [comment]
Thanks, looks much better now! 

I'll open a low-priority issue for post-launch revisitation.
