### ISSUE TITLE
Wide featured featured images should be cropped server-side

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#226]
> We have a different tool for re-sizing/cropping photos "on the fly;" it's really best not to crop in CSS because then the client is receiving too much image (unnecessary bandwidth) which impacts performance.

That makes the css much simpler, but the images really only need by cropped in certain viewports, whereas in most views we could actually display the full uncropped image.

Cropping server-side is definitely simpler so let's go with that for the sake of launch expediency, but it risks losing important peripheral image elements and composition in the case that someone has a good reason for uploading a wide aspect photo. Admittedly this will likely be very rare (other than video) so probably it's pretty low priority.

For server-side cropping please set all featured images to be cropped to 3 x 2, so that the width is equal to no more than 1.5 times the height. For example an image that is 400px tall should be no wider than 600px. Only the width needs to be cropped, tall images should be ok.

**Comment by MrBryan** [comment]
-umLet's talk to editorial on that one I think they were happy with bumping the content up to fit

**Comment by phillipadsmith** [comment]
> Let's talk to editorial on that one I think they were happy with bumping the content up to fit

Yes, I think what's being discussed here is cropping _down_ to the required size (vs. bumping up).

I think you've already resolved this, @MrBryan, as we discussed it last week.

Phillip.

**Comment by MrBryan** [comment]
so.. nothing left to do here?

**Comment by phillipadsmith** [comment]
> so.. nothing left to do here?

Think we're good for now.
