### ISSUE TITLE
Irregularities in positioning of main-col-container and asides 

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#227]
The main-col-container jumps around irregularly between vw 700px and 900px. The asides are also affected.
http://thetyee.github.io/design-article.thetyee.ca/

**Comment by alexgreen** [comment]
This seems to be caused by the following css breakpoints:

```
/* more attempts at cross browser / os alignment issues w/ small image in play  BC */
 @media screen and (min-width: 700px) and (max-width: 880px) {
  .main-col-container {
     margin-left: auto;
          margin-right: auto;
    left: -7%; 
   left: calc( -1 * ( ((100vw - 33em) / 2) - (3em) ) );

 }
 }

 @media screen and (min-width: 640px) and (max-width: 755px){
    .main-col-container {
      max-width: 90%;
    }
 }
  @media screen and (min-width: 740px) and (max-width: 880px) {
    .ad-box--halfpage.smaller {
    margin-right: -25%;
    }
 }
```

I have commented out these rules and that resolves the issue.
I think this may also make it easier to resolve ad+aside collision issue and prevent future layout unpredictability.

@MrBryan, it looks like the rules were added to style the edge case of small feature images. Is there a way to style those images without affecting the css of the main-col-container? Since that new figure medium object lives inside the main-col-container it shouldn't care where the container is located on the page. If you port over the legacy small-image pages to the github repo then I can help with styling it.

**Comment by alexgreen** [comment]
2d6e2caf8cf648c269403ec8ab7824ecf3f36558 resolves this issue

**Comment by phillipadsmith** [comment]
> If you port over the legacy small-image pages to the github repo then I can help with styling it.

I can do this quickly.

**Comment by phillipadsmith** [comment]
The example is here:
http://thetyee.github.io/design-article.thetyee.ca/legacy-small-image

I've asked @MrBryan to confirm that I've got the structure right, i.e., matching what the CMS is outputting when it detects a small feature image. 

@alexgreen Hoping you can look at this ASAP because The Tyee staff are reviewing stories tomorrow.

**Comment by alexgreen** [comment]
Thanks Phillip!

Everything seems fine on that example page.

**Comment by phillipadsmith** [comment]
> Everything seems fine on that example page.

👍 

Closing the issue then.
