### ISSUE TITLE
aside.placehold is causing a blank object that creates a gap in the layout

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#229]
On http://preview.thetyee.ca/Presents/2016/06/09/Start-Farmers-Market/index.html
there's still a weird empty aside:
<aside class="aside" id="placehold"></aside>
This element is causing a gap between the preceding series-box and the subsequent explainer fact-box. Why is this placeholder there? Can it be omitted?

@MrBryan the css changes you've made in the repo aren't propagating to preview.
Also, setting the width and height to 0 doesn't change anything because the size of the object is caused by its margin.
But

```
    aside#placehold {
            display: none;
    }
```

should work to prevent displaying it.

**Comment by MrBryan** [comment]
Haven't pulled yet from because have to fix other issues like the section you commented out that enabled the medium sized images. I thought I had noticed that the gap was closed when I changed it to zero but I will test again when I get a chance

**Comment by alexgreen** [comment]
> have to fix other issues like the section you commented out that enabled the medium sized images

Sorry bout that.
The .main-col-container styling is really the scaffold of the layout and most other things hang off of it or are contained by it, so any changes to it are likely to cause problems. The best thing is if objects just sit inside it and are positioned relative to it (like figures and asides). I've tried to comment everything as I go, but haven't had a chance to distill all the comments into one concise description yet.

**Comment by MrBryan** [comment]
I set to display none for now . Will address the main-col-container thing in the relevant thread later
