### ISSUE TITLE
Factbox doesn't appear on small screens -- is this correct?

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#230]
@alexgreen I can't remember the final, final, final decision about what should appear on small screens vs. what's okay to hide (from the Editorial team). 

This story has what would seem like an important fact box in the sidebar on larger screens, but it's gone on smaller screens: http://preview.thetyee.ca/News/2016/01/08/End-Fracking-Regulator-Immunity/

Does that jive with what's supposed to happen? 

Phillip.

**Comment by phillipadsmith** [comment]
Another example of an important-looking fact box that disappears:
http://preview.thetyee.ca/News/2016/01/11/California-Gas-Leak/

**Comment by alexgreen** [comment]
@phillipadsmith You're right, that's incorrect. In narrow views the fact-box should appear at the bottom of the article (instead of in an aside). You can see this in operation at http://thetyee.github.io/design-article.thetyee.ca/library

This behaviour is explained in the comments of the Fact-box.html object:

> The fact appears at the bottom of the article by default, but appears in the sidebar in wider viewports. This is done by changing the value of the fact-box's display property based on location/context and viewport width (by targeting .fact-box via css). 
>     The additional .hide-on-narrow-vp class gets applied to the containing 
>     <aside> so that its margin doesn't cut into the the text column when
>     the fact box is hidden. (This ugly class could probably be eliminated if 
>     asides were simply a class rather than a container, or if an aside's 
>     margins were applied to it's contents instead of the container itself.)
> 
> In default (narrow) viewports there should be the option of putting an anchor text-link within the article body text so that readers can easily get down the page to the fact-box. E.g:
> `<a href="#fact-box-1" class="fact-box__anchor-link">Inline link to fact box.</a>`
> ... as seen in the atom fact-box-anchor-link.html which can be embedded into the paragraph.html atom.
> This link will be set to display:none in wider viewports. 
> There is empty `<span id="fact-box-1"></span>` at the bottom of the article__body to serve as the destination anchor for this link. (Assign #fact-box-1 to the fact-box object itself wouldn't work because the html for this object appears in 2 locations on the page.)

So basically the fact-boxes should get marked up in both locations of the page and then display visibility of one or the other is determined by css according to view width.

**Comment by MrBryan** [comment]
Fixed here, must be repreviewed for any other stories

http://preview.thetyee.ca/News/2016/01/11/California-Gas-Leak/

**Comment by phillipadsmith** [comment]
Same as previous issue, the fact box is visible at small viewports, but the disclaimer is not visible.

**Comment by MrBryan** [comment]
samesies -- it's at the bottom of story

**Comment by alexgreen** [comment]
We're only talking about the .fact-box--explainer object now (aka disclaimers) and that has its own issue thread ( #263 ), so I'm going to close this issue.
