### ISSUE TITLE
Fix Philip's crappy template logic for tags

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#231]
<img width="363" alt="liberals_extend_deadline_to_donate_to_syrian_refugee_matching_fund___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/16543524/3d5b0534-408d-11e6-926b-8bc3c019e1ab.png">

**Comment by MrBryan** [comment]
Did you do this already? I can't seem to reproduce it

![image](https://cloud.githubusercontent.com/assets/1721891/16965065/683c62a6-4dcc-11e6-98b9-909a95d1a35c.png)

**Comment by MrBryan** [comment]
Calling it closed

![image](https://cloud.githubusercontent.com/assets/1721891/16965085/83b23178-4dcc-11e6-8c8b-f771e3f2f4b1.png)

**Comment by phillipadsmith** [comment]
http://thetyee.ca/Culture/2016/07/21/Shoe-Boy-Trapline-Memoir/

<img width="744" alt="that_first_goose__excerpt_from_a_trapline_memoir___the_tyee_" src="https://cloud.githubusercontent.com/assets/34128/17042519/0c6aa2ce-4f63-11e6-98a1-a42711475e48.png">

**Comment by MrBryan** [comment]
Fixed (when the story makes it way through the queue). Tested with preview.

Basically the template was looping through categories then showing only if /Topic was present in the uri. But in the same loop it was deciding whether to include an apostrophe based on if there were more categories in the array independent of whether it has /Topic so it could evaluate that there were more, show the apostrophe, then the /Topic check would show nothing.

**Comment by MrBryan** [comment]
Decided it's probably not worth much republishing but will work going forward
