### ISSUE TITLE
Whole story in italics?

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#233]
Bug or feature? http://preview.thetyee.ca/Opinion/2016/01/16/Never-See-100-Barrel-Oil-Again/

**Comment by phillipadsmith** [comment]
Seems okay on the live site: http://thetyee.ca/Opinion/2016/01/16/Never-See-100-Barrel-Oil-Again/

**Comment by alexgreen** [comment]
Bug. My browser says there's a "user agent stylesheet" that is imposing the italics. That makes me suspect we aren't using a proper CSS reset. But aren't we?

Anyway, I just added

```
p {
  margin-bottom: 1em;
  font-style: normal;
}
```

to the css and that seems to fix it. It's only a 1-line change so I'll just push it as merge from ag-atomic.

**Comment by alexgreen** [comment]
Thanks for catching this!

**Comment by alexgreen** [comment]
Yeah this is definitely weird, because even the asides are set in italics.
I had to add

```
/* Reset to prevent some articles form displaying in italics */
h1, h2, h3, h4, h5, h6, p, a, blockquote, .ad-box {
  font-style: normal
}
```

to get it to reset to normal.

Makes me wonder if there's some deeper problem.
