### ISSUE TITLE
Second ad zone in short stories?

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#234]
I think we've got this recorded already, but I'm not 100% sure what was decided. Here's a short story, and it shows only one big box advertisement in the text column: http://preview.thetyee.ca/News/2016/01/14/Teachers-Bargaining-Supreme-Court/

I think that Michelle's requirement is that there are always two, no matter how short the article?

**Comment by MrBryan** [comment]
No I believe she agreed that when it is very short it should not show. Presently if there are less than 17 "places" (paragraphs, images etc) the second ad will never arrive

**Comment by phillipadsmith** [comment]
> No I believe she agreed that when it is very short it should not show. Presently if there are less than 17 "places" (paragraphs, images etc) the second ad will never arrive

Ah, yes? Okay, as long as that was acceptable to Michelle. :-)
