### ISSUE TITLE
Also in this series box is wonky at small size

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#239]
Some serious wonkiness in this story with the series box and YouTube embed and so on. All issues reported previously, I think. And yet this is a good test story to work on for fixing: http://preview.thetyee.ca/News/2016/06/07/Aging-Out-of-Foster-Care/

**Comment by MrBryan** [comment]
Everything seems to be working correctly  now, yes?

**Comment by phillipadsmith** [comment]
> Everything seems to be working correctly now, yes?

Yep.
