### ISSUE TITLE
New Tyee Presents "sidebar" element

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#240]
@MrBryan Let's sync up today if possible to discuss the new Tyee Presents sidebar element and what needs to happen in the business office to make that possible for launch, or shortly after. 

I'm happy to take on the Bricolage work on this requirement -- setting up the story, and figuring out the other elements -- if you're focused on fixing the issues that have been identified so far.

I'm on Skype until 12:45PM PT, then again after 4PM PT.

**Comment by MrBryan** [comment]
i'l be working probably until late tonight so if you are still around any time is good -- if you want to take the lead on the bric side that works for me otherwise I can fit it in after this round of catch up on the github stuff

**Comment by alexgreen** [comment]
Are you talking the Tye Presents object as it appears on http://thetyee.github.io/design-article.thetyee.ca/library ? Or is this about something else?
