### ISSUE TITLE
Contributor photos: next steps?

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#241]
https://docs.google.com/spreadsheets/d/12iHJSL59n0ZjifNVyQ-__DTueY0Buk2_Ev_SmAIDdII/edit#gid=0

**Comment by phillipadsmith** [comment]
Oh, yah, forgot to ask @MrBryan: What's the plan here?

**Comment by MrBryan** [comment]
I believe a fellow sharing the same initials as the acronym convention for "post script" volunteered to do some bric data entry on that one... But British Columbia could put that in his queue just as easily

**Comment by phillipadsmith** [comment]
> I believe a fellow sharing the same initials as the acronym convention for "post script" volunteered to do some bric data entry on that one... But British Columbia could put that in his queue just as easily

I vaguely remembered ~~there~~ that, so I wanted to be sure that was the plan! :-P

These are just related media to the bio story? Anything fancy I need to remember? 

Phillip.

**Comment by MrBryan** [comment]
Yup exactly, just publish the related image and it should work. It has to be square
