### ISSUE TITLE
Comment icon (and link to comments) is missing from article header

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#245]
Robyn mentioned this the other day:

<img width="447" alt="_pennies_for_billions___aboriginals_fight_near_giveaway_of_pipeline_rights_in_1952___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/16628979/d1d3f486-4368-11e6-9b17-f1cb12fbbecc.png">

... Possible to sneak in that icon before launch, and to link it to the comments div ID? Extra points for expanding the comments open too.

**Comment by MrBryan** [comment]
fixed, now links to comments & opens/expands
