### ISSUE TITLE
Include new Tyee Presents "Spotlight" include

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#246]
Here she lives:
http://preview.thetyee.ca/ui/inc/presents-spotlight/include.php

The story in Bricolage is called "Tyee Presents Spotlight"

**Comment by MrBryan** [comment]
I can detect for empty and omit the element in bric

**Comment by MrBryan** [comment]
Can you remind me - we want this in every story?

**Comment by phillipadsmith** [comment]
> Can you remind me - we want this in every story?

Correct, unless it's a story in the /Presents category.

**Comment by phillipadsmith** [comment]
Closed, I think?

**Comment by alexgreen** [comment]
> The story in Bricolage is called "Tyee Presents Spotlight"

? Isn't "Tyee Presents Spotlight" a block?
btw why did the name get changed from presents-box to tyee-presents-spotlight?

**Comment by phillipadsmith** [comment]
> btw why did the name get changed from presents-box to tyee-presents-spotlight?

"Presents box" was getting too easily confused with the Tyee Presents **series** box. 

So I picked another name that made the intention more obvious: too spotlight (or highlight, or draw attention to) Tyee Presents content.
