### ISSUE TITLE
What happens / should happen to old The Hook stories? 

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#248]
e.g., http://preview.thetyee.ca/Blogs/TheHook/Education/2010/09/16/ChairLangleySchoolResigns/

**Comment by MrBryan** [comment]
Looks like I did miss those -- I will have to do some css overrides for those hook pages for interim . There are enough odd elements that I don't think it's worth bringing them into the new layout

**Comment by MrBryan** [comment]
Gave them a passable treatment in CSS - repreviewed the above. They'll all have to be republished

**Comment by phillipadsmith** [comment]
Not looking "passable" to me just yet (looks like an unclosed div or something?):

<img width="1076" alt="chair_of_langley_school_board_resigns__cites_pressure_from_other_trustees___the_hook__a_tyee_blog_" src="https://cloud.githubusercontent.com/assets/34128/16742936/e2d59556-475e-11e6-8bf7-8b364aaaca2e.png">

**Comment by MrBryan** [comment]
Fixed that -- you have to hard-refresh because the css file is hard coded into each html story so can't increment with an include...
