### ISSUE TITLE
Fix CSS syntax errors

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#249]
Hi @alexgreen,

Hoping you can review and resolve these CSS syntax errors: 

> CSS lint found 19 errors

Just copy and paste article.css into http://csslint.net/ to see the problems (missing properties, extra commas, etc.)

Have you had a chance to set-up CSS "linting" in your editor? Most of this is immediately visible
<img width="1200" alt="article_css___private_var_folders_xl_456_wxzx2l17s2vpn44s___eanup_at_startup_c62a7880-d3ab-4942-82c8-86c53934add4__-_vim" src="https://cloud.githubusercontent.com/assets/34128/16668001/0016d6f2-4444-11e6-9eff-37eb351116c1.png">
 to me when I open the CSS file because I have that set-up, e.g.:

The reason we need to fix these up is because the mod_pagespeed module, which we're using to improve performance, can't optimize CSS with parse errors, and it's currently reporting: "CSS rewrite failed: Parse error in http://pagespeed.thetyee.ca/design-article.thetyee.ca/ui/css/article.css"

I'm happy to go through and clean these up, and yet some may require your input so it might make sense for you to review first.

Phillip.

**Comment by alexgreen** [comment]
I'm going through them now.
I tried to install a https://packagecontrol.io/packages/CSSLint for sublime text but when I run I get 
`Unable to access jarfile /Users/alexg/Library/Application Support/Sublime Text 2/Packages/CSSLint/scripts/rhino/js.jar
`
But that file has universal read permissions so I don't what it's talking about.

**Comment by alexgreen** [comment]
I fixed them with a couple exceptions:

(1) I don't know what this rule is for or what it means. @MrBryan can you have a look at this one?

> 343   Parsing Errors  Unknown @ rule: @-moz-document.
>  @-moz-document url-prefix() {

(2) The linter turns up 10 errors about brackets and parentheses, but as far as I can see these rules are syntactically correct. e.g.:

> Expected RBRACE at line 1215, col 23.<pre>          left:  calc((34em-100vw+0px)/2);</pre>

It would clearly be wrong to put a right brace at col 23. Any ideas?

**Comment by phillipadsmith** [comment]
> It would clearly be wrong to put a right brace at col 23. Any ideas?

Problem with the parser, it would seem: 
https://github.com/CSSLint/csslint/issues?utf8=%E2%9C%93&q=is%3Aissue%20Expected%20RBRACE

Many thanks for cleaning those up. Appreciated. 

@MrBryan over to you on this question:

> 343 Parsing Errors Unknown @ rule: @-moz-document.
> @-moz-document url-prefix() {

**Comment by MrBryan** [comment]
That is a class that is used to target Mozilla Firefox. It fixed an issue where the drop padding  was not correct and was cutting off the character

**Comment by phillipadsmith** [comment]
> That is a class that is used to target Mozilla Firefox. It fixed an issue where the drop padding  was not correct and was cutting off the character

Still required?

**Comment by MrBryan** [comment]
yup.. did someone disable it on develop already? it used to fix this

![image](https://cloud.githubusercontent.com/assets/1721891/16745774/709bf5a8-4785-11e6-94ee-7a7b745c05de.png)

**Comment by MrBryan** [comment]
sorry no it is still in place.  Here is without it on firefox:

![image](https://cloud.githubusercontent.com/assets/1721891/16745896/025c1aea-4786-11e6-989e-10ca3f055df3.png)

**Comment by MrBryan** [comment]
and with 

![image](https://cloud.githubusercontent.com/assets/1721891/16745912/0ea7e356-4786-11e6-8e7b-f4e60cc4e81b.png)

**Comment by MrBryan** [comment]
( http://thetyee.github.io/design-article.thetyee.ca/library.html )

**Comment by phillipadsmith** [comment]
> sorry no it is still in place. Here is without it on firefox:

Ah, okay, no worries. Just wanted to confirm it was still needed so that I can close this issue. Thanks! :-)
