### ISSUE TITLE
Determine if / when the '#series-listview-link' is needed

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#250]
Hi @alexgreen,

The `#series-listview-link` is in the HTML structure for the Presents Spotlight block, e.g.:
http://preview.thetyee.ca/ui/inc/presents-spotlight/include.php

... However, I'm unclear what it does/should be linking to? Can you confirm?

**Comment by alexgreen** [comment]
Is the Presents Spotlight block a renamed version of presents-box.html?

I guess you mean
`<a href="#series-listview-link" class="series-badge {{ include.badge-position }}"><img src="{{ site.url }}ui/img/badge-presents.svg"></a>`
?

This line is part of the presents-badge.html object. This object appears in three places on the page:
1. next to the headline in the article__header
2. at the top of a presents-box
3. at the top of a presents-series-box

Initially I thought that in the context of the presents-series-box the badge it should link to a series index page, but now I think it should just link to http://thetyee.ca/About/Advertise/Tyee-Presents/ in all cases.

I've changed the object's code to reflect that:
`<a href="http://thetyee.ca/About/Advertise/Tyee-Presents/" class="series-badge {{ include.badge-position }}"><img src="{{ site.url }}ui/img/badge-presents.svg"></a>`

Sound good?

**Comment by phillipadsmith** [comment]
> Is the Presents Spotlight block a renamed version of presents-box.html?

It's just the name of the include in Bricolage.

> Initially I thought that in the context of the presents-series-box the badge it should link to a series index page, but now I think it should just link to http://thetyee.ca/About/Advertise/Tyee-Presents/ in all cases.
> Sound good?

Yes, I think we can live for that now and revisit later if Business has any concerns. 

@MrBryan Can you implement this change?
