### ISSUE TITLE
Link slug to relevant Category

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#254]
<img width="462" alt="why_gawker_s_first_contract_is_a_blueprint_for_unions___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/16674080/6cb01b6e-4469-11e6-9258-93da8781cd8e.png">

**Comment by MrBryan** [comment]
Fixed (on repreview) http://preview.thetyee.ca/Culture/
