### ISSUE TITLE
Figure out why this story didn't preview properly

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#255]
http://preview.thetyee.ca/Culture/2016/03/08/International-Womens-Day-Poem/

**Comment by MrBryan** [comment]
Had to add a condition to allow for the possibility of single paragraph stories  (fixed)

**Comment by phillipadsmith** [comment]
> Had to add a condition to allow for the possibility of single paragraph stories (fixed)

What the heck is that?

**Comment by MrBryan** [comment]
Just when there was only one paragraph in the story it was failing the way perl was testing for presence of elements to apply drop caps or not
