### ISSUE TITLE
Social icons in footer should link to ‘like’ and ‘follow’ pages, not share story

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#260]
Social icons in footer should link to ‘like’ and ‘follow’ pages, not share story
URL: Any page
Description: Isn’t the standard practice that when you see the facebook and twitter icons at the very top or very bottom of a site, that it’s intended to send you to the brand’s facebook page or twitter page so that you can join?  Currently, when you click the icons in the footer, it shares the particular story you’re on.
Reporter: Michelle

**Comment by MrBryan** [comment]
Fixed  everywhere (was in include)
