### ISSUE TITLE
Presents "disclaimer" sidebar should not hide on small screens

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#263]
On Android phone, Tyee Presents disclaimer text doesn’t appear
URL: http://preview.thetyee.ca/Presents/2016/04/14/To-Plan-or-Not-to-Plan/
Description: On my nice big monitor, this displays right at the top of the article, quite unmissable. But on my android phone, the disclaimer just disappears.
<img width="538" alt="tyee_staff_consolidated_article_page_feedback_-_google_docs" src="https://cloud.githubusercontent.com/assets/34128/16674773/663f726e-4470-11e6-8412-03cdd6dd88f8.png">

**Comment by phillipadsmith** [comment]
Related:

On Android phone, Tyee Presents FACT BOX doesn’t appear
URL: http://preview.thetyee.ca/Presents/2016/04/14/To-Plan-or-Not-to-Plan/
Description: On my nice big monitor, this displays farther down in the article, well presented.  But on my android phone, it disappears. This will often be very critical info for a Tyee Presents feature.
Screenshot: 

<img width="533" alt="tyee_staff_consolidated_article_page_feedback_-_google_docs" src="https://cloud.githubusercontent.com/assets/34128/16674790/90fc9004-4470-11e6-897f-9fd2c334027b.png">

**Comment by alexgreen** [comment]
—not just on android, the fact-box and fact-box--explainer don't display at all in narrow views. I explained the problem here: #230

**Comment by MrBryan** [comment]
OK that's fixed as per #230 . Repreviewed this one to be sure

**Comment by phillipadsmith** [comment]
Hi @MrBryan: Doesn't seem fixed to me. With a fix in place, the disclaimer would be **visible** in narrow views, which -- as far as I can tell -- it is not.

**Comment by MrBryan** [comment]
it's there, just at the end of the story which is what I thought it was supposed to do.. scroll wayyyy down

**Comment by alexgreen** [comment]
>  it's there, just at the end of the story which is what I thought it was supposed to do

Yes, that's the spec.

It seems to work with a fact-box here: http://preview.thetyee.ca/News/2016/06/22/BC-Ban-Big-Bucks/

But it's not working with the fact-box--explainer here: http://preview.thetyee.ca/Presents/2016/06/09/Start-Farmers-Market/index.html

@MrBryan can you makes sure every fact-box--explainer is getting marked up at the bottom of the article__body as well as in the aside?

**Comment by MrBryan** [comment]
yes it will wherever the story is repreviewed now -- I hadn't caught that it is there twice until you pointed it out here

**Comment by MrBryan** [comment]
or should be there twice rather

**Comment by phillipadsmith** [comment]
@MrBryan: I'm still not seeing the Presents disclaimer anywhere; do those stories just need a re-preview?

**Comment by MrBryan** [comment]
I'm sorry I kept looking at the other fact box - it is there now!

**Comment by phillipadsmith** [comment]
Guys, this is not fixed:
- The disclaimer is NOT showing on desktop now
- The disclaimer is showing TWICE on mobile views now

**Comment by MrBryan** [comment]
http://preview.thetyee.ca/News/2016/06/22/BC-Ban-Big-Bucks/ fixed just had to repreview

**Comment by MrBryan** [comment]
i'll leave it for you to confirm and close lest I cry wolf again

**Comment by phillipadsmith** [comment]
Fixed!
