### ISSUE TITLE
Date cut off in small viewports

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#265]
<img width="315" alt="iphone_5s_-_iphone_5s___ios_9_3__13e230_" src="https://cloud.githubusercontent.com/assets/34128/16742331/125a8eba-475c-11e6-9ae1-6efb6bd347d9.png">

**Comment by alexgreen** [comment]
This is already fixed in develop. But we also need to get headshots into preview as that will change this object a lot.

**Comment by phillipadsmith** [comment]
>  But we also need to get headshots into preview as that will change this object a lot.

That's on my to-do list :-/

**Comment by MrBryan** [comment]
robyn said she would help rally someone tomorrow if we want

**Comment by phillipadsmith** [comment]
> robyn said she would help rally someone tomorrow if we want

Actually, that would be great.

@robynleighsmith if I show someone how to load contributor photos tomorrow when I'm in, would that someone have time to load about 20-30 of them?

**Comment by robynleighsmith** [comment]
@phillipadsmith Yes, Chris will be in and can do this.

**Comment by phillipadsmith** [comment]
> Yes, Chris will be in and can do this.

👍  ... I'll be in at 10AM

**Comment by alexgreen** [comment]
The date issue is now fixed in preview and we're talking about adding photos to the author-info block so I'll close this issue and open a new one for that: #276
