### ISSUE TITLE
Menu label position on small views

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#266]
@alexgreen I don't remember the menu being in this position before:
<img width="315" alt="iphone_5s_-_iphone_5s___ios_9_3__13e230_" src="https://cloud.githubusercontent.com/assets/34128/16743025/4970e8f6-475f-11e6-9e89-563681a0e5c1.png">

This is on the GitHub pages site, as well as preview. 

Is that the way it's always been?

**Comment by alexgreen** [comment]
I've never seen this. here's how it looks in OSX chrome:

![screen shot 2016-07-11 at 5 30 36 pm](https://cloud.githubusercontent.com/assets/151099/16751318/47ddf30c-478d-11e6-9c06-6772c5a1463e.png)

**Comment by phillipadsmith** [comment]
> I've never seen this. here's how it looks in OSX chrome:

Perhaps, but not how it looks on iOS / mobile Safari.

**Comment by phillipadsmith** [comment]
iPhone 5 viewport size.

**Comment by alexgreen** [comment]
It's fine on android nexus

**Comment by alexgreen** [comment]
I'll have a look. However, I have not done any work on the nav, so I'll be going in blind.

**Comment by phillipadsmith** [comment]
> I'll have a look. However, I have not done any work on the nav, so I'll be going in blind.

Appreciated. 

(Where's the blind emojii!?)

**Comment by alexgreen** [comment]
I think the problem is that the button is wider than the bootstrap column that contains it:

![screen shot 2016-07-12 at 1 22 59 am](https://cloud.githubusercontent.com/assets/151099/16760379/566e333a-47d0-11e6-9d6b-e1a5dcff0f75.png)

**Comment by alexgreen** [comment]
This should fix it: 9fd5360e8d071e37b8b843ad8bbc9f24d2c850d6

**Comment by phillipadsmith** [comment]
> This should fix it

👍

**Comment by alexgreen** [comment]
...so I guess this issue should still be open, pending implementation in bric?

**Comment by MrBryan** [comment]
already implemented, the global nav is in git in bric
