### ISSUE TITLE
Remove "Publications" from both version of the new menu (under "More)

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#267]
<img width="357" alt="please_advise__is_the_world_voting_its_way_to_ruin____the_tyee" src="https://cloud.githubusercontent.com/assets/34128/16747670/f9b3e456-4774-11e6-9dd7-ba4c19cf8af9.png">

**Comment by MrBryan** [comment]
fixed https://github.com/TheTyee/design-article.thetyee.ca/commit/aa64823bf44b464d79bbba00f12350f593cf2f8b#diff-eb11dec8655f31b8465bca96f7ff51baL860

**Comment by phillipadsmith** [comment]
Publications is still in both menus. Please remove when you have a mo'.

**Comment by MrBryan** [comment]
ef5adfd  fixed
