### ISSUE TITLE
Fix Latest Stories block to not pull a square thumb

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#268]
Maybe use Thumbor instead? 

<img width="447" alt="please_advise__is_the_world_voting_its_way_to_ruin____the_tyee" src="https://cloud.githubusercontent.com/assets/34128/16747849/a8bfa1a6-4775-11e6-92b2-cabb0f864dbb.png">

**Comment by MrBryan** [comment]
ok if this doesn't need to go pre-launch I'll wait and do it with thumbor in a few places

**Comment by phillipadsmith** [comment]
This issue is back on preview at least, http://thetyee.ca/Mediacheck/2016/01/25/hiding-faces-610px_square_thumb.jpg

<img width="943" alt="citizens_tell_the_premier__ban_big_bucks__end_party_pay___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/16784209/87bfcf68-483c-11e6-926e-c6ab1d1aed0f.png">

**Comment by MrBryan** [comment]
republished that image seems to have solved. not sure why it didn't publish correctly going to keep an eye

**Comment by MrBryan** [comment]
actually fixed with 2d702d2

**Comment by phillipadsmith** [comment]
Here's my fix (local, will push now as a branch):
<img width="1414" alt="_pennies_for_billions___aboriginals_fight_near_giveaway_of_pipeline_rights_in_1952___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/16823193/17d1b60e-4917-11e6-9f14-b86cc28fa8c4.png">

**Comment by phillipadsmith** [comment]
@MrBryan FYI, https://github.com/TheTyee/design-article.thetyee.ca/tree/feature/fix-square-image-in-latest-stories

**Comment by phillipadsmith** [comment]
I have to admit, I don't understand what relevance / value the width and height (bestWidth and bestHeight variables) served. I've removed them. All seems well.

**Comment by MrBryan** [comment]
I think i did that so that it would use the best image available which sometimes was better than a missing image

**Comment by MrBryan** [comment]
sometimes the story was showing before the image was available

**Comment by phillipadsmith** [comment]
> I think i did that so that it would use the best image available which sometimes was better than a missing image

The width and the height!? Doesn't seem right...

**Comment by phillipadsmith** [comment]
This change avoids thumbs altogether and simply using the largest image as a source to Thumbor.

**Comment by MrBryan** [comment]
in theory it was looping and knocking the images out of contention the closer they were to a certain height and width but yes that sounds better! :P

**Comment by phillipadsmith** [comment]
> in theory it was looping and knocking the images out of contention the closer they were to a certain height and width but yes that sounds better! :P

👍 

Deploy, deploy, deploy!
