### ISSUE TITLE
Interim menu problems

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#269]
So, the interim menu is wonky if you click more, then click search:
<img width="1078" alt="the_tyee___news__culture__solutions_" src="https://cloud.githubusercontent.com/assets/34128/16748200/a2089b4a-4777-11e6-8419-0eb9bb212080.png">

Not a launch-blocking problem, but should get fixed.

**Comment by alexgreen** [comment]
I would say this is launch blocking. We should not launch like this. There's odd background colours throughout the nav:

![screen shot 2016-07-11 at 10 31 59 pm](https://cloud.githubusercontent.com/assets/151099/16756079/6cc55cf8-47b7-11e6-8e2f-99ecdc3d861e.png)

![screen shot 2016-07-11 at 10 32 19 pm](https://cloud.githubusercontent.com/assets/151099/16756078/6cbceb0e-47b7-11e6-8bc5-df8600be84db.png)

**Comment by phillipadsmith** [comment]
Yes, indeed, I discussed earlier with @MrBryan on Skype (see backlog).

**Comment by MrBryan** [comment]
that pictured above is the nav on the new site not the interim but in any case both are now fixed

**Comment by alexgreen** [comment]
> that pictured above is the nav on the new site not the interim

I'm not following. Are there 2 new sites we're currently working on? 
Just to be clear: I have no awareness of this. As far as I'm concerned the develop branch, the gh-pages branch and http://preview.thetyee.ca/ all represent the changes to thetyee.ca that we're trying to launch this week and they should all exhibit exactly the same front end qualities. So I have no idea how I could possibly have been looking at the wrong site when I took that screenshot. Is there another dev site somewhere?

**Comment by alexgreen** [comment]
... unless you're saying that the nav block on the tyee homepage will be generated from a different code base than the nav block on the article pages (i.e. there would be 2 duplicate code bases for the nav block). ?

**Comment by MrBryan** [comment]
yes we have a hacked together interim nav that duplicates the appearance of the new design for non-article pages, if you look at the home page http://preview.thetyee.ca

**Comment by MrBryan** [comment]
(but don't spend any energy on that - phillip was tagging it here just so we'd remember to do that before launch)

**Comment by alexgreen** [comment]
...there's still some critical work to do on that interim nav. #277
