### ISSUE TITLE
Correct presents series block still not being deployed

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#271]
http://preview.thetyee.ca/Presents/2016/05/06/Save-Haida-Language/

Should be like this: http://thetyee.github.io/design-article.thetyee.ca/presents-series

**Comment by MrBryan** [comment]
those are already working  per the previous thread just the include that generates that header has to be done in a bit of a labourious way so only the ones we are actually testing the issue on are done such as in the previous thread for this.  Just did this one too but won't do all of them now http://thetyee.github.io/design-article.thetyee.ca/presents-series

**Comment by MrBryan** [comment]
https://github.com/TheTyee/design-article.thetyee.ca/issues/205
