### ISSUE TITLE
JS to close gap from short feature-media is no longer working

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#272]
http://preview.thetyee.ca/Presents/2016/05/06/Save-Haida-Language/

@MrBryan I remember you had solved this problem with some js magic, but something has broken the spell.

**Comment by alexgreen** [comment]
![screen shot 2016-07-11 at 4 46 09 pm](https://cloud.githubusercontent.com/assets/151099/16750520/3ac367a2-4787-11e6-81f4-b299ea9cb5d5.png)

**Comment by alexgreen** [comment]
...maybe it's just that #219 still needs to be done.

**Comment by MrBryan** [comment]
fixed with bc4dd54

**Comment by MrBryan** [comment]
actually 923153f
