### ISSUE TITLE
Add MEDIA SIZE 4: Full-width featured  media

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#28]

**Comment by kidcompassion** [comment]
I'm sure this is obvious, but if any of these are for me, just add some details and assign it back to me!

**Comment by alexgreen** [comment]
This may not be needed as it's actually very similar to the current media size 3: figure--xl.
It makes more sense to just consider whether to enlarge the figure--xl format.

**Comment by phillipadsmith** [comment]
Anything that needs to be done on this ticket, @alexgreen @kidcompassion ?

**Comment by kidcompassion** [comment]
That is  a question for @alexgreen. I interpreted his comment as meaning he was beautiful mind-ing a solution to this.

**Comment by alexgreen** [comment]
Yes, beautiful mind-ing is in progress. I think we can hold off on this item for now.

**Comment by alexgreen** [comment]
Media size 4: figure--xxl is done. It extends the figure object to be full viewport width. In narrow and medium viewports it's almost identical to the figure--xl, but in large viewports it gets gigantic.

So now editorial has 3 media size options:
- aside (thumbnail)
- figure (normal media block within text column)
- figure--xl (media block that expands out of text column in medium and large views)
- figure--xxl (full viewport width at all screen sizes)

84bca5d45b4652da43579844a410ef3dfda3706c
