### ISSUE TITLE
Deploy nav on Submissions page

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#287]
![img_7088](https://cloud.githubusercontent.com/assets/34128/16813571/fd6779dc-48e6-11e6-9b21-ca2ab1b9d31d.PNG)

@MrBryan Feel free to group these together with a tag saying "Will be okay after re-published" or something.

**Comment by MrBryan** [comment]
Fixed by includes symlink fix
