### ISSUE TITLE
Remove Poll block from bottom of new articles for now

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#290]
We'll bring it back when we've resolve poll-page specific issues

**Comment by MrBryan** [comment]
I already fixed it though.. probably OK to leave as is. Just search & replaced all $ to jQuery

**Comment by MrBryan** [comment]
in the nav js

**Comment by phillipadsmith** [comment]
Yes, but there will be no new (open) poll until we give the word, so probably no point having the teaser there because they can't take the poll! ;-)

**Comment by phillipadsmith** [comment]
Not launch blocking, but something to circle back to.

**Comment by MrBryan** [comment]
Done
