### ISSUE TITLE
Remove "read more" from bios

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#291]
Per Skype conversation:
- Remove the read more, show/hide magic from bios
- Run them (tighten up space beneath!) on wide enough screens
- Hide them on mobile

We'll need to create a new element in Bricolage for funding information and run that at the bottom of the story.

**Comment by alexgreen** [comment]
There's a gap under the bio. Can't see what's causing it. doesn't appear to be css or an html element. maybe something to do with the current hide/show js?

![screen shot 2016-07-13 at 4 16 40 pm](https://cloud.githubusercontent.com/assets/151099/16823055/009f6f2c-4916-11e6-8171-5c3e17466a88.png)

**Comment by MrBryan** [comment]
I can't figure it out either it is puzzling me. Maybe if the page loads having never had an overflow or max height somehow it wont happen

**Comment by MrBryan** [comment]
it was also preventing the read more functionality from working since the div inside the div which was being tested was always 'overflowing' whether there was more text or not it wants to be that tall

**Comment by MrBryan** [comment]
the read more detection that is

**Comment by alexgreen** [comment]
It appears that this css is causing the gap (although I'm not clear on why it would):

```
/* fix date spacing on bric */
 @media screen and (min-width: 600px) {
   .author-info__date {
  margin-left:-4px;
   }
 }
/* end fix */
```

So I've commented it out and that closes the gap.
But now there's a small gap to the right of the author name (presumably what the above rule was supposed to fix) and I have no idea where that comes from.
@MrBryan what causes that small space to the right of the author-name?

**Comment by alexgreen** [comment]
The read-more link is remove, gap is closed, .author-info__text aligns flush left when no headshot is present. 02aed42475809ac4a84619286fc48cd795caf959
