### ISSUE TITLE
Blocker: Broken link from "About Us" in navigation (article page)

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#293]
"About Us" links to:
https://preview.thetyee.ca/Tyeenews/2016/07/13/New-Tyee/About/Us/

Which is a 404.

I think it's missing a / ?

**Comment by MrBryan** [comment]
fixed caught one more same too  af7e362556c6b68a11aa2314f9c37b21605dafac
