### ISSUE TITLE
Interim nav: Search active state looks not-awesome

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#297]
<img width="1089" alt="the_tyee___news__culture__solutions_" src="https://cloud.githubusercontent.com/assets/34128/16829394/d68de8ee-494c-11e6-9b22-7957cd44aec3.png">

**Comment by MrBryan** [comment]
fixed 
![image](https://cloud.githubusercontent.com/assets/1721891/17005990/b65fd262-4eab-11e6-8942-045bbc7c6984.png)
