### ISSUE TITLE
Broken functionality: overflow: hidden on comments is hiding the reply options and more

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#298]
<img width="908" alt="sunny_ways_or_gloomy_days__checking_in_on_liberal_promises___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/16852152/b920d3a6-49bb-11e6-87ad-43d8a7ecf508.png">

**Comment by phillipadsmith** [comment]
Respond to Andrew Henderson when resolved.

**Comment by phillipadsmith** [comment]
To be deployed, @MrBryan, at your next opportunity. Thanks.

**Comment by MrBryan** [comment]
I cherry picked it on preview and it still doesn't seem to expand far enough down still

![image](https://cloud.githubusercontent.com/assets/1721891/16853929/a66d7572-49dc-11e6-9fa3-4698ece6bfcf.png)

**Comment by MrBryan** [comment]
i guess that's less of a big deal though that's only if you try to comment on the last comment

**Comment by MrBryan** [comment]
ooh that's smart -- if you reference the issue in the commit instead of the other way around it shows up on here when I cherry pick it

**Comment by MrBryan** [comment]
p.s alex and i were talking and we were thinking we would keep issues open until they are on production and assign to me if they are awaiting deployment

**Comment by phillipadsmith** [comment]
Can you mark this as closed? :-)

**Comment by MrBryan** [comment]
It's already closed - get some sleep !
