### ISSUE TITLE
New header not deployed on certain list view pages

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#299]
http://thetyee.ca/Archive/weekly/2015/12/28/

**Comment by phillipadsmith** [comment]
http://thetyee.ca/Bios/Phillip_Smith/

**Comment by alexgreen** [comment]
I see  the header now but the fonts are wrong and it's broken on iPad.

**Comment by MrBryan** [comment]
Fixed except on http://thetyee.ca/Bios/Phillip_Smith/ where new easter eggs added

**Comment by MrBryan** [comment]
:)
