### ISSUE TITLE
Subheads aren’t marked up correctly

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#302]
http://thetyee.ca/Culture/2016/07/15/You-Should-Care-About-Pokemon-Go/

Subheads aren’t marked up correctly:

`<p><strong>Augmented reality, but whose reality?</strong></p>
`

should be:

`<h2>Augmented reality, but whose reality?</h2>
`

**Comment by MrBryan** [comment]
All of those "subheads" are just editors manually doing the strong tags within a paragraph element.

I added the subhead element now so it will show, tested in a preview of that story:

http://preview.thetyee.ca/Culture/2016/07/15/You-Should-Care-About-Pokemon-Go/index.html

I can let them know it is an option

**Comment by alexgreen** [comment]
Is it difficult to auto-replace `<p><strong>...</strong></p>` with the correct element?
