### ISSUE TITLE
Adjust spacing within author bios

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#305]
debd93003e944d90ced40b14796f2772355284af

**Comment by alexgreen** [comment]
This is in develop and ready to be deployed.

**Comment by MrBryan** [comment]
i don't see any commits and that link didn't work did you forget to push?

**Comment by MrBryan** [comment]
heads up -- try to pull and merge before you do commit I am reverting a commit now

**Comment by MrBryan** [comment]
actually doesn't matter i reverted on bricmod branches

**Comment by alexgreen** [comment]
Oh sorry, maybe I only pushed the gh-pages branch.
pushed now: debd93003e944d90ced40b14796f2772355284af
