### ISSUE TITLE
++ Header breaking on mobile on some (all?) list view pages 

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#308]
http://thetyee.ca/Bios/Phillip_Smith/
http://thetyee.ca/Archive/weekly/2015/12/28/

View from iPad:

![image](https://cloud.githubusercontent.com/assets/151099/16903670/44b5c104-4c39-11e6-97b5-eea23add44b9.png)

**Comment by MrBryan** [comment]
This was fixed by correcting a symbolic link on the filesystem to stylesheets
