### ISSUE TITLE
Some Series stories don't have a series badge in their article__header

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#313]
eg:
http://preview.thetyee.ca/News/2015/02/23/Four-Sisters-Coop-Profile/

common issue?

**Comment by MrBryan** [comment]
What you were seeing there is just a result of the way the parts are pieced together in bricolage -- the part that shows the series info is added as an include that is generated seperately and that particular one hadn't been done.   This is working on the live version of the site and should be working for all stories when the republishing script finishes

**Comment by alexgreen** [comment]
Some articles still aren't displaying a series badge in their article__header.

http://thetyee.ca/News/2015/02/23/Four-Sisters-Coop-Profile/
