### ISSUE TITLE
Broken thumbnail for related story

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#315]
<img width="331" alt="who_will_listen_to_richard_perry____the_tyee" src="https://cloud.githubusercontent.com/assets/34128/16924724/93826d2c-4cd5-11e6-8216-28143398cb2f.png">
http://thetyee.ca/Mediacheck/2015/04/13/Richard-Perry/

**Comment by MrBryan** [comment]
republished & it fixed -- i think I have those working dependably now on publish / republish
