### ISSUE TITLE
Create print CSS

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#330]
see https://basecamp.com/1929296/projects/9481270/messages/60066584#comment_443149247 
and https://github.com/TheTyee/design-article.thetyee.ca/issues/172

**Comment by MrBryan** [comment]
Here are some pages with the print button & css enabled:
http://preview.thetyee.ca/Culture/2016/08/26/Tunnel-Movie/index.html
http://preview.thetyee.ca/News/2016/08/26/Flourishing-in-a-Not-for-Profit-World/
http://preview.thetyee.ca/News/2016/08/26/Islamophobia-School-Resources/index.html
http://preview.thetyee.ca/News/2016/08/25/RCMP-Arrest-Indigenous-Fish-Farm-Protestors/index.html

The second one has some issues wrt series header - and some other spacing issues. Looks like there may be an error in the bric version html that is resulting in that weird forward slash in the header which I'll have to find.

Let me know what else you may need to get this to a live version, we have gotten two readers writing in about wanting to print articles so would be good to get something up

**Comment by alexgreen** [comment]
As far as I can tell none of those pages are using the print stylesheet I created.
Go to http://thetyee.github.io/design-article.thetyee.ca/library and press `<command-p>` and you'll see what it should look like.
I've also printed pdfs and posted them in the basecamp thread referenced above, but I haven't gotten any feedback from anybody yet.

**Comment by alexgreen** [comment]
... realizing that I didn't create visual print button in the repo, but I see that you've put one in preview already. Can you add that component to the repo so that things stay in sync? thx!

**Comment by MrBryan** [comment]
They are using the print.css that is in develop -- is that not the one you created?   Can you please add it to that branch if not?

![image](https://cloud.githubusercontent.com/assets/1721891/18035269/e7574d1c-6d20-11e6-9d01-5bd135a31b30.png)

And that print button is/was always in the repo, I assumed you selected it as it was from before, I merely un-commented it:  see cb34ed5c43e60ea66782c762e77c458ee84173a0

**Comment by MrBryan** [comment]
Probably you just need to pull so that it will show up.

**Comment by alexgreen** [comment]
Yes the my print.css has been there for over a week. Have you tried running develop locally or going to http://thetyee.github.io/design-article.thetyee.ca/library ? The output is very different than what I get from the preview site.

here's the commit: 421a6284001842f1faa699bee334ad9c4c207f71

![screen shot 2016-08-28 at 4 21 05 pm](https://cloud.githubusercontent.com/assets/151099/18037570/c131a2a6-6d3c-11e6-8593-8f8eafbd2cdc.png)

**Comment by alexgreen** [comment]
Funny that the print icon was there all along. I think I put it in at the beginning but it seemed too 1990s, so I was hoping to convince people to leave it out.

**Comment by MrBryan** [comment]
It was hidden until recently. I think it looks fine, but feel free to swap it for something else if you prefer. Or maybe you mean having a print icon at all is retro. In any case we know that our readers use it. We can monitor more closely and see how many do once it is up. If your print CSS is in the develop repo then the pages you above are in fact ( or should be) using your CSS.

**Comment by alexgreen** [comment]
> Or maybe you mean having a print icon at all is retro.

Yup, that's what I meant. It seems odd to have a button in the page for a function that can already be performed more easily in at least 2 other ways that have been universal across all browsers (and indeed virtually all software applications!) for at least 15 years.
But if there's strong reader demand for it then I suppose that's a good reason to keep the button. ...but this actually another point that might be relevant regarding the nature of the reader demand—I'll address that in the basecamp thread to get input from editorial.

> If your print CSS is in the develop repo then the pages you above are in fact ( or should be) using your CSS.

In my experience they clearly aren't. This can easily be seen by simply printing from github.io and then printing from preview to see the vastly different results. Have you tried? Please print to file from both sources and post the results so I can see what output you're actually getting.

@phillipadsmith are you not seeing a discrepancy in print output between github.io (or develop run locally) and what's currently on preview?

**Comment by MrBryan** [comment]
There is different content but  by looking at the source you can see that they are both loading the same print css, in the same way at the same spot. So we can conclude that this is the effect that this css has on these pages when you print them and there are issues that need to be addressed unless they can be blamed on HTML.

![image](https://cloud.githubusercontent.com/assets/1721891/18071484/31a07098-6e24-11e6-81cb-0ca1807f7e85.png)

![image](https://cloud.githubusercontent.com/assets/1721891/18071493/48badc32-6e24-11e6-89b4-c207ee390d81.png)

**Comment by alexgreen** [comment]
Did you try printing from both sources? Please take 2 minutes and post your results. It would really help to know what you're seeing.

**Comment by alexgreen** [comment]
It's very odd, because I've printed various pages locally and from github.io and they all print correctly. It's only the ones from preview that seem to be leaving out virtually all the styling. So it does seem to be specific to the preview pages, but I don't see why they should render differently.

**Comment by MrBryan** [comment]
i'm on a slow connection at the moment to upload the pdf but yes they look totally different.

Probably have to debug what is happening with the CSS rules:

http://stackoverflow.com/questions/2452713/suggestions-for-debugging-print-stylesheets

**Comment by alexgreen** [comment]
The print.css files are indeed identical, but for some reason the rules not getting applied in preview. I was able to apply the print styles to the preview screen view, so it doesn't appear to be an html issue relating to the structure of the source.

I'll have another look an see if any other difference turns up.

**Comment by alexgreen** [comment]
ok I see the problem.

Preview is missing a declaration in the HTML head that applies article.css to screen AND print media. Many screen styles are used in the print rendering in order to minimize duplication. See screenshot. (It might also work to use a single declaration with a "screen and print" boolean but I haven't tried.)

So if you add that declaration to the preview html head this problem should be fixed. (I hope.) Although I'm seeing one or 2 issues arising from the differences between the codebase on preview and the one in the repo, but that should be an easy fix.

![screen shot 2016-08-29 at 5 56 51 pm](https://cloud.githubusercontent.com/assets/151099/18072463/59ceb568-6e13-11e6-9a54-06f878e25fb8.png)

**Comment by MrBryan** [comment]
Unfortunately no dice for the first way -- same issue.  Combining them into "media and print" breaks the layout altogether.

**Comment by alexgreen** [comment]
Good, that does indeed solve almost all the print layout issues. 

But the update is inconsistently applied to the stories identified (at top of this thread).
The correct stylesheet links appear in:
http://preview.thetyee.ca/Culture/2016/08/26/Tunnel-Movie/index.html
http://preview.thetyee.ca/News/2016/08/26/Islamophobia-School-Resources/index.html
But they're still wrong in:
http://preview.thetyee.ca/News/2016/08/26/Flourishing-in-a-Not-for-Profit-World/
http://preview.thetyee.ca/News/2016/08/26/Islamophobia-School-Resources/index.html

Can refresh these latter 2 preview stories? Then I can check out the other print issues.

**Comment by MrBryan** [comment]
OK I repreviewed those

**Comment by phillipadsmith** [comment]
These are looking great, Gents.

Few comments:
- There's a (/) beside the logo and a similar URL fragment beside the category slug, author name, series badge, and topic links at the bottom. Thoughts on the usefulness of those?
- "Latest stories" is appearing at the bottom. Probably best to remove?
- Dropcap seems incorrectly positioned on the series story by Justin Richie

**Comment by MrBryan** [comment]
Ah yes thinking about this I realized why the forward slash is there and not on develop: because the logo links to home on bricmod branch so it shows the link address

**Comment by MrBryan** [comment]
![image](https://cloud.githubusercontent.com/assets/1721891/18184127/877a0ff4-7065-11e6-8cf3-37304ccb7052.png)

**Comment by phillipadsmith** [comment]
> Ah yes thinking about this I realized why the forward slash is there and not on develop: because the logo links to home on bricmod branch so it shows the link address

Resolution?

**Comment by MrBryan** [comment]
Alex asked for feedback and we gave some, what is next @alexgreen ?

**Comment by phillipadsmith** [comment]
> Alex asked for feedback and we gave some,

Miscommunication: I was asking, what is the resolution for the forward slash issue?

**Comment by MrBryan** [comment]
Oh I don't know -- that has something to do with whatever causes every link to display on the page, so no miscommunication I was saying that's part of the feedback for alex

**Comment by phillipadsmith** [comment]
> Oh I don't know -- that has something to do with whatever causes every link to display on the page, so no miscommunication I was saying that's part of the feedback for alex

👍

**Comment by alexgreen** [comment]
> There's a (/) beside the logo and a similar URL fragment beside the category slug, author name, series badge, and topic links at the bottom. Thoughts on the usefulness of those?

I'll take a look at suppressing those with CSS as they don't appear in the repo.

> "Latest stories" is appearing at the bottom. Probably best to remove?

Yes it shouldn't be there. This is also a difference between the repo and preview/live as that label doesn't exist in the repo version (although it should). I think the problem must be that the label is sitting outside the html latest-stories object and thus even though the object is hidden by CSS the label isn't within its scope. So probably the label should be included within the actual object.

> Dropcap seems incorrectly positioned on the series story by Justin Richie

I don't see a positioning issue. Can you print to file and post?

**Comment by phillipadsmith** [comment]
> I don't see a positioning issue. Can you print to file and post?

You're right. I'm not seeing it now either. Must have been an anomaly.

**Comment by alexgreen** [comment]
All print css issues should be fixed in the repo now: 325b67f8ce7a99c9c594c6c54186c03efe00e20a
Please deploy to preview.

**Comment by MrBryan** [comment]
This is deployed - there are a few tweaks to catch like videos which should be hidden 

http://thetyee.ca/News/2016/09/12/Forest-Parkour-BC/

and the widescreen fix was doing something wonky so the position will have to be overridden and fixed for print.. can't find an immediate example but probably just going through stories and trying the print button now that its there you'll find some more small things

**Comment by alexgreen** [comment]
> there are a few tweaks to catch like videos which should be hidden

Can you add your tweaks to the repo? I'm not seeing any commits related to it.

**Comment by alexgreen** [comment]
> the widescreen fix was doing something wonky so the position will have to be overridden and fixed for print

What do you mean by "widescreen fix"? Can you be more specific? I haven't come across anything that sounds like what you're talking about.

But I did fix a few other things:
b955b18f22835b2da21f2107b8cf0e5143bd8086

...oh, do you mean the js fix that ads a negative margin when featured-media is shorter than 600px? The above fixes do deal with that, but the js also seems to be causing some issues that I've described here: JS margin is breaking layout on live site in Chrome · Issue #350

**Comment by MrBryan** [comment]
Yes that's what i meant . that other issue is fixed.

The videos are still printing a big empty box, don't think we want that:

![image](https://cloud.githubusercontent.com/assets/1721891/18652926/15ff0198-7e8b-11e6-86d0-99f8d90c36d7.png)

**Comment by alexgreen** [comment]
The videos are still printing a big empty box
Yeah browser print rendering of these elements varies a lot, so I've hidden the players and put in a grey labeled block: d9ee0d45031694996373ca484a607a1944b2a79d

Seems to print consistently across osx browsers.

![screen shot 2016-09-21 at 11 35 18 pm](https://cloud.githubusercontent.com/assets/151099/18738832/1a73b9ba-8054-11e6-89c3-38ef3125deca.png)

**Comment by alexgreen** [comment]
As far as I know that's the last remaining issue with the print css. But lmk if there's anything else.

**Comment by MrBryan** [comment]
deployed
