### ISSUE TITLE
tweets often have images from different articles?

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#331]
Reported by Hugh Stimson:
https://twitter.com/hughstimson/status/763246036517199872 

![image](https://cloud.githubusercontent.com/assets/34128/17542929/b363d744-5e81-11e6-9c3e-adff406349fd.png)

While we're investigating, we should also remove '| The Tyee' from what Twitter is sharing because it looks odd to have that and 'via @TheTyee' in the tweet.

cc @robynleighsmith

**Comment by robynleighsmith** [comment]
Hm, that could be human error? I'll let Chris know. Yes to the '| The Tyee' point.

**Comment by MrBryan** [comment]
Not sure how it could have happened unless the story was initially published with the wrong image and the twitter scraper hit the page.  Probably a good exercise whenever publishing would be to hit the share button and make sure it looks right

**Comment by MrBryan** [comment]
and sure, can parse out " | The Tyee "

**Comment by MrBryan** [comment]
will create separate issue for the " | The Tyee "
