### ISSUE TITLE
Reconcile the Share icon and Heart icon from Bricolage to GitHub

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#336]
<img width="545" alt="perfect_storm _engulfing_canada s_economy_perfectly_predictable___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/17608279/4266b66e-5fe0-11e6-933b-1eaec5b298b3.png">

**Comment by MrBryan** [comment]
Done!

**Comment by MrBryan** [comment]
https://github.com/TheTyee/design-article.thetyee.ca/commit/ef5966c151ea023b77fc11fd99d796832fe49705

https://github.com/TheTyee/design-article.thetyee.ca/commit/98e6f665613e4bdbcd847356e8680f247667acc6
