### ISSUE TITLE
Implement a comment count functionality on article page

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#337]
https://basecamp.com/1929296/projects/10634215/todos/266293077

First pass:
<img width="891" alt="perfect_storm _engulfing_canada s_economy_perfectly_predictable___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/17608380/051801b8-5fe1-11e6-9970-abf9ac88784b.png">

cc @robynleighsmith

**Comment by phillipadsmith** [comment]
Small screen mobile:
<img width="386" alt="perfect_storm _engulfing_canada s_economy_perfectly_predictable___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/17608458/79009b3a-5fe1-11e6-98d2-52e2d3e61e2e.png">

**Comment by robynleighsmith** [comment]
That looks great to me, Phillip.

**Comment by phillipadsmith** [comment]
New mobile treatment to avoid line breaks:
<img width="331" alt="perfect_storm _engulfing_canada s_economy_perfectly_predictable___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/17609320/ae55ae9a-5fe8-11e6-915c-f2ca8f3add8c.png">

**Comment by phillipadsmith** [comment]
Ready for testing and deployment:
https://github.com/TheTyee/design-article.thetyee.ca/tree/feature/comment-count

Merged into 'develop' also.

**Comment by phillipadsmith** [comment]
There is something still to figure out, however:

The way that Disqus' JS determines where to put the comment count data is by looking for an anchor tag with a hash fragment of '#disqus_thread'  ... 

But, for some reason, that hash fragment is not firing as it should when the link is clicked. I'm wondering if it has something to do with the JS that jumps the user down to the comments, and opens them up, when the comment bubble is clicked? Guessing so... these two might need to be reconciled to work together. 

Over to you, @MrBryan. :-)

**Comment by MrBryan** [comment]
It's mainly because it was looking for #comments rather than #disqus_thread  but the comments text and icon were different so targeted them both now

f3ce68d

**Comment by robynleighsmith** [comment]
@MrBryan @phillipadsmith Looks good, guys!
