### ISSUE TITLE
Need to add "funder attribution" 

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#341]
From Robyn

> At some point we need to add a Bricolage field for "funder attribution or other additional credits." This has traditionally been added to the "bio" field, but now that we're trying to keep those short, we need a long-term solution for how to ensure funder attribution is prominent.

Basecamp:
https://basecamp.com/1929296/projects/10634215

@alexgreen Can you take a first pass at considering where this attribution should appear and how?

**Comment by MrBryan** [comment]
Bump, monsieur @alexgreen

**Comment by alexgreen** [comment]
Should I promote this to top priority? I will have time on Sunday

**Comment by MrBryan** [comment]
Depends whats in the queue ahead of it? just noticing that it was in the schedule for august

**Comment by alexgreen** [comment]
not so much actually
https://github.com/TheTyee/design-article.thetyee.ca/issues?q=is%3Aopen+is%3Aissue+assignee%3Aalexgreen+label%3A%22Priority%3A+High%22

**Comment by MrBryan** [comment]
we're going to just use the author bio field for now so let's close this

**Comment by alexgreen** [comment]
Is there a response upcoming in the basecamp thread?
