### ISSUE TITLE
Size of thumbs in Latest Stories block

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#345]
Curious what's causing these minor anomalies: 
<img width="736" alt="fentanyl_crackdown_could_bring_deadlier_drugs__says_expert___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/18184854/af99b7fc-704f-11e6-8af0-ceeba4cf57a9.png">

**Comment by MrBryan** [comment]
It's the smart cropping detecting how long and skinny eels are

**Comment by MrBryan** [comment]
Tee hee.  OK actually it's the code that tries to find the best image fit not quite landing on the right one, I will add a line to prefer the "latest" thumbnail when it's available (it goes through the others in case the image isn't published yet)

**Comment by MrBryan** [comment]
Fixed this by preferring the latest thumb when it is available, then running the next best image code only if it isn't there

https://github.com/TheTyee/design-article.thetyee.ca/commit/f60bf60e52a0017793e3554629aa8e5d0b498f25
