### ISSUE TITLE
Deploy update to e-mail subscription form structure and JavaScript

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#346]
Hey @MrBryan,

I've moved the e-mail subscription form JS into `article_custom.js` and I've updated the include that contains the forms to match the HTML on the site.

I'd like to do another update so that code automatically uses the correct version of the webhook app, depending on context -- local, preview, or live -- but I'm going to leave that for the moment.

Please see this branch for the changes:
https://github.com/TheTyee/design-article.thetyee.ca/commits/feature/fix-email-subscription-form

So, the changes would be:
- [ ] Remove the inline JS that is deployed live currently and instead use this updated version of the article_custom.js file
- [ ] Merge my changes to the HTML into what's live, which adds some error messaging support as well as more obvious success messaging, and also adds a class to the e-mail input, which is needed for some automated testing.

Let me know if you have any questions,

Phillip.

P.S. Let's make a note to loop back to a discussion/documentation of how the whole site is wired together now. I was stumped for about an hour on getting these changes made because the HTML structure in the GitHub repo for this section does not match what's live on the site, which makes doing work in the usual workflow quite difficult. Probably an artifact of our launch-related deadlines and last-minute juggling ... but going forward it's important that everything stay in sync as closely as possible, or at least get documented as not being in sync (in the GitHub code), because otherwise figuring that out is going to cost someone some time down the road.

**Comment by MrBryan** [comment]
OK I removed it.

I'll try to make sure any of my changes are backported to develop repo when I test the changes on preview.thetyee.ca/bc-bricmod

**Comment by MrBryan** [comment]
removed the inline  html that is, and tested it preview+live and it works
