### ISSUE TITLE
latest-stories object -- reconcile differences between repo and the live site

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#347]
live site and repo currently have different html for this object

**Comment by MrBryan** [comment]
I did a diff and I see some comments are removed but what are you noticing that has a consequence?

**Comment by alexgreen** [comment]
Can't remember exactly what I meant but there's a couple differences I see right off. 

In the live version each media item is wrapped in a `<a>` (header version only?) but not in the repo (here the links are within each div).

LIVE:
![screen shot 2016-09-13 at 4 56 22 pm](https://cloud.githubusercontent.com/assets/151099/18495591/223abce2-79d4-11e6-9dd1-40194dbc303b.png)

REPO:
![screen shot 2016-09-13 at 4 57 13 pm](https://cloud.githubusercontent.com/assets/151099/18495590/223a5cfc-79d4-11e6-92c5-cfa557a0055a.png)

Oddly there's also differences in the CSS.

LIVE:

```
#latest_bottom_wrap {
    border-bottom: 1px #929292 solid;
    padding: 10px 0;
    margin: 40px 0;
}
```

REPO:

```
#latest_bottom_wrap {
    border-top: 1px #929292 solid;
    border-bottom: 1px #929292 solid;
    padding: 10px 0;
    margin: 40px 0;
}
```

Not sure if there's other differences.

**Comment by MrBryan** [comment]
Got the HTML differences sorted here

72724c6 

and css here (removed top border from develop -- looks better sans)

7dc28a436f9d0058e7753b2e94af6a7ffa8a8794
