### ISSUE TITLE
Words floating out of column in Firefox

### ISSUE THREAD

**Issue by MrBryan** [TheTyee/design-article.thetyee.ca#349]
![image](https://cloud.githubusercontent.com/assets/1721891/18322003/7fb500a6-74fe-11e6-850c-69719735c94c.png)

That happens at larger widths on stories in Firefox

This screenshot was from http://www.thetyee.ca/Culture/2016/09/07/Killer-Whale-Who-Changed-World/

**Comment by MrBryan** [comment]
Any suggestions, Alex?

**Comment by alexgreen** [comment]
I pushed a fix for this: b5f1b3af38ce0d24ed90d5f66a3ab10778e39e7a

It removes the float from bigbox ads and adds an overflow:auto to prevent collision with the XL and XXL figures. Seems to work in all my local browsers and it also has the advantage of preventing the ads from straying away from where they're actually marked up in the html.

The floats are pretty fussy so we should do some testing in preview before deploying publicly.

**Comment by MrBryan** [comment]
Seems to work on FF & chrome wherever I tested it , it's live now

**Comment by alexgreen** [comment]
(^_^)b
Thanks! Glad we've got a solution that keeps the elements in order and also provides more control to editorial.
