### ISSUE TITLE
JS margin is breaking layout on live site in Chrome

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#350]
http://thetyee.ca/News/2016/09/12/Forest-Parkour-BC/

There's something forcing the page to be wider than the viewport causing horizontal scrolling at all viewport widths. This occurs on Chrome OSX desktop, but I'm not seeing this on mobile, nor am I seeing this occur in OSX firefox or safari. See attached screenshots.

It seems to be caused by this negative margin which is applied by js when the featured-media object is shorter than the featured ad:

`<section class="featured-media" data-dev-object-descrip="02-organisms/article/featured-media" style="margin-bottom: -126px;">
`

I have no idea why this would affect the width of any container, but when I remove the margin the problem disappears, so it seems related.

@phillipadsmith @MrBryan are you also seeing this?

![screen shot 2016-09-12 at 9 30 12 pm](https://cloud.githubusercontent.com/assets/151099/18461885/b0b1fd52-7932-11e6-9cf8-d2af5478bb1b.png)

![screen shot 2016-09-12 at 9 30 59 pm](https://cloud.githubusercontent.com/assets/151099/18461884/b0affaa2-7932-11e6-9cf3-644c1b00926c.png)

**Comment by MrBryan** [comment]
I can scroll slightly horizontally at 1200+px but when i do $("*").css("border", "1px solid red");  nothing shows up outside the body/html bounds so I'm not sure what's causing it.  Luckily it's pretty inconsequential for the ux so I don't think it's actually high priority unless you're seeing other effects

**Comment by MrBryan** [comment]
body {overflow-x:hidden  } fixes it

**Comment by MrBryan** [comment]
i'll just do that for now as there is no point at which we want horizontal scrolling as far as I can think

**Comment by MrBryan** [comment]
431dbd8 fixed
