### ISSUE TITLE
Tyee Presents styling is inconsistent in Latest Stories

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#353]
Sometimes it appears, sometimes not. Especially when I click past it and then reverse back to it the styling is always missing.

![screen shot 2016-09-29 at 9 42 16 pm](https://cloud.githubusercontent.com/assets/151099/18980930/41b3ba44-868e-11e6-9672-3cd51bca102b.png)
![screen shot 2016-09-29 at 9 42 06 pm](https://cloud.githubusercontent.com/assets/151099/18980927/3fb83990-868e-11e6-8a54-634a73c5db8e.png)

**Comment by MrBryan** [comment]
nice catch - fixed that with a commit.. haven't deployed yet as I'm looking at a bigger fix or possibly rewrite of that scroller.  What it does is loads placeholders, then when you click on next it goes and ajax replaces each element in each placeholder through a bunch of complex functions and it has bugs (if you click previous a few times it will fail for a few clicks until all the odd number of stories per scroll are balanced out) that are complicated to fix.

I think it would be better to just load the stories in a long list then the next and previous buttons reveal the content by adjusting its position within the viewing area like normal scrolls. Or make use of a plugin that makes that shorter.

**Comment by MrBryan** [comment]
possibly sally was doing it this way to keep the initial load low but with the smaller thumbnails this shouldn't be an issue and I think the pagespeed extension will handle this, too

**Comment by MrBryan** [comment]
Fixed

**Comment by alexgreen** [comment]
> I think it would be better to just load the stories in a long list then the next and previous buttons reveal the content by adjusting its position within the viewing area like normal scrolls. 

I agree. It would also make it functional on medium touch screens views (e.g. ipads which don't allow any scrolling of Latest Stories).

> possibly sally was doing it this way to keep the initial load low but with the smaller thumbnails this shouldn't be an issue and I think the pagespeed extension will handle this, too

Yes this is why she did it.
