### ISSUE TITLE
Homepage nav broken on ipad

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#354]
Here's a screenshot from ipad mini Safair.
I can't reproduce this issue on desktop Safari.

![3bfb707d-5fd6-4908-8341-e2cb04a4181e](https://cloud.githubusercontent.com/assets/151099/19062771/b4827526-89b1-11e6-8b21-deea8a3c5fb8.PNG)

**Comment by alexgreen** [comment]
I see the same problem on ipad mini Chrome.
Seems to affect all index pages.

**Comment by alexgreen** [comment]
Also seeing it on the Xcode ipad simulator

**Comment by MrBryan** [comment]
dupe -- fixed
