### ISSUE TITLE
Fix existing embeds

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#356]
E.g., http://thetyee.ca/News/2014/07/14/Sanctuary-City-Timeline/

Seems like a jQuery plugin is missing or something. I'll investigate, along with the other embeds.

cc @MrBryan

**Comment by MrBryan** [comment]
interesting it seems to break jQuery much like Wufoo, maybe I've been blaming them when there is some third javascript somewhere in common that is causing the issue for both

**Comment by phillipadsmith** [comment]
> interesting it seems to break jQuery much like Wufoo, maybe I've been blaming them when there is some third javascript somewhere in common that is causing the issue for both

I'll dig into it a bit today and see if there's anything obvious...

**Comment by phillipadsmith** [comment]
Current resolution is here / awaiting input:
https://github.com/TheTyee/design-article.thetyee.ca/issues/359

**Comment by phillipadsmith** [comment]
I'll leave this open because I'll need to manually update some of the embed code for existing timelines....
