### ISSUE TITLE
Modal popover for builder - bring into this repo

### ISSUE THREAD

**Issue by MrBryan** [TheTyee/design-article.thetyee.ca#362]
Jeanette sent me the builder popover as an attachment so it has all its own libraries and js/css  - Can you please do it in our github repo with the new article so that the styles etc will be integrated + not two copies of bootstrap styles etc?  Probably makes more sense since you were just working on it rather than my reverse engineering

Currently  02-organisms/sections/subscription-modal.html is where our existing one is and the code that operates it is in article_subscription_popup.js 

you can add a condition that is always true to test the modal popup in that js --

      if ( elapsed > 604800000) {

to become

      if ( elapsed > 604800000 | 1 < 2 ) {

Then it will show on page load whenever you are in an incognito window

**Comment by alexgreen** [comment]
> if ( elapsed > 604800000 | 1 < 2 ) {

This doesn't work. The popup doesn't show. I'll have to table this until I can see the popup.

Phillip do you have any idea how we can make the popup appear?

**Comment by MrBryan** [comment]
Were you in an incognito window ? that part is crucial because you'll have cookies that won't let it get that far

**Comment by MrBryan** [comment]
just tested again myself, works every time for me

**Comment by alexgreen** [comment]
Yes I tried it several times incognito with different conditionals. Can you
set up a branch that works so i can pull it?

**Comment by MrBryan** [comment]
Very odd -- should have worked.  Before we go that route how about just paste            

` window.setTimeout(showPopup, 0);`



around line 121 so just before 

```
function hideModal() {
    jQuery('#modalSub').modal('hide')
}

```

That should be fool proof and work whether or not incognito

**Comment by MrBryan** [comment]
Don't commit that change, of course

**Comment by alexgreen** [comment]
Still doesn't work. Which page in the repo are you viewing when you see the modal appear?
There is no instance of "modalSub" on the repo index page, so it seems like there's nothing for the js to show.

**Comment by alexgreen** [comment]
i.e. I don't think the modal include is actually being called when repo pages are generated. unless there's a specific repo page you've set up where the include is used.

**Comment by alexgreen** [comment]
Oh it doesn't get called in article-standard, but it does seem to get called in article and most other layouts. So that means it should appear on the library page which is one of the pages I've tested and the modal doesn't show up there.

...wouldn't hurt to include the modal within footer.html rather than separately in every different layout.

**Comment by alexgreen** [comment]
ha! looks like article_subscription_popup.js isn't actually being deployed by jekyll in the develop branch. Can you push all your commits that are relevant to the modal? And any other commits you haven't pushed.

**Comment by MrBryan** [comment]
ah.. you're right. Sorry ,I forgot I did that on article-standard layout in my local environment

**Comment by MrBryan** [comment]
sure we can add to the footer one instead

**Comment by alexgreen** [comment]
ok, please make sure everything's in place. I have to do some other stuff for jeanette and won't get back to this until later.

**Comment by MrBryan** [comment]
ok just added it to footer.html affd731

**Comment by MrBryan** [comment]
removed from the other layouts too b9f427d

**Comment by MrBryan** [comment]
+added to meta

**Comment by alexgreen** [comment]
cool. and that js file is getting deployed now?

**Comment by MrBryan** [comment]
it's in the head.html

**Comment by MrBryan** [comment]
so yes should be in that commit too

**Comment by alexgreen** [comment]
works now, thanks

**Comment by alexgreen** [comment]
I merged the builder-modal branch into develop and it's in the repo now.

It's working on OSX chrome at all viewport sizes and iPad. But for some reason the modal doesn't appear on my android chrome. Not sure if that's specific to me so please test with whatever devices you have on hand.

**Comment by MrBryan** [comment]
yes disabled on android and iphone, too annoying

**Comment by alexgreen** [comment]
Are phone browsers designed to prevent modals? Wouldn't that mean that any js-based showing and hiding of content is impossible? That seems crazy. It also seems odd that IOS would allow modals on tablets but not on phones.

**Comment by MrBryan** [comment]
No it's by design on our end

**Comment by MrBryan** [comment]
We decided it was too hard to close the little model screen and who is going to want to sit and fill out a form anyways on their phone

**Comment by MrBryan** [comment]
deployed

**Comment by alexgreen** [comment]
filling out a form on mobile is a high bar. But there's ways around it: google pay, apple pay, paypal 1-click payments (assuming this exists). (This also relates to the reader micro-payments discussion I seeded a few weeks ago, so hopefully we'll have an update on that soon too.)

Or the mobile popup might deliver completely different functionality. e.g. single click to post "I support The Tyee" on FB, twitter, etc.

**Comment by MrBryan** [comment]
Good points - we do get a not insignificant number of donations on mobile already so anything that make it easier is a good idea.  We use a service called recurly for all of our payments at the moment so it would involve a fairly big add on but possibly worth it or wait until apple/google pay are  ready on recurly https://blog.recurly.com/recurly-to-support-apple-pay-on-the-web
