### ISSUE TITLE
Builder modal not working on android?

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#363]
It's working on OSX chrome at all viewport sizes and iPad. But for some reason the modal doesn't appear on my android chrome. Not sure if that's specific to me so please test with whatever devices you have on hand.

**Comment by MrBryan** [comment]
this is intentional

**Comment by MrBryan** [comment]
( just found it's annoying to get popups on small devices)

**Comment by alexgreen** [comment]
I find that a 1-time pop-up isn't a big deal for a once-a-year campaign from a not-for-profit organization. But obviously the lack of mobile popup didn't impede reaching our goal, so no harm done I guess.
