### ISSUE TITLE
Homepage nav layout is broken in tablet view

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#364]
Seems like this problem has returned. Screenshot from iPad mini 3 attached.
I think it's just a matter of setting the nav to collapse at a slightly higher breakpoint.

![photo 2016-11-24 6 11 54 pm](https://cloud.githubusercontent.com/assets/151099/20613450/e97eb8da-b278-11e6-966a-91ccffedb6dd.png)

**Comment by alexgreen** [comment]
I'm not able to reproduce this in OSX Chrome.

**Comment by MrBryan** [comment]
Fixed by shrinking font to 12px under 900 pixels
