### ISSUE TITLE
Gappy homepage layout bug on tablet

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#365]
Blocks seem to be assembled haphazardly with large gaps and little vertical alignment. Screenshot from iPad Mini 3.

![photo 2016-11-24 6 12 36 pm](https://cloud.githubusercontent.com/assets/151099/20613486/537042cc-b279-11e6-805f-a5a5e42712e7.png)

**Comment by alexgreen** [comment]
Can also be reproduced in OSX Chrome at many view widths.

![screen shot 2016-11-24 at 7 11 05 pm](https://cloud.githubusercontent.com/assets/151099/20613531/dcf680f6-b279-11e6-82cb-6e68437c9979.png)

**Comment by MrBryan** [comment]
This was just the interim collapsable layout we grafted on for the interim on the home page and section pages that use the old layout so that we'd have something semi-responsive.  We are not going to spend any more energy on it and focus on getting the section & home redesigned ASAP instead
