### ISSUE TITLE
Banner ads not showing on article pages 

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#367]
... Despite multiple refreshing. Issue on nexus phone and on iPad mini. 
But the banner ads DO up on the home page (but only on iPad and only in landscape vote). 
![image](https://cloud.githubusercontent.com/assets/151099/21023833/0e0239ca-bd37-11e6-9f41-037ea78b2c03.png)

![image](https://cloud.githubusercontent.com/assets/151099/21024262/9ddd07b8-bd38-11e6-9c89-ce5f3bdf6aeb.png)

**Comment by MrBryan** [comment]
This was set in the ad loading settings  (code wrapped by addSize() ) - i moved the minimum down to 727 pixels which i believe those devices viewports are and that make them visible.
