### ISSUE TITLE
Comment section -- disqus breaks layout

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#37]
- [x] Add the disqus code into this section, without the extra cruft in the default code.
- [x] Style the comments block in all views.

**Comment by phillipadsmith** [comment]
@kidcompassion @alexgreen Would it be helpful if I worked on this issue?

**Comment by alexgreen** [comment]
This ball is in @kidcompassion 's court but that sounds good to me.

**Comment by kidcompassion** [comment]
That would be awesome, @phillipadsmith! I had just plugged in Disqus' dummy code, but it appends a lot of extra junk. I'm not sure how to populate it with anything else, so even if you could find a way to plug in some actual comments, that's be great. I can style the rest.

**Comment by phillipadsmith** [comment]
Here's a preliminary attempt that obscures the comment section at a reasonable height and presents a button to display the full thread. 

Open to ideas on how to improve this.

<img width="672" alt="localhost_4000" src="https://cloud.githubusercontent.com/assets/34128/14057647/37fd246c-f2c4-11e5-9689-9ddc991a7c18.png">

**Comment by phillipadsmith** [comment]
Here it is without a featured comment:

<img width="704" alt="localhost_4000" src="https://cloud.githubusercontent.com/assets/34128/14057672/f0662152-f2c4-11e5-93d2-fdbd4bce5b29.png">

And on smaller screens:
<img width="374" alt="iphone_6s_-_iphone_6s___ios_9_2__13c75_" src="https://cloud.githubusercontent.com/assets/34128/14057788/c68a84b0-f2c7-11e5-93f9-7043f3ee1826.png">

**Comment by phillipadsmith** [comment]
That's all in the develop branch now.

**Comment by alexgreen** [comment]
Looks good to me, but I would fade to white rather than grey. That way it will blend into layout more.

It's missing a right margin. Is it breaking the bootstrap container?

**Comment by phillipadsmith** [comment]
Tell me more about the margin, as I'm not intimately familiar with how you've been building things. Pretend I know nothing! :-)

**Comment by alexgreen** [comment]
Sorry, I may have been mislead by that screenshot. might be no problem. I'll have to pull the branch and test in browser.

**Comment by phillipadsmith** [comment]
> Sorry, I may have been mislead by that screenshot. might be no problem. I'll have to pull the branch and test in browser.

Yes, indeed, probably best if you do that in general to ensure we're staying efficient and not making unnecessary work for one another. ;-)

That's the whole idea of Git, to be honest. You can simply "stash" your current work, and then switch to another branch to review those changes and provide input. 

When you're done, you can simply switch back to your own branch and apply the stash and you're back to where you were moments before. 

Let me know if you have any questions on the process.

Phillip.

**Comment by alexgreen** [comment]
> When you're done, you can simply switch back to your own branch and apply the stash and you're back to where you were moments before.

True. But I have a couple dozen files open in Sublime Text that will live update when I switch branches, and I have a vague fear that if one of those files doesn't exist in the branch I switch into then something maybe SB will freak out and something might get corrupted. But maybe I'm just being superstitious.

**Comment by phillipadsmith** [comment]
> True. But I have a couple dozen files open in Sublime Text that will live update when I switch branches, and I have a vague fear that if one of those files doesn't exist in the branch I switch into then something maybe SB will freak out and something might get corrupted. But maybe I'm just being superstitious.

I don't use Sublime, so I have no first-hand experience.

The editor I use handles this scenario just fine. If files I have open disappear, I get a notification that they're gone. Files that are different just update. 

Regardless, if you're latest work is saved in your editor and you've either committed or stashed that work in Git, then there's nothing to fear. You might lose your undo history for a file, but your latest changes won't be lost. And, frankly, if you're making atomic commits then your undo history in your editor is moot because there will be Git commits to revert to if necessary to go back in time. That's the whole idea. ;-)

**Comment by alexgreen** [comment]
> Tell me more about the margin, as I'm not intimately familiar with how you've been building things. Pretend I know nothing! :-)

The comments module should align with the main text column of the page (as shown by the blue lines in the screen shots attached). Currently the alignment and sizing of the comments seems a bit erratic.

Currently article__body and messaging-zone are containers that are styled to align with this column, but I'll abstract a universal layout container that can be used to house any object that needs to align with the main text column.

![comments too wide](https://cloud.githubusercontent.com/assets/151099/14064976/da9a6534-f451-11e5-8995-3781924395e2.png)

![comments not aligned](https://cloud.githubusercontent.com/assets/151099/14064977/da9e4708-f451-11e5-8a92-dfa12802c2f1.png)

**Comment by alexgreen** [comment]
> I'll abstract a universal layout container that can be used to house any object that needs to align with the main text column.

I've abstracted the main text column positioning styles into the class .main-col-container.
So you can apply .main-col-container to any direct descendent of _body_ that should conform to the main text column dimensions and alignment.

**Comment by phillipadsmith** [comment]
> So you can apply .main-col-container to any direct descendent of body that should conform to the main text column dimensions and alignment.

I'll give that a try for the comments block.

**Comment by phillipadsmith** [comment]
> So you can apply .main-col-container to any direct descendent of body that should conform to the main text column dimensions and alignment.

Yep, that works.

<img width="702" alt="localhost_4000" src="https://cloud.githubusercontent.com/assets/34128/14067961/464ae19c-f429-11e5-8118-c0c5d9a2e7ad.png">

<img width="686" alt="localhost_4000" src="https://cloud.githubusercontent.com/assets/34128/14067966/64e90e80-f429-11e5-881c-0b5ffbd6d968.png">

**Comment by alexgreen** [comment]
Since you're not using any bootstrap container class you'll need to add 15px of left and right padding to get it to align exactly with the other column containers. Or you can add a .container-fluid class to it (as the other containers employ).

**Comment by phillipadsmith** [comment]
Hi @alexgreen: Not totally following. The whole Disqus widget is already inside a .container-fluid ... so I'm not quite sure what you're asking for here? Can you clarify?

<img width="860" alt="comments_html____development_design-article_thetyee_ca__includes_02-organisms_sections__-_vim" src="https://cloud.githubusercontent.com/assets/34128/14089106/f4e61f82-f4e7-11e5-8120-be245ba05599.png">

**Comment by alexgreen** [comment]
The _.main-col-container_ needs to be outside _.container-fluid_. (Or if they're both applied to the same tag that might possibly work too—not sure. But _.main-col-container_ inside of _.container-fluid_ won't currently work. I realize this order is unconventional in terms of how layout frameworks are usually employed.)

 ...to be honest I'm feeling that bootstrap isn't really serving any purpose within the main text column elements and should probably be omitted from them entirely, but that's probably a refactoring task best left for another day. However, if you think now is an opportune time in the workflow for refactoring lmk and I'll have at it.

**Comment by phillipadsmith** [comment]
> The .main-col-container needs to be outside .container-fluid. (Or if they're both applied to the same tag that might possibly work too—not sure. But .main-col-container inside of .container-fluid won't currently work. I realize this order is unconventional in terms of how layout frameworks are usually employed.)

No worries. I'll swap. I'm just not familiar enough with the templates yet to guess at such things.

> but that's probably a refactoring task best left for another day. However, if you think now is an opportune time in the workflow for refactoring lmk and I'll have at it.

Another time, I would propose.
