### ISSUE TITLE
How to apply proper height to latest story items?

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#376]
There seems to be javascript that's hardcoding a height into the html of latest story items. (See screen shot.)
When I include the header (organisms/global/header.html) in the new index pages this height doesn't get applied, resulting in a broken latest-stories layout. What needs to be done for header.html object to work consistently on all pages?

![screen shot 2017-02-23 at 10 45 47 pm](https://cloud.githubusercontent.com/assets/151099/23293353/985d3352-fa1a-11e6-9811-b3f610288ff8.png)

**Comment by MrBryan** [comment]
Basically on window.ready it loops the items in the list and finds the tallest one and then makes them all that height + a buffer. As long as the elements haven't changed their location/attributes it should still work - have any class names or object nesting changed ?

**Comment by alexgreen** [comment]
No change I'm aware of. I just included organisms/global/header.html like the story pages do:

`{% include meta/head.html %}
  <body class="{{ page.layout }} {% comment %}cmnt--visibility{% endcomment %}" id="{{ page.slug | 'front' }}">

    
    
    
    {% include 01-molecules/messaging/alerts--browser-support.html %}
    {% include 02-organisms/sections/httpswarning.html %}
    {% include 01-molecules/blocks/ad-banner.html ad-source="UBCMUD-leaderboard.jpg" %}
    {% include 02-organisms/global/header.html %}

    

    {{ content }}`

**Comment by MrBryan** [comment]
That was a pretty hacky fix in the first place maybe a good time to do it right and truncate length of text with eclipses and get a consistent height
