### ISSUE TITLE
gh-pages branch not deploying

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#377]
The section page is almost done. I've merged my changes into the gh-pages branch and pushed it to github, as you can see here: https://github.com/TheTyee/design-article.thetyee.ca/tree/gh-pages

I can serve it locally but it's not getting served to github.io:
http://thetyee.github.io/design-article.thetyee.ca/section-index.html

@MrBryan any idea what the problem is?

**Comment by alexgreen** [comment]
Hmm. it seems to be up on github.io now. Did you do something?

**Comment by MrBryan** [comment]
Nope not other than look at it, must just be delayed we need to play it

**Comment by alexgreen** [comment]
...play it?

I never noticed any delays in github.io before but I guess it's possible.

**Comment by MrBryan** [comment]
Sorry that was a Siri miscue - when we deploy I meant
