### ISSUE TITLE
Hotfix needed to mobile subscription form

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#382]
Hey there @MrBryan 

Just found this high-priority bug:
https://github.com/TheTyee/design-article.thetyee.ca/blob/63f4e85099268432d13fd08d2f33bfe48e789269/_includes/01-molecules/blocks/messaging-block--subscribe.html#L34

On the mobile form, the weekly option is set to daily. Instead of making the change as part of the work I'm doing, I was thinking it might be faster for you to fix it up and then I can rebase off of your changes.

Phillip.

**Comment by MrBryan** [comment]
I committed to develop.. went to pull onto bc-bricmod but there are changes in that file on server & article_custom.js -- was that me?  Assuming you would never work on the server....  ;)

**Comment by phillipadsmith** [comment]
That was you! ;)

**Comment by MrBryan** [comment]
Merged it ok to preview --    The subscribe form is pointing https://preview.webhooks.thetyee.ca/subscribe on preview which is down atm so fails -- seems to be via the "proxyAPI" variable switch. 

But when I merged to live it would fail on the subscribe button saying " proxyAPI" not defined even when I would manually run enableEmailSubscribe() function that defines it..   So I rolled back  & did a hotfix on live for that typo for now...  preview has it merged

**Comment by phillipadsmith** [comment]
Can you re-merge the develop branch into preview (only!) kind Sir @MrBryan ? I've fixed the proxy URL so testing should be working again.

**Comment by MrBryan** [comment]
Done :)  didn't commit the merge in case :)

**Comment by phillipadsmith** [comment]
This is closed, yes?
