### ISSUE TITLE
Nav Bar -- clarify section nav dropdown

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#40]
- add TYEE PRESENTS as a section in the section menu
- May also need a similar "Sections" header, but hopefully not as the button already says this.
  _DONE - Add a "Topics" header above the topics list_

Robyn:
Alex, if it’s easy enough to put a “Topics” header within the drop-down, above the first topic (which would be Aboriginal Affairs), that’d be great. The distinction between "Sections" and "Topics" is not essential, but maybe still helpful for readers.

I’ve never viewed Reported Elsewhere as a distinct “Section” – it’s more of a front-page widget that has its own homepage (http://thetyee.ca/ReportedElsewhere/).
I'm not sure how this page will be affected by the redesign, but as you normally only access it on the front page anyway, maybe that’s a Phillip question?

Currently we link to a list of “Contributors” in the footer. I think it’s fine to keep doing that. No need to add to “Sections.”

Yes, let’s add TYEE NEWS as a “Section.” Let’s also add TYEE PRESENTS here, too. Let's not worry about changing the names right now.

From Alex:
I think this depends on what you mean by "section" and "topic" and whether it's important for readers to be aware of the difference. If readers need to be made aware, then I would suggest that answer is yes, they should be differentiated more clearly, especially in mobile views where it all stacks into one column with no division. "Sections" already appears above, so that seems obvious, but we could a "topics" header within the dropdown above the list of topics.

From Michelle:
- in the section drop down, do you think we should say 'section' above the sections, and 'topics' above the topics?  Or does that matter at all?
- Are we letting go of Reported Elsewhere?  Or did we just forget to add it to Sections?
- Should we be adding 'columnists' to the Sections?  They're nowhere in the nav right now
- Should 'Tyee News' live in the sections, and possibly be renamed as something a little clearer?  (signaling that it's internal news - and then maybe 'jobs' can live there instead of having its own page?)

**Comment by kidcompassion** [comment]
<img width="1229" alt="screen shot 2016-03-09 at 11 48 44 am" src="https://cloud.githubusercontent.com/assets/1507827/13646575/4e74d7b4-e5ed-11e5-94da-ff94be095841.png">
I've added a topics subheader in branch sp-based-off-ag-atomic, commit 0ff2471fe423c0f26586ee9706d5cbdf7bcc765c. Not closing this, because editorial comments on header remain unresolved.

**Comment by kidcompassion** [comment]
Closing, as I haven't heard any more feedback or change reuqests.
