### ISSUE TITLE
Add Tyee presents block (header?)

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#41]
- [x] Design Tyee presents block
- [x] style for all views
- [x] determine where it will live

**Comment by kidcompassion** [comment]
@alexgreen can I get a wireframe/design for this too?

**Comment by phillipadsmith** [comment]
@alexgreen Status on this?

**Comment by alexgreen** [comment]
still in progress. should be done on monday.

**Comment by phillipadsmith** [comment]
👍

**Comment by alexgreen** [comment]
@phillipadsmith Since Michelle was concerned about aside content on small screens I prioritized that. Now that it's complete I'll return to this Presents block header.

**Comment by alexgreen** [comment]
82d94a3e43c6e500fcdf0e45d425e91e6b6a4a8f adds and styles the Tyee presents-box. Presents story elements TBA pending specs.
