### ISSUE TITLE
Latest stories widget is loading large images

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#47]
Looks like the "Latest Stories" widget is referencing large images (610px), which means the page load speed is greatly impacted.

The API exposes links to the thumbnails images for the story, so we should use one of the smaller options if possible.

Shout if we need a new thumbnail size generated for stories.

Phillip.

**Comment by kidcompassion** [comment]
@phillipadsmith I'm thinking this could be coordinated with Bryan's handiwork? so, potentially get Bric to crop to a specific scroller-appropriate size and pass it to the API?

**Comment by phillipadsmith** [comment]
@kidcompassion Yes, I think we'll need to add this size to what's created for each story.

cc @MrBryan

**Comment by MrBryan** [comment]
@phillipadsmith can you remind me where the api submission code is called in bric?  haven't been able to find it

**Comment by phillipadsmith** [comment]
Mostly in triggers.mc if I’m not mistaken.

However, the entire thing is in a separate library that is on GitHub here:
https://github.com/TheTyee/Tyee-API https://github.com/TheTyee/Tyee-API

And you’ll find it on sashimi under the sashimi.thetyee.ca directory.

Let me know if that’s what you’re looking for.

In terms of image sizes, I think all that you would need to do is adjust the parameters to the crop_and_resize function in the story.mc template (?) and that should automatically pass a new image object to the API, which should then show up as a property of the story.

All that to say, if memory serves, I don’t think you’ll need to make adjustments to the API submission call, or the API library, just to provide a new image size.

Let me know if that doesn’t make sense!

Phillip.

**Comment by MrBryan** [comment]
Cool I'll have a look -- I assumed the API needed explicit references to any new items it will catalogue unless you were replacing images which presumably we are not since the old resolution may be used elsewhere

**Comment by phillipadsmith** [comment]
Again, memory serves that the thumbnails are just related media assets that are specific to a story, and I believe the library handles that here: https://github.com/TheTyee/Tyee-API/blob/master/lib/Tyee/API/Story.pm#L582-L634 https://github.com/TheTyee/Tyee-API/blob/master/lib/Tyee/API/Story.pm#L582-L634 

I.e., looking up those assets and adding them to a property of the story’s object.

So, I _think_ simply adding a new option to the crop_and_resize function (I think in story.mc?) would auto-magically show up in that story’s property in the API.

Obviously, it would not be there for old stories. So there would need to be a republishing at some point to update old story’s properties with the new thumbnail reference.

**Comment by phillipadsmith** [comment]
> Cool I'll have a look -- I assumed the API needed explicit references to any new items it will catalogue unless you were replacing images which presumably we are not since the old resolution may be used elsewhere

Any luck?

**Comment by MrBryan** [comment]
not really I added references to another image in related_media.mc but now that I look, the other one listed there, with file_suffix  => '_page_thumb',  isn't in the existing list in the API either

**Comment by MrBryan** [comment]
the api filters by: 

```
        if ( defined( $_->get_file_name )
            and $_->get_file_name =~ m/_thumb/ )
        {
            my %thumb;
            $thumb{'name'}   = $_->get_name;
            $thumb{'width'}  = $_->get_value( 'width' );
            $thumb{'height'} = $_->get_value( 'height' );
            $thumb{'uri'}    = $CDN . $_->get_uri;
            push @related_media_thumbs, \%thumb;
        }

```

and  we have  this running on every new related image (second part is mine, but the first also doesn't show up in the thumbnail list so shouldn't need any republishing for those ones... confused

```
   $image = eval {
        $image->find_or_create_alternate({
            title_prefix => $max_width . 'px version of ',
            file_suffix  => '_page_thumb',
            et_key_name  => 'thumbnail',
            relate       => 0,
            transformer  => sub {
                shift->scale( xpixels => $w  );
            },
        });
    };

};

$image_thumb = eval {
        $image->find_or_create_alternate({
            title_prefix =>  '175slider_thumb_version',
            file_suffix  => '_slider_thumb',
            et_key_name  => 'thumbnail_slider',
            relate       => 0,
            transformer  => sub {
                shift->scale( xpixels => 175  );
            },
        });
    };

```

**Comment by MrBryan** [comment]
looks like it doesn't exist just searching in media either, probably has to be moved into publish somehow directly first which is probably done to the other ones when the front page, cover page etc are created.

**Comment by MrBryan** [comment]
OK got it now ;)  I pasted the code from somewhere in the template where as you can see it was wrapped in "eval" :P   +  I put it into story.mc now FYI

**Comment by phillipadsmith** [comment]
> OK got it now ;) I pasted the code from somewhere in the template where as you can see it was wrapped in "eval" :P + I put it into story.mc now FYI

👍

**Comment by MrBryan** [comment]
added a trick that searches for alternate >200px and smaller than default 5657abb126e081a1e3a7b075c100a8363fb8f70a.  Usually there is something.  Phillip & I chatted more about this.. to be replaced by the Thumbor later perhaps..
