### ISSUE TITLE
Reconcile the top navigation drop down?

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#48]
I find switching from the navigation item "Latest Stories" to "Sections" to "More" somewhat "not smooth," and it's hard to put it in more concise words than that; something just feels not right because the heights of the drop-down menus are difference and because the treatments are slightly different (some use lines, some don't).

Discus. :-)

**Comment by alexgreen** [comment]
I also flagged a related concern in response to the latest PR:

> The stacked nav must allow multiple items to be expanded simultaneously. I.e. if I click to expand the Latest Stories and scroll down past them where I then decide to expand More, Latest Stories should remain expanded. Otherwise the whole menu shifts upwards and I have to scroll up to see the top of the More list. —So, currently the menu expansion behaviour actually conceals the very thing I’m trying to see. (Hard to explain this clearly in words, but try it in a view 700px wide and you’ll see what I mean.)

There's further comments appended to the PR: https://github.com/TheTyee/design-article.thetyee.ca/pull/44

**Comment by kidcompassion** [comment]
@phillipadsmith are these comments specific to the larger sizes of the nav? If so, I defer to @alexgreen for any design things that need to be reworked. My guess is that the topic header that I plugged in there is the culprit; we can get rid of it if need be, or if you'd like to rework it @alexgreen, you sure won't hurt my feelings!

**Comment by phillipadsmith** [comment]
@kidcompassion Yes, indeed, I was referring specifically to the large sizes. Looks at #44, I think most of it's covered in that conversation. Closing this one for now.
