### ISSUE TITLE
Social icons: E-mail this article

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#50]
E-mail this article needs to be wired up. That can be done at this point, and it'll work a-ok, as it's a micro service with some JavaScript. 

I can take this on if helpful.

**Comment by alexgreen** [comment]
Yes, please take it away. Thanks Phillip!

**Comment by phillipadsmith** [comment]
Closed with this commit:
https://github.com/TheTyee/design-article.thetyee.ca/commit/70774dbe298269c71a234f7d68e2782c44686957

**Comment by phillipadsmith** [comment]
Form:
<img width="760" alt="localhost_4000" src="https://cloud.githubusercontent.com/assets/34128/14068670/9ae40614-f43f-11e5-9899-7cd04c3b5aa9.png">

Form validation:
<img width="645" alt="localhost_4000" src="https://cloud.githubusercontent.com/assets/34128/14068673/bade28aa-f43f-11e5-976d-4888168e8c1a.png">
