### ISSUE TITLE
Social icons: Facebook & Twitter

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#51]
I'm going to drop a note into the Analytics Basecamp now to ping Eric on this.

My sense is that we'll need to use the native FB & Twitter buttons, unless we have time to wire-up our own, because of the way that sending data to Google Analytics, which requires that we load and use both the Facebook JS SDK and Twitter's embed JS.

Could put on my list if helpful.

**Comment by phillipadsmith** [comment]
Basecamp thread: 
https://basecamp.com/1929296/projects/9588526/messages/56049562

**Comment by alexgreen** [comment]
Yes, if you could take this on that would be great. No need to use custom buttons. I believe I just grabbed the stock icons from bootstrap.

**Comment by alexgreen** [comment]
fyi: 

> Hmm, that isn’t right
> You may have typed the URL incorrectly.
> 
> Check to make sure you’ve got the spelling, capitalization, etc. exactly right.

**Comment by phillipadsmith** [comment]
@alexgreen You probably don't have access to that Basecamp project.

I'm awaiting a response from Eric, yet I think we'll stick with the custom (not native) buttons.

**Comment by phillipadsmith** [comment]
@alexgreen I'm looking at  molecules/blocks/tool-bar.html and it's almost repeated verbatim in messaging-block--share.html  ... wondering if the contents of tool-bar.html (the share icons) should be abstracted out and then included in each?

**Comment by alexgreen** [comment]
Probably, but the visual result in the 2 placements (in terms of which icons are displayed and their sizing) is very different. So I don't think figuring out a way to abstract this while still allowing for that degree difference in content and styling is really worth the bother when there's more pressing issues.

**Comment by phillipadsmith** [comment]
Cool.
