### ISSUE TITLE
Subscribe to the Tyee box

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#52]
Who was working on the "Subscribe to the Tyee" box? Was that @MrBryan? 

If so -- given that he's travelling this week and possibly next -- I'm thinking we should probably re-assign? 

Relevant thread:
https://basecamp.com/1929296/projects/9481270/messages/55732693#comment_397565173

Phillip.

**Comment by alexgreen** [comment]
There was quite a bit of discussion and enthusiasm about Bryan coding a fairly elaborate progressive discloser sequence, but in the end I believe it was decided to follow Grist's newsletter option drop-down model (which I thought had been our plan from the beginning).

If you can add a dropdown to the button code and move the submit button right of the email field that would be great!

**Comment by phillipadsmith** [comment]
> If you can add a dropdown to the button code and move the submit button right of the email field that would be great!

Yep. On my list as @MrBryan is travelling at the moment and don't think he'd be able to get to this for March 28th.

**Comment by phillipadsmith** [comment]
This is what I'm thinking: 

<img width="630" alt="localhost_4000" src="https://cloud.githubusercontent.com/assets/34128/14068244/f91f026e-f431-11e5-87da-98b8cfa27889.png">

<img width="784" alt="localhost_4000" src="https://cloud.githubusercontent.com/assets/34128/14068247/083e5510-f432-11e5-8aaf-3ea4175eba28.png">

**Comment by kidcompassion** [comment]
@phillipadsmith Nice! :+1:

**Comment by phillipadsmith** [comment]
Merged here:
https://github.com/TheTyee/design-article.thetyee.ca/commit/76a2f315dbb9a565556cfab0fcea250737d9229b

**Comment by MrBryan** [comment]
Looks great. I had only ever jumped in because we were trying to look at ways I could take a small load off and wasn't aware the plans had been solidified. The discussion was more like a few comments one afternoon so no time lost.  Forge ahead and happy to try to help some other way. For now I'll hit the beach again :)

Bryan

**Comment by phillipadsmith** [comment]
> Forge ahead and happy to try to help some other way. For now I'll hit the beach again :)

Send beach gifs! ;-)

**Comment by alexgreen** [comment]
What is the @ sign for at the start of the form? Seems unusual and possibly misleading.
Can we omit it?

**Comment by alexgreen** [comment]
... otherwise I think this is perfect

**Comment by phillipadsmith** [comment]
Needs to be fixed at small viewport size:
<img width="391" alt="localhost_4000" src="https://cloud.githubusercontent.com/assets/34128/14089547/3dd71456-f4ea-11e5-919a-d30c282c61ba.png">

**Comment by alexgreen** [comment]
I don't wanna be too fussy, but could all 3 fields/buttons stack into separate full-width lines (as Grist)? (Or even just expanding the subscribe button to full-width would help to balance it visually.)

![grist-subscribe-stacked](https://cloud.githubusercontent.com/assets/151099/14106133/4e94d052-f5ea-11e5-9514-51a6ed47d81e.png)

**Comment by phillipadsmith** [comment]
Also change text to "Get The Tyee in your inbox"

**Comment by phillipadsmith** [comment]
> I don't wanna be too fussy, but could all 3 fields/buttons stack into separate full-width lines (as Grist)? (Or even just expanding the subscribe button to full-width would help to balance it visually.)

Yep. No problem. Will do today.
