### ISSUE TITLE
Simplify footer

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#53]
The footer is to be simplified per this input from the team:
https://basecamp.com/1929296/projects/9481270/messages/53811335#comment_395543151

**Comment by kidcompassion** [comment]
@alexgreen can you provide even a super rough wireframe for this? I'm going to tag you/request that for any design changes. It can seriously just be a photo of a scribble on a paper.

**Comment by alexgreen** [comment]
It's hard to believe they only want 6 items in there! (... really hard to believe!) 

How about a 3-column layout that lines up with the text column above. If you start with the messaging-zone.html container object and extend it to add any additional styles you need then the alignment with above text should be taken care of already.
(hmm, I should have abstracted a content-agnostic text-column container since a couple separate objects already use this positioning. That would be a good thing to refactor.)

![footer](https://cloud.githubusercontent.com/assets/151099/14060112/6fb2e0da-f39c-11e5-8e14-701cae382034.png)
(Pls disregard the use of purple.)

**Comment by phillipadsmith** [comment]
> It's hard to believe they only want 6 items in there! (... really hard to believe!)

It was discussed at length at the time, and the decision was to have a footer that is as simple as possible. 

With the two columns of links, it's not obvious how to split the links up between the two columns, so I'd personally advocate against that.

Also, the items need to be alphabetized, not arbitrary, in their order. 

I think something much simpler would work really well.

**Comment by alexgreen** [comment]
> it's not obvious how to split the links up between the two columns

My rationale was to group like actions into the column. But I now see there isn't really one single intuitive way to do that. (Maybe group Join + Subscribe and About + Contact + Advertise ?)

> the items need to be alphabetized

Why? alpha order is highly arbitrary, so if there's any more intuitive way to organize them that should be preferable.

> I think something much simpler would work really well.

3 columns seems pretty simple and probably the easiest way to keep things aligned. unless you're talking about running them in a single column, which would look odd.

Anyway, I'm open to any suggestions. take 'er away!

**Comment by phillipadsmith** [comment]
> Why? alpha order is highly arbitrary, so if there's any more intuitive way to organize them that should be preferable.

How would you prioritize them then? It would be an arbitrary choice, no? At least alpha is intuitive to the reader.

> 3 columns seems pretty simple and probably the easiest way to keep things aligned. unless you're talking about running them in a single column, which would look odd.

It's going to be one column at small views anyway, no? 

How about a simple inline list (running horizontally at wide views, and wrapping at smaller views)?

Lots of examples of simple footers out in the wild to draw from; we don't need to re-invent the wheel here (yet we need something for March 28th).

Phillip.

**Comment by phillipadsmith** [comment]
Nice and simple (no links):
<img width="1019" alt="grist___environmental_news__commentary__advice" src="https://cloud.githubusercontent.com/assets/34128/14061886/ba257d06-f349-11e5-8f07-87642ca4ab34.png">

No links, yet a nice way to end things:
<img width="988" alt="viawesome___vancouver_publication_featuring_positive_stories_of_culture__arts__lifestyle_and_everything_awesome_about_our_city_" src="https://cloud.githubusercontent.com/assets/34128/14061888/cdd0d01c-f349-11e5-99b9-0e061714b962.png">

Classic, just links:
<img width="1104" alt="page_not_found_-_the_new_yorker" src="https://cloud.githubusercontent.com/assets/34128/14061893/e9030526-f349-11e5-8661-647f815f1547.png">

**Comment by alexgreen** [comment]
> How would you prioritize them then? It would be an arbitrary choice, no?

There's lots of non-arbitrary ways to organize a list. For example it makes sense for the ones that the reader is most likely need (or the ones you want to encourage them to use) to be most prominent and/or higher up in the list. Or, as I mentioned, you could group links that are related in terms of content or action. Alpha order really only makes sense when you have a long directory list or there's absolutely no semantic way to organize the items. In this case it's only 6 items so it probably doesn't matter much either way.

The examples look good to me. Layout-wise I just think it needs to align with the text column in some way. You have ideas, so can I leave it to you?

**Comment by alexgreen** [comment]
> hmm, I should have abstracted a content-agnostic text-column container since a couple separate objects already use this positioning.

I've abstracted the main text column positioning styles into the class .main-col-container.
So you can apply .main-col-container to any direct descendent of _body_ that should conform to the main text column dimensions and alignment.

**Comment by phillipadsmith** [comment]
> You have ideas, so can I leave it to you?

I don't have any specific ideas, to be honest. Just heard The Tyee staff saying "simple." 

@kidcompassion Any ideas?

**Comment by kidcompassion** [comment]
@phillipadsmith yup, i'll just make an executive decision.

"Sally, why are there two dozen animated gifs of sloths in the footer?!"
![uploads/e0bf5394-ab75-4864-8aea-a4cce06f18de/sloth-baby-1436970265.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe0bf5394-ab75-4864-8aea-a4cce06f18de%2Fsloth-baby-1436970265.gif)

**Comment by phillipadsmith** [comment]
SLOTHS! 

We should ask (later) if it would make sense to include awards in the footer. I kinda' like that as it adds some credibility to the piece, without needing to read the "About Us" page.
