### ISSUE TITLE
Latest story directional arrow doesn't seem to do anything...

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#56]
See the arrow to the right, yet not seeing it do anything. I recall you mentioning something about the slider, so just close this if I'm stating the obvious that you're in the midst of working on.
<img width="481" alt="localhost_4000" src="https://cloud.githubusercontent.com/assets/34128/14033102/dae2a0a8-f1d4-11e5-9080-6104efa2f785.png">

**Comment by alexgreen** [comment]
The button works for me, but the photos load so slowly that it appears non-functional. 
Here's my comments from the PR https://github.com/TheTyee/design-article.thetyee.ca/pull/44:

Latest stories
- Slider only navigates rightwards. Can we add a left arrow?
- When navigating (rightwards) there’s a really long lag before the new images get loaded. Can they load quicker? If not then we should put in grey boxes with a loading symbol gif as placeholders.

**Comment by kidcompassion** [comment]
Closing this, because it's accounted for in another branch (I still have bugs to fix in the scroller).
