### ISSUE TITLE
Advertising: In-story big box ad missing

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#58]
We'll want to include a big box ad _in_ the actual story flow before presenting these again.

**Comment by alexgreen** [comment]
There's already 2 bigboxes within the flow now. (But in wide views the first one moves next to the featured image.)

**Comment by phillipadsmith** [comment]
> There's already 2 bigboxes within the flow now. (But in wide views the first one moves next to the featured image.)

:+1:
