### ISSUE TITLE
Series header example

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#59]
Example of an article that part of a series that shows:
- [x] An indication that the story is part of a series (in the past, a badge was used)
- [x] A "series navigation" block that links to the series front page, as well as other stories in the series.

**Comment by kidcompassion** [comment]
Closing this, as it appears to be resolved in current dev branch. Feel free to put it back if there's more to be done.

![uploads/68417859-4fd3-4d84-b7a8-ea3e38ad1e0f/Screen Shot 2016-04-17 at 12.01.12 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F68417859-4fd3-4d84-b7a8-ea3e38ad1e0f%2FScreen+Shot+2016-04-17+at+12.01.12+PM.png)

![uploads/bd1e0560-9644-44c3-8679-742906de0e65/Screen Shot 2016-04-17 at 12.01.07 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbd1e0560-9644-44c3-8679-742906de0e65%2FScreen+Shot+2016-04-17+at+12.01.07+PM.png)
