### ISSUE TITLE
Mini-bios and photos

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#61]
From our web team planning document:

> Mini bios & bio photos [Editorial, Sally]
> If no image, don’t show the image
> Next actions:
> SP to ask Tyee team for their top 40 list, plus photos
> 315px wide… or larger
> Decide on fallback image for social media, whether author or pre-made fallback image

**Comment by kidcompassion** [comment]
Waiting on response. 
https://basecamp.com/1929296/projects/9481270/messages/56083117

**Comment by phillipadsmith** [comment]
:+1:
