### ISSUE TITLE
Pop-over subscription ask

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#65]
The subscription pop-over will need to be re-implemented.

**Comment by kidcompassion** [comment]
@phillipadsmith @alexgreen do we want this ready for internal testing, or is this just a "do this eventually" issue?

**Comment by phillipadsmith** [comment]
@kidcompassion I'd propose it's something we should try to include for testing, as it is something that will need to get carried over and something that we've not accounted for on mobile yet, i.e., it's only visible on a "desktop" version of the site at the moment.

**Comment by kidcompassion** [comment]
@phillipadsmith I'm sorry if you get 8000 notifications saying I assigned this to you! For some reason Huboard freaked out and wouldn't let me assign it to me. :D

**Comment by phillipadsmith** [comment]
>  I'm sorry if you get 8000 notifications saying I assigned this to you! For some reason Huboard freaked out and wouldn't let me assign it to me. :D

I only received one! :-)

**Comment by phillipadsmith** [comment]
Looks like this one is still open (at least in terms of styling), unless is resolved in another branch:
<img width="842" alt="the_tyee_article_page" src="https://cloud.githubusercontent.com/assets/34128/14193492/19e5eeb0-f75a-11e5-994a-12508dd09af9.png">

If this isn't something you can get to before Monday, @kidcompassion, let's just prevent the pop-over from popping for now so as not to confuse testers. Then we can come back to it later.

**Comment by phillipadsmith** [comment]
Looking at this, I guess I'm realizing for the first time that perhaps the existing layout/design of the pop-over will not work at smaller sizes (duh!) and thus that this actually requires some re-thinking / re-designing... perhaps that's the bigger issue?

**Comment by phillipadsmith** [comment]
If that's the case, let's assign this to @alexgreen to have a look at.

**Comment by phillipadsmith** [comment]
Oddly, the background changes at smaller viewport sizes (looking much closer to what I was expecting!):
<img width="763" alt="screenshot_2016-03-31__5_04_pm" src="https://cloud.githubusercontent.com/assets/34128/14194650/a16cce98-f765-11e5-8734-56c691673667.png">

**Comment by phillipadsmith** [comment]
@kidcompassion  Are you working on this, or should I re-assign it to me?

**Comment by kidcompassion** [comment]
I thought it was. I think some styles from elsewhere may be overriding my changes, will have a look.

**Comment by kidcompassion** [comment]
Fixed & merged into develop.

**Comment by phillipadsmith** [comment]
💯
