### ISSUE TITLE
Social icons: E-mail icon dropping under others on smaller views

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#69]
<img width="372" alt="iphone_6s_-_iphone_6s___ios_9_2__13c75_" src="https://cloud.githubusercontent.com/assets/34128/14057786/a57a580e-f2c7-11e5-8fd3-24317fd0170f.png">

**Comment by alexgreen** [comment]
@phillipadsmith were you saying that we should use stock social buttons from the proprietors? If so, it probbly makes sense to sub those in before doing any layout fixes.
Would you have time to take that on?

**Comment by phillipadsmith** [comment]
> were you saying that we should use stock social buttons from the proprietors?

I was wondering out loud, yes, and I've asked Eric to confirm... 

Yet, in hindsight, I believe Eric will prefer that we use these custom icons/buttons because they will be much easier for him to track in Analytics.

So, for the moment, I believe we should push forward with custom buttons. 

Phillip.

**Comment by alexgreen** [comment]
fixed by commit c625aac
