### ISSUE TITLE
Nav bar -- adjust link spacing and breakpoints

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#70]
Search link could collapse to just magnifying glass.
Other comments in attached screen shots.

![nav-break-1](https://cloud.githubusercontent.com/assets/151099/14064751/dabbbe3a-f449-11e5-92cd-1ba1d5bc0b58.png)

![nav-break-2](https://cloud.githubusercontent.com/assets/151099/14064765/62988f2c-f44a-11e5-97a7-c8281a121c79.png)

**Comment by kidcompassion** [comment]
Will do as soon as all functionality is completed.

**Comment by alexgreen** [comment]
still some inconsistencies:

![screen shot 2016-03-31 at 10 32 10 pm](https://cloud.githubusercontent.com/assets/151099/14177543/b4a6eec2-f791-11e5-8ec5-067cf2e7896f.png)

**Comment by phillipadsmith** [comment]
Moved to a later milestone.

**Comment by phillipadsmith** [comment]
Howdy @alexgreen @kidcompassion,  

Just checking-in on the status for this issue? Resolved or now in #128?

Phillip.

**Comment by alexgreen** [comment]
I think the spacing and breaks points issue is now solved. #128 is an new issue that arose as a result of the measures that fixed the problem of the ballooning logo size in wide views.
