### ISSUE TITLE
Latest Stories -- adjust borders & colours

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#72]
![nav-borders_colours](https://cloud.githubusercontent.com/assets/151099/14064868/f2e20330-f44d-11e5-9699-4586f94e3e09.png)

**Comment by kidcompassion** [comment]
Will do as soon as all functionality is completed.

**Comment by alexgreen** [comment]
In viewports narrower than 992px the borders are still green and there's still a bottom border.

![screen shot 2016-03-30 at 7 02 57 pm](https://cloud.githubusercontent.com/assets/151099/14138834/5af4a1b8-f6aa-11e5-8b4d-0536d381ca61.png)

**Comment by phillipadsmith** [comment]
@kidcompassion Would be great if you have time to nail this on Friday/Sunday. I've moved other "niggles" to a later milestone.

**Comment by kidcompassion** [comment]
All done!
