### ISSUE TITLE
Nav bar -- borders of drop-down change colours at some view widths

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#73]
Somewhere around 770px the border colour changes from grey to green.

![nav-colours](https://cloud.githubusercontent.com/assets/151099/14064891/a0f5b8f4-f44e-11e5-8cbe-33bce23be16d.gif)

**Comment by alexgreen** [comment]
Borders change colour at 991px

**Comment by phillipadsmith** [comment]
Moving to later milestone.

**Comment by kidcompassion** [comment]
Fixed!
