### ISSUE TITLE
Create main col layout container 

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#74]
Abstract a universal layout container that can be used to house any object that needs to align with the main text column. (e.g. see attached)

![comments not aligned](https://cloud.githubusercontent.com/assets/151099/14064971/a36ed392-f451-11e5-8767-d5b5790ea94b.png)

**Comment by alexgreen** [comment]
I've abstracted the main text column positioning styles into the class .main-col-container.
So you can apply .main-col-container to any direct descendent of <body> that should conform to the main text column dimensions and alignment.

**Comment by phillipadsmith** [comment]
> I've abstracted the main text column positioning styles into the class .main-col-container.
> So you can apply .main-col-container to any direct descendent of that should conform to the main text column dimensions and alignment.

:+1:
