### ISSUE TITLE
Author Bio more button -- show teaser

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#75]
Right now the blank bio blows a hole in the layout. 
Can we set it to always show the first 107 characters of the bio and then append the more link inline?

**Comment by phillipadsmith** [comment]
Howdy @kidcompassion: Seems like you're working on this requirement? If so, I'll re-assign these to you to avoid duplicating work.

**Comment by kidcompassion** [comment]
I'll start this, but @alexgreen, if you have something specific in mind, do you mind providing some kind of drawing or diagram? It makes getting stuff done way faster and avoids having to do repeated iterations.

**Comment by phillipadsmith** [comment]
>  if you have something specific in mind

I think that @alexgreen described/proposed an option in the other related tickets: #76, #77, #78

**Comment by kidcompassion** [comment]
Yup! @phillipadsmith My preference is to get that design element done first, before I build something myself. It saves time from me doing it and then doing it again.

**Comment by alexgreen** [comment]
> I think that @alexgreen described/proposed an option in the other related tickets: #76, #77, #78

correct

Here's the summary:
- set a 670px viewport breakpoint for truncating the bio
- always show the first 107 characters of the bio 
- append a "show more" link inline as a simple text link.
- In the expanded state the "show more" link disappears and a "show less" text link is appended inline.
- caret is optional, probably unnecessary

I could draw it but that won't tell give you any additional information. It's just a normal text link.
Is that enough to go on?

**Comment by phillipadsmith** [comment]
Question: Why are we showing the bio (even truncated) at smaller sizes? 

Can we not just link the contributor's name to their bio page and leave the design to the mobile user to explore further? 

Alternately, hide the bio at the top of the mobile story (where vertical space is at a premium) and show it at the end of the mobile story.

Two cents,

Phillip.

**Comment by alexgreen** [comment]
> Question: Why are we showing the bio (even truncated) at smaller sizes?

Because our MO has been to exclude as little content as possible from small views and this has been reflected in all mockups to date. (Not saying it's carved in stone, just explaining.)

> Can we not just link the contributor's name to their bio page and leave the design to the mobile user to explore further?

Yes, but do we want to redesign this right now? Good ideas and I'm happy to explore, but at this point every new task will delay delivery. 

> Alternately, hide the bio at the top of the mobile story (where vertical space is at a premium) and show it at the end of the mobile story.

ditto.

**Comment by phillipadsmith** [comment]
> Because our MO has been to exclude as little content as possible from small views and this has been reflected in all mockups to date. (Not saying it's carved in stone, just explaining.)

Yes, but then all of the asides are now being hidden at smaller views, so this MO is not consistent.

> Yes, but do we want to redesign this right now? Good ideas and I'm happy to explore, but at this point every new task will delay delivery.

Not proposing a re-design, just hiding something that's taking up vertical space on small screens.

I'm fine to come back to this later.

**Comment by alexgreen** [comment]
> Yes, but then all of the asides are now being hidden at smaller views, so this MO is not consistent.

True, but I'm still trying to adhere to it as a guiding principle in most, if not all, cases.

But after seeing how nice the mobile view looks without any asides I'm coming around to your suggestion—thinking about an intermediate possibility.

**Comment by phillipadsmith** [comment]
> But after seeing how nice the mobile view looks without any asides I'm coming around to your suggestion—thinking about an intermediate possibility.

:+1:
