### ISSUE TITLE
Author Bio more button -- not working on mobile?

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#76]
The more button doesn't function on my ipad or my android phone.

**Comment by alexgreen** [comment]
Seems like it isn't working in my Chrome device tester either.

**Comment by kidcompassion** [comment]
I _think_ this is working now (caveat is that I haven't got my system wired up to check mobile devices locally, so I'm basing this on XCode and the Chrome emulator. Let me know if i'm wrong.

**Comment by alexgreen** [comment]
This is still not working reliably for me. 
On my android phone in Chrome it works in landscape, but not in portrait. In laptop Chrome device mode it works at 375px view but not at 320px, and at 425px it works sometimes but not always.

**Comment by phillipadsmith** [comment]
I'm going to propose that we move this to a later milestone and, if necessary because it's going to confuse people, just remove the button for now.

**Comment by phillipadsmith** [comment]
Howdy @alexgreen @kidcompassion,  

Just checking-in on the status for this issue? Resolved? 

Phillip.

**Comment by alexgreen** [comment]
This was resolved in #94. Assuming everyone's happy with the current solution then I'd say it's done.
