### ISSUE TITLE
Author Bio more button -- restyle

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#77]
Can we restyle this in a less obtrusive way? Does it need to be a literal button element?
A simple text link + caret would be great.

**Comment by alexgreen** [comment]
Did you merge this into develop? I'm not seeing any change yet.

**Comment by phillipadsmith** [comment]
I think is closed, correct?

**Comment by alexgreen** [comment]
yes, pending any feedback on the design solution.
