### ISSUE TITLE
No tabs, only spaces please! :-)

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#79]
Howdy @alexgreen @kidcompassion,

Can you two check your editor settings to ensure that spaces (4) are used instead of tab characters? 

Many of the files I'm opening have loads of tabs in them, which makes moving around kinda' funky. 

Thanks! :-)

**Comment by kidcompassion** [comment]
@phillipadsmith Tabs are the default HTML setting in Sublime Text. Will change ASAP!

**Comment by phillipadsmith** [comment]
Sublime Text--   (Not so sublime are you now, Mr. Sublime Text!)

**Comment by alexgreen** [comment]
:+1:
