### ISSUE TITLE
Make a list of all elements used in the last year

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#8]

**Comment by kidcompassion** [comment]
For reference, my preliminary list had: 
- hed
- dek
- paragraph (seen in the series page element)
- content (seen in a story page element)
- photo gallery
- multimedia (video or audio)
- individual photo
- authour
- social tools

Obviously this doesn't match exactly with the bricolage element structure currently in place, but it appeared to cover most use cases in the last year.
