### ISSUE TITLE
Search icon position is too low on small views

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#81]
<img width="400" alt="responsive_layouts_from_http___localhost_4000_" src="https://cloud.githubusercontent.com/assets/34128/14068793/201bceea-f443-11e5-98ee-470adb2d5833.png">

**Comment by alexgreen** [comment]
The "search" label will probably need to collapse (show only icon). Likely this should occur at a wider breakpoint than this because it causes problems in other cases too (noted in other issues).

**Comment by kidcompassion** [comment]
Resolved.
![uploads/2678fcc1-7dde-4013-84ad-e63102402a43/Screen Shot 2016-03-30 at 6.02.47 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F2678fcc1-7dde-4013-84ad-e63102402a43%2FScreen+Shot+2016-03-30+at+6.02.47+PM.png)
