### ISSUE TITLE
Position of "More" in mobile menu seems incorrect?

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#84]
@alexgreen @kidcompassion Curious about this position of the "More" in the mobile menu: feature or bug? 

<img width="387" alt="localhost_4000" src="https://cloud.githubusercontent.com/assets/34128/14089827/df74b998-f4eb-11e5-8401-b131ded7dbd6.png">

**Comment by alexgreen** [comment]
bug.
There's still quite a bit of tuning to be done on the menus, but based on what Sally has said I believe she has deferred such display issues until other underlying problems with the nav are resolved. So I'm disregarding things like this until she gives us the aok.

**Comment by kidcompassion** [comment]
This is resolve in develop.
