### ISSUE TITLE
Vertical positioning of logo is irregular and in wider views; and logo becomes enormous

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#95]
- [x] Vertical positioning of logo is irregular and in wider views; 
- [x] and logo becomes enormous

![screen shot 2016-03-31 at 10 11 19 pm](https://cloud.githubusercontent.com/assets/151099/14178014/cf40a488-f793-11e5-9966-0a08111542c7.png)

![screen shot 2016-03-31 at 10 11 38 pm](https://cloud.githubusercontent.com/assets/151099/14178017/d2a6b5ae-f793-11e5-9be5-01c806856ff5.png)

![screen shot 2016-03-31 at 10 12 35 pm](https://cloud.githubusercontent.com/assets/151099/14178026/d96718ca-f793-11e5-8aee-8fd68e1522be.png)

![screen shot 2016-03-31 at 10 52 50 pm](https://cloud.githubusercontent.com/assets/151099/14178035/dfbd83f8-f793-11e5-82e7-5f12492f7d80.png)

**Comment by kidcompassion** [comment]
Resolved in bugs/testing-fixes, commit a3bf995a099f9be3bfc9ea776de4bd0f007c8ddd
