### ISSUE TITLE
Comments section has a dark band on ipad.

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#96]
Seems like an opacity issue.

![file 2016-03-31 11 49 06 pm](https://cloud.githubusercontent.com/assets/151099/14179832/907b0af6-f79b-11e5-81af-985b3da02a64.png)

**Comment by phillipadsmith** [comment]
Think it must just be cached... I'll double-check.

**Comment by phillipadsmith** [comment]
Fixed in https://github.com/TheTyee/design-article.thetyee.ca/commit/82462a06cfc9b1a37a392e6cfbd05ce075b85367
