### ISSUE TITLE
Flow real article content into template

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#97]
Article:
http://thetyee.ca/News/2016/01/27/Aboriginal-Rights-Pipeline-Deal/

Author photo:
https://www.flickr.com/photos/46912778@N03/25815906162/in/set-72157636249291295/

**Comment by phillipadsmith** [comment]
@alexgreen @kidcompassion 

Just a note to mention to you both that -- in preparation for sharing of an article page with "friends and family of The Tyee" early next week (Monday or Tuesday) -- I'm going to flow actual content into a template that can be viewed publicly.

I was hoping to do this today, yet I've run out of time. I'll restart this over the weekend.

My plan is roughly to:
- [ ] Create a new layout for the current "kitchen sink" that contains all possible elements
- [ ] Or, alternately, just create a new article__body.html for this purpose that only contains a typical set of elements called something like article_body_w_content.html 
- [ ] From there, I'd like to create a new file, e.g., kitchensink.html that takes the place of the current index.html for the "kitchen sink" of elements. Again, this might mean just creating a new layout like `article-kitchensink` or something

Any thoughts on the above before I get started are welcome.

Hasta pronto,

Phillip.

**Comment by alexgreen** [comment]
Can we call it a "library" instead of a kitchensink? That page will in effect be our component library.

**Comment by alexgreen** [comment]
I'll continue developing components within the library, because that's the only way to see how any one (new or altered) object might affect every other object and flag potential problems.

Hopefully any changes I make will be seamlessly propagated to this new demo page by virtue of the _inclusion of corresponding html object template files. (E.g. if I make a change to /_includes01-molecules/blocks/related-story.html then this will be reflected in any relate-story block that might appear on the demo page.)

**Comment by phillipadsmith** [comment]
> Can we call it a "library" instead of a kitchensink? That page will in effect be our component library.

:+1: 

> Hopefully any changes I make will be seamlessly propagated to this new demo page by virtue of the _inclusion of corresponding html object template files. (E.g. if I make a change to /_includes01-molecules/blocks/related-story.html then this will be reflected in any relate-story block that might appear on the demo page.)

That's what I"m thinking too.

**Comment by phillipadsmith** [comment]
Closed with https://github.com/TheTyee/design-article.thetyee.ca/commit/13759f45cf88c1c5fb7dde3ab82f78e78aa27abf 

The "library" is now at /library.html and needs some updates in the article and article__body to pass parameters into various includes. Happy to fix those up later this week if you don't beat me to it (you'll see the obvious missing elements, and if you check the changes in that last commit you'll see what parameters get passed).

Having worked with the include system and patterns that you've set-up for an evening, @alexgreen, I must give you **huge kudus** for setting up a foundation that is going to move The Tyee light years forward in terms of being able to quickly iterate design changes. 

A sincere thanks to you for what must have felt at times like a thankless job. :-)

**Comment by phillipadsmith** [comment]
I just want to say it again: seriously impressive thinking in terms of how to take the atomic design approach and leveraging the features of Jekyll to make something that is well documented, intuitive, and following the "don't repeat yourself" ethos. Excited to see where this can go next... :-)

**Comment by alexgreen** [comment]
Thanks for the props! I'm pretty happy that it's been possible to carry through what I think is a fairly logical and consistent system. The documentation is a bit haphazard now as I just wrote it on the go, so I'm really glad that it made sense!

It's so great to see it with real content! Thanks for doing that!

> Excited to see where this can go next

My dream is that in the future we'll be able to make design revisions and build new objects simply by editing template _includes that will automatically get propagated into the production website.

**Comment by phillipadsmith** [comment]
> My dream is that in the future we'll be able to make design revisions and build new objects simply by editing template _includes that will automatically get propagated into the production website.

We'll get there one day! :-)

**Comment by alexgreen** [comment]
There's a couple new includes that break the link between the component library and the standard-article. For example,
- 02-organisms/article-standard/featured-media.html
- 02-organisms/article-standard/article__header.html
- fact-box-article-standard.html

So changes to these objects will need to get made in duplicate in order for them to appear in both the library and and the article. Is that right? Am I missing any other duplicate objects?

Is there a way we can make these more DRY?
It does look like the object content could possibly be abstracted as parameters set in article-standard.html and article-standard/article__body.html. (Maybe renaming the latter as article__body--standard.html to avoid object name duplication.) That might dry it out. ?

**Comment by phillipadsmith** [comment]
> Is there a way we can make these more DRY?

Very open to exploring that question. Admittedly, I was just thinking "How can I flow in this content while creating minimum problems," and I'm sure there are better ways to approach this.

Will give it a noodle on Thursday morning.

**Comment by phillipadsmith** [comment]
Well, quick thoughts:
- I think that featured-media.html can be re-used without duplicating it by simply passing in values from the template that includes it as you've done elsewhere, in this case from article-standard.html or article__body
- Similarly, it would be worth an attempt to pass the title, teaser and author info as parameters from the calling template, or -- perhaps even better -- just put those values into the front matter for the page in question and then use them wherever necessary

Based on the above, I think you're right that we could eliminate the "article-standard" directory all together,  and simply create new versions of the article__body to provide the content to that page.

Getting close...

**Comment by phillipadsmith** [comment]
> Based on the above, I think you're right that we could eliminate the "article-standard" directory all together, and simply create new versions of the article__body to provide the content to that page.

I've removed anything special from flowing in the article content and migrated a bunch of properties out of the markup and into front matter in index.html and library.html in this commit: 
https://github.com/TheTyee/design-article.thetyee.ca/commit/bcb62b98907a192ba55a31d9c1a0bb25689cb08a

**Comment by alexgreen** [comment]
feeling the low humidity

**Comment by alexgreen** [comment]
I see the series badge is still showing up on the library (good), but I don't see where the page.series variable is being set. What am I missing?

**Comment by alexgreen** [comment]
...oh I see it's gone now. Must have been cached despite the dev tools.

**Comment by alexgreen** [comment]
Now I'm having the opposite problem. I've set series: Yes in library.html but the series badge still isn't showing up. argh!

**Comment by alexgreen** [comment]
Commenting out the non-functioning variable query for now

**Comment by phillipadsmith** [comment]
> Commenting out the non-functioning variable query for now

Hi Alex,

I'm away this week (since Monday). I'll circle up and address any tickets assigned to me on Sunday, Tuesday and Thursday. 

Phillip.
