### ISSUE TITLE
Missing declarations?

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#99]
@alexgreen What's happening here:
https://github.com/TheTyee/design-article.thetyee.ca/blob/8ef267241247e30c9f77a8b959cfee37a1da00cc/ui/css/article.css#L48

Seem to be a bunch of those, i.e., properties with no values.

**Comment by alexgreen** [comment]
In that case it's just a placeholder that is no longer required.

In other cases, like this
https://github.com/TheTyee/design-article.thetyee.ca/blob/8ef267241247e30c9f77a8b959cfee37a1da00cc/ui/css/article.css#L910
it's to indicate the root of an object (for BEM purposes), even though no styles are actually applied at root itself.

**Comment by phillipadsmith** [comment]
> In other cases, like this

That example is AOK -- it throws no errors in my CSSlinter. It's just the declarations with no value that are showing up as problems.

**Comment by alexgreen** [comment]
I think the empty declarations have been eliminated in my above commit. ?

**Comment by phillipadsmith** [comment]
Yes, I think so. :-)
